fn main() {
    // S0 spike harness (build-sessions/encoder/S0-FINDING.md) — DEBUG BUILDS ONLY.
    //
    // The two probe commands (`probe_report`, `probe_ipc`) and the capability that
    // grants them to https://setnayan.com live in `src/probe.rs` behind
    // `#[cfg(debug_assertions)]` and in `capabilities-debug/`, a directory the
    // default `./capabilities/**/*` glob never reads. Cargo sets `PROFILE` for build
    // scripts ("debug" for `cargo build` / `cargo tauri build --debug`, "release"
    // for `cargo tauri build`), so a release binary neither compiles the commands
    // nor carries the grant. Verify: `strings target/release/setnayan-desktop |
    // grep -c probe_report` must print 0.
    let debug = std::env::var("PROFILE").map(|p| p == "debug").unwrap_or(false);
    // A debug build makes tauri-build write `permissions/autogenerated/<cmd>.toml`
    // for the two commands (gitignored), and tauri-build reads `./permissions/**`
    // in EVERY profile — so a release build on a tree where a debug build ran
    // before it embedded the allow/deny permission DEFINITIONS (no capability
    // grants them, no handler exists, but `strings … | grep -c probe_report` read
    // 1, not 0 — measured 2026-09-05). Drop the stale directory in release so the
    // release binary is byte-clean whether or not a debug build preceded it.
    if !debug {
        let _ = std::fs::remove_dir_all("./permissions/autogenerated");
    }

    // Commands that ship in EVERY build: S8's stream-key commands (own-channel
    // paste + hosted-channel nonce exchange) and S10's keep-awake assertions.
    // Both are real product surface, not spikes, so they are registered
    // unconditionally; only S0's probe commands are gated on `debug`.
    let mut commands: Vec<&'static str> = vec![
        "stream_key_set_pasted",
        "stream_key_claim_hosted",
        "stream_key_forget",
        "start_keep_awake",
        "stop_keep_awake",
    ];

    let mut attrs = tauri_build::Attributes::new();
    if debug {
        commands.push("probe_report");
        commands.push("probe_ipc");
        attrs = attrs.capabilities_path_pattern("./capabilities*/**/*.json");
        println!("cargo:rerun-if-changed=capabilities-debug");
        println!("cargo:rerun-if-changed=probe/encoder-probe.js");
    }
    // AppManifest::commands wants a `&'static [&'static str]`; a build script
    // runs once per build, so leaking this tiny Vec is the simplest way to get
    // one from a list assembled at runtime (debug vs release).
    let commands: &'static [&'static str] = Box::leak(commands.into_boxed_slice());
    attrs = attrs.app_manifest(tauri_build::AppManifest::new().commands(commands));

    tauri_build::try_build(attrs).expect("failed to run tauri-build");
}
