fn main() {
    // S0 spike harness (build-sessions/encoder/S0-FINDING.md) — DEBUG BUILDS ONLY.
    //
    // The two probe commands (`probe_report`, `probe_ipc`) and the capability that
    // grants them to https://setnayan.com live in `src/probe.rs` behind
    // `#[cfg(debug_assertions)]` and in `capabilities-debug/`, a directory the
    // default `./capabilities/**/*` glob never reads. Cargo sets `PROFILE` for build
    // scripts ("debug" for `cargo build` / `cargo tauri build --debug`, "release"
    // for `cargo tauri build`), so a release binary neither compiles the commands
    // nor carries the grant. Verify: `strings target/release/setnayan-desktop |
    // grep -c probe_report` must print 0.
    let debug = std::env::var("PROFILE").map(|p| p == "debug").unwrap_or(false);
    // A debug build makes tauri-build write `permissions/autogenerated/<cmd>.toml`
    // for the two commands (gitignored), and tauri-build reads `./permissions/**`
    // in EVERY profile — so a release build on a tree where a debug build ran
    // before it embedded the allow/deny permission DEFINITIONS (no capability
    // grants them, no handler exists, but `strings … | grep -c probe_report` read
    // 1, not 0 — measured 2026-09-05). Drop the stale directory in release so the
    // release binary is byte-clean whether or not a debug build preceded it.
    if !debug {
        let _ = std::fs::remove_dir_all("./permissions/autogenerated");
    }
    let mut attrs = tauri_build::Attributes::new();
    if debug {
        attrs = attrs
            .app_manifest(tauri_build::AppManifest::new().commands(&["probe_report", "probe_ipc"]))
            .capabilities_path_pattern("./capabilities*/**/*.json");
        println!("cargo:rerun-if-changed=capabilities-debug");
        println!("cargo:rerun-if-changed=probe/encoder-probe.js");
    }
    tauri_build::try_build(attrs).expect("failed to run tauri-build");
}
