#!/usr/bin/env tsx
/**
 * gen-admin-map.ts — write the committed inventory of admin destinations.
 *
 *   pnpm --filter @setnayan/web admin:map
 *
 * 🔑 GENERATED, NEVER AUTHORED — the same posture as port-control-baseline.json
 * and reserved-slugs. Nobody types a route. The committed value cannot drift
 * from the real tree, because a guard re-scans the tree and refuses any
 * difference; the failure mode of a guard comparing two hand-typed things is
 * that both drift together and CI stays green.
 *
 * WHEN TO RE-RUN: after adding, moving or deleting an admin page. The diff is
 * the point — a page appearing or vanishing lands in the pull request as one
 * readable line instead of silently.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

import { scanAdminRoutes } from '../lib/admin-map/scan-admin-routes';

const WEB = join(__dirname, '..');
const OUT = join(WEB, 'lib/admin-map/admin-routes.generated.ts');

let ref = 'unknown';
try {
  ref = execSync('git rev-parse --short HEAD', { cwd: WEB, encoding: 'utf8' }).trim();
} catch {
  /* not a git checkout — the ref is provenance, not a dependency */
}

const routes = scanAdminRoutes(join(WEB, 'app/admin'));
const pages = routes.filter((r) => r.kind === 'page').length;

const body = `// AUTO-GENERATED by scripts/gen-admin-map.ts — do not hand-edit.
// Regenerate with: pnpm --filter @setnayan/web admin:map
//
// Every place inside /admin a person can land, scanned from the route tree.
// ${routes.length} destinations (${pages} real pages, ${routes.length - pages} redirect stubs)
// as of ${ref}. admin-map-is-generated.test.ts fails if this drifts from the tree.

import type { AdminRoute } from './scan-admin-routes';

export const ADMIN_ROUTES: readonly AdminRoute[] = ${JSON.stringify(routes, null, 2)};
`;

writeFileSync(OUT, body);
console.log(
  `admin map: ${routes.length} destinations (${pages} pages, ${routes.length - pages} redirects) → ${OUT}`,
);
