/**
 * gen-taxonomy-seed.ts
 *
 * Emits the SEED SQL for the DB-backed taxonomy tree (service_categories +
 * canonical_service_taxonomy) DERIVED FROM lib/taxonomy.ts — the authored
 * source of truth during the Phase-1 transition. Guarantees DB == code so the
 * /admin/taxonomy editor (0023 §3.15) starts from a perfect mirror.
 *
 *   Regenerate:  npx tsx scripts/gen-taxonomy-seed.ts > /tmp/taxonomy_seed.sql
 *   Then splice the output into the SEED section of the
 *   20260803000000_service_categories_tree_foundation.sql migration.
 *
 * Re-run whenever TAXONOMY_MAP / the folder/tile maps change so the seed stays
 * in lockstep with code until Phase 2 flips the source of truth to the DB.
 */
import {
  WEDDING_FOLDER_ORDER,
  WEDDING_FOLDER_LABEL,
  WEDDING_FOLDER_SHORT_LABEL,
  WEDDING_FOLDER_SLUG,
  WEDDING_TILE_ORDER,
  TILE_PARENT,
  WEDDING_TILE_LABEL,
  WEDDING_TILE_SLUG,
  TAXONOMY_MAP,
} from '../lib/taxonomy';

/** SQL string literal with single-quote escaping; NULL passthrough. */
const q = (s: string | null | undefined): string =>
  s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`;
/** SQL boolean literal. */
const b = (v: boolean | undefined): string => (v ? 'TRUE' : 'FALSE');

// ── Referential-integrity guard — refuse to emit a seed that would FK-fail ────
// Every folder/tile/secondary_tile a canonical references MUST be a seeded node,
// or the canonical_service_taxonomy FKs blow up on `supabase db push`.
const folderSet = new Set<string>(WEDDING_FOLDER_ORDER);
const tileSet = new Set<string>(WEDDING_TILE_ORDER);
const problems: string[] = [];
for (const tile of WEDDING_TILE_ORDER) {
  if (!folderSet.has(TILE_PARENT[tile])) {
    problems.push(`tile '${tile}': parent '${TILE_PARENT[tile]}' not in WEDDING_FOLDER_ORDER`);
  }
}
for (const [canonical, e] of Object.entries(TAXONOMY_MAP)) {
  if (!folderSet.has(e.folder)) {
    problems.push(`${canonical}: folder '${e.folder}' not in WEDDING_FOLDER_ORDER`);
  }
  if (e.tile && !tileSet.has(e.tile)) {
    problems.push(`${canonical}: tile '${e.tile}' not in WEDDING_TILE_ORDER`);
  }
  for (const st of e.secondary_tiles ?? []) {
    if (!tileSet.has(st)) {
      problems.push(`${canonical}: secondary_tile '${st}' not in WEDDING_TILE_ORDER`);
    }
  }
}
if (problems.length > 0) {
  process.stderr.write(`FK integrity FAILED (${problems.length}):\n${problems.join('\n')}\n`);
  process.exit(1);
}

// ── service_categories: 10 parents (tier 1) + ~53 tiles (tier 2) ──────────────
const catRows: string[] = [];
WEDDING_FOLDER_ORDER.forEach((folder, i) => {
  catRows.push(
    `  (${q(folder)}, NULL, 1, 'branch', ${q(WEDDING_FOLDER_LABEL[folder])}, ` +
      `${q(WEDDING_FOLDER_SHORT_LABEL[folder])}, ${q(WEDDING_FOLDER_SLUG[folder])}, ${i}, 'global', FALSE)`,
  );
});
WEDDING_TILE_ORDER.forEach((tile, i) => {
  catRows.push(
    `  (${q(tile)}, ${q(TILE_PARENT[tile])}, 2, 'leaf', ${q(WEDDING_TILE_LABEL[tile])}, ` +
      `NULL, ${q(WEDDING_TILE_SLUG[tile])}, ${i}, 'global', FALSE)`,
  );
});

// ── canonical_service_taxonomy: every TAXONOMY_MAP entry ──────────────────────
const mapRows: string[] = [];
for (const [canonical, e] of Object.entries(TAXONOMY_MAP)) {
  const secondary =
    e.secondary_tiles && e.secondary_tiles.length
      ? `ARRAY[${e.secondary_tiles.map((t) => q(t)).join(', ')}]::TEXT[]`
      : `'{}'::TEXT[]`;
  mapRows.push(
    `  (${q(canonical)}, ${q(e.folder)}, ${e.tile ? q(e.tile) : 'NULL'}, ${q(e.phase)}, ` +
      `${e.faith ? q(e.faith) : 'NULL'}, ${b(e.ph)}, ${b(e.setnayan)}, ${b(e.rental)}, ` +
      `${e.dietary ? q(e.dietary) : 'NULL'}, ${b(e.tradition)}, ${b(e.marketplaceHidden)}, ${secondary})`,
  );
}

const out = `-- ────────────────────────────────────────────────────────────────────────────
-- GENERATED by apps/web/scripts/gen-taxonomy-seed.ts FROM lib/taxonomy.ts.
-- DO NOT HAND-EDIT — re-run the generator after any TAXONOMY_MAP change.
-- ${catRows.length} category nodes (${WEDDING_FOLDER_ORDER.length} parents + ${WEDDING_TILE_ORDER.length} tiles) · ${mapRows.length} canonical mappings.
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO public.service_categories
  (id, parent_id, tier, kind, label_en, label_short, slug, sort_order, scope, marketplace_hidden)
VALUES
${catRows.join(',\n')}
ON CONFLICT (id) DO UPDATE SET
  parent_id   = EXCLUDED.parent_id,
  tier        = EXCLUDED.tier,
  kind        = EXCLUDED.kind,
  label_en    = EXCLUDED.label_en,
  label_short = EXCLUDED.label_short,
  slug        = EXCLUDED.slug,
  sort_order  = EXCLUDED.sort_order,
  updated_at  = now();

INSERT INTO public.canonical_service_taxonomy
  (canonical_service, folder_id, tile_id, phase, faith, is_ph, is_setnayan, is_rental, dietary, is_tradition, marketplace_hidden, secondary_tiles)
VALUES
${mapRows.join(',\n')}
ON CONFLICT (canonical_service) DO UPDATE SET
  folder_id          = EXCLUDED.folder_id,
  tile_id            = EXCLUDED.tile_id,
  phase              = EXCLUDED.phase,
  faith              = EXCLUDED.faith,
  is_ph              = EXCLUDED.is_ph,
  is_setnayan        = EXCLUDED.is_setnayan,
  is_rental          = EXCLUDED.is_rental,
  dietary            = EXCLUDED.dietary,
  is_tradition       = EXCLUDED.is_tradition,
  marketplace_hidden = EXCLUDED.marketplace_hidden,
  secondary_tiles    = EXCLUDED.secondary_tiles,
  updated_at         = now();
`;

process.stdout.write(out);
