#!/usr/bin/env tsx
/**
 * gen-admin-jobs.ts — write the committed checklist of what each admin job asks for.
 *
 *   pnpm --filter @setnayan/web admin:jobs
 *
 * Companion to gen-admin-map.ts: that one records WHERE things are, this one
 * records WHAT A JOB NEEDS. Same rule — generated, never authored — and the same
 * guard shape: a test re-scans and refuses any difference.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

import { scanAdminJobs } from '../lib/admin-map/scan-admin-jobs';

const WEB = join(__dirname, '..');
const OUT = join(WEB, 'lib/admin-map/admin-jobs.generated.ts');

let ref = 'unknown';
try {
  ref = execSync('git rev-parse --short HEAD', { cwd: WEB, encoding: 'utf8' }).trim();
} catch {
  /* not a git checkout — the ref is provenance, not a dependency */
}

const jobs = scanAdminJobs(join(WEB, 'app/admin'));
const withFields = jobs.filter((j) => j.fields.length).length;

const body = `// AUTO-GENERATED by scripts/gen-admin-jobs.ts — do not hand-edit.
// Regenerate with: pnpm --filter @setnayan/web admin:jobs
//
// Every job the admin can perform and what it asks for, read out of the action
// that performs it. ${jobs.length} jobs, ${withFields} of them form-driven, as of ${ref}.
// admin-jobs-are-generated.test.ts fails if this drifts from the code.

import type { AdminJob } from './scan-admin-jobs';

export const ADMIN_JOBS: readonly AdminJob[] = ${JSON.stringify(jobs, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`admin jobs: ${jobs.length} (${withFields} form-driven) → ${OUT}`);
