/**
 * POST /api/v1/manpower/sync-device
 *
 * V2 on-site crew device handshake. Processes a scanned Master Event QR
 * payload, captures the browser device fingerprint, INSERTs into
 * `registered_crew_devices` (the BEFORE INSERT trigger enforces the 5-cap),
 * and UPSERTs `event_software_activations_v2` so the calling vendor is
 * stamped as the definitive owner-stamp for that event's token rewards.
 *
 * Master Event QR is a rolling 60s hash regenerated by the couple's Phase 2
 * wedding website route. The hash structure is `{event_id}.{timestamp_60s_bucket}.{sig}`.
 * Server-side validation accepts hashes within ±2 buckets (±2 minutes) of
 * current server time to absorb clock skew + scan latency.
 *
 * Auth: cookie session (vendor team member of `vendor_id`). DEMO_MODE
 * bypasses auth + DB writes and returns a synthesized device_id + seat
 * count so the walkthrough video can record the flow.
 *
 * Spec corpus: V2_Cutover_Plan_2026-05-28.md Phase D (master event QR +
 * crew device handshake). Blueprint Part 4 § 1 Step 1-2.
 */

import { NextResponse } from 'next/server';
import { createHmac } from 'node:crypto';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';

type SyncBody = {
  event_id?: string;
  vendor_id?: string;
  device_fingerprint?: string;
  master_qr_payload?: string;
  canvas_signature_data_url?: string; // optional · operator's canvas sig
  service_code?: string; // optional · which service this device serves (defaults CAMERA_BRIDGE)
};

const DEMO_MODE = process.env.SETNAYAN_DEMO_MODE === '1';
const MAX_SEATS = 5;
const ROLLING_HASH_BUCKET_SECONDS = 60;
const HASH_ACCEPT_WINDOW = 2; // ±2 buckets = ±2 minutes tolerance

export async function POST(req: Request) {
  let body: SyncBody;
  try {
    body = (await req.json()) as SyncBody;
  } catch {
    return err(400, 'invalid_json', 'Request body is not valid JSON.');
  }

  const eventId = body.event_id?.trim();
  const vendorId = body.vendor_id?.trim();
  const fingerprint = body.device_fingerprint?.trim();
  const qrPayload = body.master_qr_payload?.trim();
  const serviceCode = (body.service_code ?? 'CAMERA_BRIDGE').trim().toUpperCase();

  if (!eventId) return err(400, 'missing_event_id', 'event_id is required.');
  if (!vendorId) return err(400, 'missing_vendor_id', 'vendor_id is required.');
  if (!fingerprint) return err(400, 'missing_fingerprint', 'device_fingerprint is required.');
  if (fingerprint.length < 16 || fingerprint.length > 256) {
    return err(400, 'invalid_fingerprint', 'device_fingerprint length must be 16-256 chars.');
  }
  if (!qrPayload) return err(400, 'missing_qr_payload', 'master_qr_payload is required.');

  // ---- Validate Master Event QR rolling-60s hash -----------------------------
  const qrValidation = validateMasterEventQr(qrPayload, eventId);
  if (!qrValidation.ok) {
    return err(400, 'invalid_qr', qrValidation.reason);
  }

  // ---- Auth + vendor team membership -----------------------------------------
  if (!DEMO_MODE) {
    const supabase = await createClient();
    const { data: userResult } = await supabase.auth.getUser();
    const userId = userResult?.user?.id;
    if (!userId) return err(401, 'unauthenticated', 'Sign in required.');

    const admin = createAdminClient();
    const { data: vendorMembership } = await admin
      .from('vendor_service_agents')
      .select('member_id')
      .eq('vendor_id', vendorId)
      .eq('member_id', userId)
      .maybeSingle();

    // Also accept the case where userId is the vendor's owner.
    let allowed = !!vendorMembership;
    if (!allowed) {
      const { data: vendorOwner } = await admin
        .from('vendor_profiles')
        .select('owner_user_id')
        .eq('vendor_profile_id', vendorId)
        .maybeSingle();
      allowed = vendorOwner?.owner_user_id === userId;
    }

    if (!allowed) {
      return err(403, 'not_vendor_team', 'You are not on this vendor team.');
    }
  }

  // ---- DEMO MODE short-circuit ------------------------------------------------
  if (DEMO_MODE) {
    const synthDeviceId = synthesizeDeviceId(eventId, fingerprint);
    // Deterministic-ish seat count for the demo · cycles 1→5 by fingerprint hash.
    const synthSeatCount = (hashToInt(fingerprint) % MAX_SEATS) + 1;
    return ok({
      device_id: synthDeviceId,
      event_id: eventId,
      vendor_id: vendorId,
      device_fingerprint: redactFingerprint(fingerprint),
      current_seat_count: synthSeatCount,
      max_seats: MAX_SEATS,
      seats_remaining: MAX_SEATS - synthSeatCount,
      service_activation: {
        service_code: serviceCode,
        is_reward_issued: false,
        owner_stamped_vendor_id: vendorId,
      },
      canvas_signature_captured: !!body.canvas_signature_data_url,
      qr_validated_at_bucket: qrValidation.bucket,
      registered_at: new Date().toISOString(),
      mode: 'demo',
    });
  }

  // ---- Live mode · DB writes -------------------------------------------------
  const admin = createAdminClient();

  // INSERT into registered_crew_devices · 5-cap trigger raises
  // CREW_SEAT_LIMIT_EXCEEDED if event already has 5 devices.
  const { data: inserted, error: insertErr } = await admin
    .from('registered_crew_devices')
    .insert({
      event_id: eventId,
      vendor_id: vendorId,
      device_fingerprint: fingerprint,
    })
    .select('id, registered_at')
    .single();

  if (insertErr) {
    // Trigger-raised exception comes through as a regular error message.
    if (insertErr.message?.includes('CREW_SEAT_LIMIT_EXCEEDED')) {
      return err(409, 'crew_seat_limit_exceeded',
        'Maximum 5 crew device seats already registered for this event.');
    }
    // UNIQUE(event_id, device_fingerprint) collision → idempotent path
    if (insertErr.code === '23505') {
      const { data: existing } = await admin
        .from('registered_crew_devices')
        .select('id, registered_at')
        .eq('event_id', eventId)
        .eq('device_fingerprint', fingerprint)
        .maybeSingle();
      if (existing) {
        return ok({
          device_id: existing.id,
          event_id: eventId,
          vendor_id: vendorId,
          device_fingerprint: redactFingerprint(fingerprint),
          already_registered: true,
          registered_at: existing.registered_at,
          max_seats: MAX_SEATS,
        });
      }
    }
    return err(500, 'device_insert_error', insertErr.message);
  }

  // UPSERT event_software_activations_v2 to stamp Vendor ID as owner for
  // this event's `service_code` row. Idempotent on the unique constraint
  // UNIQUE(event_id, service_code).
  const { error: activationErr } = await admin
    .from('event_software_activations_v2')
    .upsert(
      {
        event_id: eventId,
        vendor_id: vendorId,
        service_code: serviceCode,
        is_reward_issued: false,
      },
      { onConflict: 'event_id,service_code', ignoreDuplicates: true },
    );
  if (activationErr) {
    // Activation failure is non-fatal for the device registration — log the
    // error but return success on the device row.
    console.error('[sync-device] event_software_activations_v2 upsert failed', {
      eventId, vendorId, serviceCode, error: activationErr.message,
    });
  }

  // Recount seats to return accurate current_seat_count.
  const { count: seatCount } = await admin
    .from('registered_crew_devices')
    .select('id', { count: 'exact', head: true })
    .eq('event_id', eventId);

  return ok({
    device_id: inserted.id,
    event_id: eventId,
    vendor_id: vendorId,
    device_fingerprint: redactFingerprint(fingerprint),
    current_seat_count: seatCount ?? 1,
    max_seats: MAX_SEATS,
    seats_remaining: MAX_SEATS - (seatCount ?? 1),
    service_activation: {
      service_code: serviceCode,
      is_reward_issued: false,
      owner_stamped_vendor_id: vendorId,
    },
    canvas_signature_captured: !!body.canvas_signature_data_url,
    qr_validated_at_bucket: qrValidation.bucket,
    registered_at: inserted.registered_at,
    mode: 'live',
  });
}

// ---------- helpers ----------

function ok(body: unknown): NextResponse {
  return NextResponse.json(body, {
    headers: { 'Cache-Control': 'no-store', 'Content-Type': 'application/json; charset=utf-8' },
  });
}

function err(status: number, code: string, message: string): NextResponse {
  return NextResponse.json({ error: { code, message } }, {
    status,
    headers: { 'Cache-Control': 'no-store' },
  });
}

type QrValidation =
  | { ok: true; bucket: number }
  | { ok: false; reason: string };

/**
 * Validate the Master Event QR rolling-60s hash. Expected payload shape:
 *   `{event_id}.{bucket_int}.{sig_hex}`
 * where `sig_hex = HMAC_SHA256(MASTER_QR_SECRET, "${event_id}:${bucket}").slice(0, 32)`.
 * Hash is accepted if `bucket` is within ±2 of the current minute-bucket.
 *
 * In DEMO_MODE we accept any well-formed payload to make filming easy.
 */
function validateMasterEventQr(payload: string, expectedEventId: string): QrValidation {
  const parts = payload.split('.');
  if (parts.length !== 3) {
    return { ok: false, reason: 'master_qr_payload must be "event_id.bucket.sig"' };
  }
  const [evtId, bucketStr, sig] = parts;
  if (evtId !== expectedEventId) {
    return { ok: false, reason: 'QR payload event_id does not match body event_id' };
  }
  if (!bucketStr || !sig) {
    return { ok: false, reason: 'QR payload is missing bucket or signature segments' };
  }
  const bucket = Number.parseInt(bucketStr, 10);
  if (!Number.isFinite(bucket) || bucket < 0) {
    return { ok: false, reason: 'QR bucket is not a valid integer' };
  }
  const nowBucket = Math.floor(Date.now() / (ROLLING_HASH_BUCKET_SECONDS * 1000));
  const skew = Math.abs(nowBucket - bucket);
  if (skew > HASH_ACCEPT_WINDOW) {
    return { ok: false, reason: `QR bucket out of window (skew=${skew} buckets, max=${HASH_ACCEPT_WINDOW})` };
  }

  if (DEMO_MODE) {
    return { ok: true, bucket };
  }

  const secret = process.env.MASTER_QR_SECRET;
  if (!secret) {
    // Fail-closed in live mode if the secret isn't configured.
    return { ok: false, reason: 'Server MASTER_QR_SECRET not configured.' };
  }
  const expectedSig = createHmac('sha256', secret)
    .update(`${expectedEventId}:${bucket}`)
    .digest('hex')
    .slice(0, 32);
  if (sig !== expectedSig) {
    return { ok: false, reason: 'QR signature mismatch.' };
  }
  return { ok: true, bucket };
}

function synthesizeDeviceId(eventId: string, fingerprint: string): string {
  const evtPrefix = eventId.split('-')[0]?.slice(0, 8).toUpperCase() ?? 'EVENT';
  const fpTail = hashToInt(fingerprint).toString(36).toUpperCase().slice(-6).padStart(6, '0');
  return `DEV-${evtPrefix}-${fpTail}`;
}

function redactFingerprint(fp: string): string {
  if (fp.length <= 12) return '***';
  return `${fp.slice(0, 4)}...${fp.slice(-4)}`;
}

function hashToInt(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}
