/**
 * apps/web/lib/cipher-shared.ts
 *
 * Cipher Monogram — shared registry + config model (client-safe, no IO).
 * Phase 3 of the monogram overhaul (owner-designed 2026-06-11): the couple
 * POSITIONS two initials (drag · size · rotate · mirror) and the engine
 * renders them as one designed mark — either a smooth single-ribbon RESTROKE
 * (single-line fonts), an over/under WEAVE with an adjustable knockout gap
 * (filled fonts), or a plain overlap. Fully deterministic SVG · ₱0/use ·
 * no AI. The 15-font set is owner-locked (all SIL OFL — see
 * assets/cipher-fonts/LICENSES.md).
 *
 * Geometry ships as prebuilt JSON under public/cipher/ (one file per font,
 * generated by scripts/build-cipher-fonts.mts) so the editor preview and the
 * server save path render through the SAME pure code (lib/cipher-render.ts)
 * — preview is pixel-identical to the saved mark, and the saved SVG is pure
 * paths (a data-URI <img> can't load webfonts).
 */

export type CipherFontKind = 'stroke' | 'filled';

export type CipherFont = {
  key: string;
  label: string;
  kind: CipherFontKind;
  hint: string;
};

export const CIPHER_FONTS: CipherFont[] = [
  // ── Flowing scripts (single-line centerlines → smooth restroke) ──
  { key: 'allure', label: 'Allure', kind: 'stroke', hint: 'Flowing Spencerian — the classic' },
  { key: 'society', label: 'Society', kind: 'stroke', hint: 'Ornate, dramatic flourishes' },
  { key: 'swiss', label: 'Swiss', kind: 'stroke', hint: 'Slender and airy' },
  { key: 'decorous', label: 'Decorous', kind: 'stroke', hint: 'Tidy formal copperplate' },
  { key: 'invite', label: 'Invite', kind: 'stroke', hint: 'Fine-nib engraved' },
  // ── Filled faces (overlap / over-under weave) ──
  { key: 'mr-de-haviland', label: 'Mr De Haviland', kind: 'filled', hint: 'Spencerian with body' },
  { key: 'pinyon-script', label: 'Pinyon Script', kind: 'filled', hint: 'Refined roundhand' },
  { key: 'herr-von-muellerhoff', label: 'Herr Von Muellerhoff', kind: 'filled', hint: 'Whisper-fine signature' },
  { key: 'luxurious-script', label: 'Luxurious Script', kind: 'filled', hint: 'Lush formal script' },
  { key: 'tangerine', label: 'Tangerine', kind: 'filled', hint: 'Delicate chancery' },
  { key: 'cinzel', label: 'Cinzel', kind: 'filled', hint: 'Engraved roman capitals' },
  { key: 'cormorant', label: 'Cormorant', kind: 'filled', hint: 'High-contrast garalde' },
  { key: 'bodoni-moda', label: 'Bodoni Moda', kind: 'filled', hint: 'Didone glamour' },
  { key: 'libre-caslon-display', label: 'Libre Caslon', kind: 'filled', hint: 'Classic display Caslon' },
  { key: 'vidaloka', label: 'Vidaloka', kind: 'filled', hint: 'Sturdy didone' },
];

export function cipherFont(key: string): CipherFont | null {
  return CIPHER_FONTS.find((f) => f.key === key) ?? null;
}

/** Public URL of a font's prebuilt geometry JSON. */
export function cipherFontDataUrl(font: CipherFont): string {
  return font.kind === 'stroke'
    ? `/cipher/strokes/${font.key}.json`
    : `/cipher/glyphs/${font.key}.json`;
}

export type CipherInk = 'gold' | 'mulberry' | 'obsidian';

export const CIPHER_INKS: { key: CipherInk; label: string }[] = [
  { key: 'gold', label: 'Gold leaf' },
  { key: 'mulberry', label: 'Mulberry' },
  { key: 'obsidian', label: 'Obsidian' },
];

/** How the two letters combine. Restroke is stroke-fonts-only; weave is
 *  filled-fonts-only; overlap works everywhere. */
export type CipherMode = 'overlap' | 'restroke' | 'weave';

export type CipherPlacement = {
  x: number;
  y: number;
  scale: number;
  rot: number;
  /** Mirror flags: ±1. */
  fx: 1 | -1;
  fy: 1 | -1;
};

export type CipherConfig = {
  v: 1;
  initials: [string, string];
  fontKey: string;
  ink: CipherInk;
  mode: CipherMode;
  /** Weave knockout gap (canvas units, 0–24). */
  gap: number;
  /** Restroke connector tension (0.2–1.1). */
  tension: number;
  /** Which letter sits on top / carries the weave: 1 or 2. */
  front: 1 | 2;
  letters: [CipherPlacement, CipherPlacement];
};

export const CIPHER_CANVAS = 400; // design space (square)

export function defaultCipherConfig(a: string, b: string): CipherConfig {
  return {
    v: 1,
    initials: [a, b],
    fontKey: 'allure',
    ink: 'gold',
    mode: 'restroke',
    gap: 8,
    tension: 0.5,
    front: 2,
    letters: [
      { x: 232, y: 168, scale: 0.16, rot: -4, fx: 1, fy: 1 },
      { x: 168, y: 224, scale: 0.18, rot: 3, fx: 1, fy: 1 },
    ],
  };
}

const clamp = (v: number, lo: number, hi: number) =>
  Math.min(hi, Math.max(lo, Number.isFinite(v) ? v : lo));

/**
 * Validate + normalize an untrusted config (the save action receives it from
 * the client). Returns null when structurally unusable; otherwise a clamped,
 * mode-coherent copy safe to render and store.
 */
export function sanitizeCipherConfig(raw: unknown): CipherConfig | null {
  if (!raw || typeof raw !== 'object') return null;
  const o = raw as Record<string, unknown>;
  const font = cipherFont(String(o.fontKey ?? ''));
  if (!font) return null;

  const init = Array.isArray(o.initials) ? o.initials : [];
  const a = String(init[0] ?? '').replace(/[^A-Za-z]/g, '').toUpperCase().slice(0, 1);
  const b = String(init[1] ?? '').replace(/[^A-Za-z]/g, '').toUpperCase().slice(0, 1);
  if (!a || !b) return null;

  const inks: CipherInk[] = ['gold', 'mulberry', 'obsidian'];
  const ink = inks.includes(o.ink as CipherInk) ? (o.ink as CipherInk) : 'gold';

  let mode = (['overlap', 'restroke', 'weave'] as const).includes(o.mode as CipherMode)
    ? (o.mode as CipherMode)
    : 'overlap';
  // Mode/kind coherence: restroke needs centerlines; weave needs fills.
  if (mode === 'restroke' && font.kind !== 'stroke') mode = 'overlap';
  if (mode === 'weave' && font.kind !== 'filled') mode = 'overlap';

  const lettersRaw = Array.isArray(o.letters) ? o.letters : [];
  const letters = [0, 1].map((i) => {
    const l = (lettersRaw[i] ?? {}) as Record<string, unknown>;
    return {
      x: clamp(Number(l.x), -CIPHER_CANVAS, CIPHER_CANVAS * 2),
      y: clamp(Number(l.y), -CIPHER_CANVAS, CIPHER_CANVAS * 2),
      scale: clamp(Number(l.scale), 0.04, 0.6),
      rot: clamp(Number(l.rot), -180, 180),
      fx: l.fx === -1 ? -1 : 1,
      fy: l.fy === -1 ? -1 : 1,
    } as CipherPlacement;
  }) as [CipherPlacement, CipherPlacement];

  return {
    v: 1,
    initials: [a, b],
    fontKey: font.key,
    ink,
    mode,
    gap: clamp(Number(o.gap), 0, 24),
    tension: clamp(Number(o.tension), 0.2, 1.1),
    front: o.front === 1 ? 1 : 2,
    letters,
  };
}
