// ============================================================================
// GENERATED FILE — DO NOT EDIT BY HAND.
//
//   regenerate:  node scripts/gen-color-vocabulary.mjs
//   source:      apps/web/scripts/color-system.md   (the owner's colour system)
//   generator:   apps/web/scripts/gen-color-vocabulary.mjs
//
// The Setnayan moodboard colour vocabulary: 24 hue families every 15°, 4
// neutral families, 336 named swatches, 13 metallics, 12 curated palettes.
//
// 🔑 THE SHAPE IS THE POINT. The FAMILY name is Filipino (Rosas, Dagat,
// Takipsilim, Kalachuchi); the SWATCH names are universal wedding vocabulary
// (Blush Rose, Antique Rose, Old Rose, Rosewood, Claret). A supplier reads a
// word they already know; the system's spine stays Filipino. Do not "simplify"
// by translating either half into the other.
//
// ⚠ THIS MODULE IS DATA ONLY — no imports, no logic. It deliberately does not
// import from './color-space' (owned by another change in flight) or from
// './color-names' (which will consume it), so it can never be half of an import
// cycle and can never be broken by a change to the colour maths.
// ============================================================================

/** A finish is a SURFACE property, not a colour. Only metallics carry one. */
export type MetallicFinish = 'polished' | 'brushed' | 'satin' | 'matte' | 'iridescent';

export type FamilyTemperature = 'warm' | 'cool' | 'neutral';

/** The 12-step ladder every family runs, light → dark. The 500 step carries
 *  the family name. */
export type SwatchStep = 25 | 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950;

export type SetnayanSwatch = {
  /** Universal wedding vocabulary — the word a supplier reads. Unique across all 336. */
  name: string;
  hex: string;
  /** Slug of the family in `SETNAYAN_FAMILIES` this step belongs to. */
  family: string;
  step: SwatchStep;
  /**
   * The text colour the system pairs with this swatch, verified ≥ 4.5:1 (WCAG
   * AA normal text) against it. Null for the neutral families, whose tables
   * publish no text-on column.
   */
  textOn: string | null;
};

export type SetnayanFamily = {
  slug: string;
  /** The Filipino name — the spine of the system. Also the `500` step's swatch name. */
  filipino: string;
  english: string;
  kind: 'hue' | 'neutral';
  /** Position on the 24-spoke wheel, in degrees. Null for the neutral families. */
  degrees: number | null;
  /** What the Filipino word names in the world — "mango", "dusk", "mangrove". */
  gloss: string | null;
  /** Extra editorial note from the source, e.g. "Setnayan's signature gold". */
  note: string | null;
  temperature: FamilyTemperature | null;
  /** Mood words a couple or stylist would brief with — "romantic", "black-tie". */
  moods: readonly string[];
  /** Slug of the family opposite on the wheel. */
  complement: string | null;
  /** Slugs of the two families forming an equilateral triad with this one. */
  triad: readonly string[];
};

export type SetnayanMetallic = {
  slug: string;
  filipino: string;
  english: string;
  hex: string;
  finish: MetallicFinish;
  note: string;
};

export type SetnayanPalette = {
  slug: string;
  filipino: string;
  english: string;
  description: string;
  season: string;
  formality: string;
  members: readonly { hex: string; name: string }[];
};

/** A brand token pinned to one swatch, so the brand and the vocabulary cannot drift apart. */
export type SetnayanAnchor = { token: string; name: string; ref: string; hex: string };

// ── the 28 families ───────────────────────────────────────────────────────────
export const SETNAYAN_FAMILIES: readonly SetnayanFamily[] = [
  {
    slug: 'rosas',
    filipino: 'Rosas',
    english: 'Rose',
    kind: 'hue',
    degrees: 0,
    gloss: 'rose',
    note: null,
    temperature: 'warm',
    moods: ['romantic', 'classic', 'garden'],
    complement: 'bakawan',
    triad: ['kalamansi', 'bughaw'],
  },
  {
    slug: 'gumamela',
    filipino: 'Gumamela',
    english: 'Hibiscus',
    kind: 'hue',
    degrees: 15,
    gloss: 'hibiscus flower',
    note: null,
    temperature: 'warm',
    moods: ['bold', 'tropical', 'festive'],
    complement: 'dagat',
    triad: ['ilangilang', 'karagatan'],
  },
  {
    slug: 'santan',
    filipino: 'Santan',
    english: 'Ixora',
    kind: 'hue',
    degrees: 30,
    gloss: 'ixora blossom',
    note: null,
    temperature: 'warm',
    moods: ['warm', 'festive', 'provincial'],
    complement: 'alon',
    triad: ['dahon', 'gabi'],
  },
  {
    slug: 'caballero',
    filipino: 'Caballero',
    english: 'Fire Tree',
    kind: 'hue',
    degrees: 45,
    gloss: 'flame tree bloom',
    note: null,
    temperature: 'warm',
    moods: ['sunset', 'tropical', 'bold'],
    complement: 'langit',
    triad: ['pandan', 'takipsilim'],
  },
  {
    slug: 'palayok',
    filipino: 'Palayok',
    english: 'Terracotta',
    kind: 'hue',
    degrees: 60,
    gloss: 'clay pot',
    note: null,
    temperature: 'warm',
    moods: ['earthy', 'rustic', 'heritage'],
    complement: 'bughaw',
    triad: ['bakawan', 'ube'],
  },
  {
    slug: 'mangga',
    filipino: 'Mangga',
    english: 'Mango',
    kind: 'hue',
    degrees: 75,
    gloss: 'mango',
    note: null,
    temperature: 'warm',
    moods: ['tropical', 'joyful', 'harvest'],
    complement: 'karagatan',
    triad: ['dagat', 'walingwaling'],
  },
  {
    slug: 'araw',
    filipino: 'Araw',
    english: 'Sun',
    kind: 'hue',
    degrees: 90,
    gloss: 'sun',
    note: "Setnayan's signature gold",
    temperature: 'warm',
    moods: ['luminous', 'luxe', 'signature'],
    complement: 'gabi',
    triad: ['alon', 'bugambilya'],
  },
  {
    slug: 'narra',
    filipino: 'Narra',
    english: 'Narra Bloom',
    kind: 'hue',
    degrees: 105,
    gloss: 'narra tree flower',
    note: null,
    temperature: 'warm',
    moods: ['heritage', 'sunlit', 'harvest'],
    complement: 'takipsilim',
    triad: ['langit', 'kalachuchi'],
  },
  {
    slug: 'kalamansi',
    filipino: 'Kalamansi',
    english: 'Citron',
    kind: 'hue',
    degrees: 120,
    gloss: 'calamansi lime',
    note: null,
    temperature: 'warm',
    moods: ['fresh', 'citrus', 'daytime'],
    complement: 'ube',
    triad: ['bughaw', 'rosas'],
  },
  {
    slug: 'ilangilang',
    filipino: 'Ilang-Ilang',
    english: 'Ylang-Ylang',
    kind: 'hue',
    degrees: 135,
    gloss: 'ylang-ylang blossom',
    note: null,
    temperature: 'neutral',
    moods: ['botanical', 'fragrant', 'garden'],
    complement: 'walingwaling',
    triad: ['karagatan', 'gumamela'],
  },
  {
    slug: 'dahon',
    filipino: 'Dahon',
    english: 'Leaf',
    kind: 'hue',
    degrees: 150,
    gloss: 'leaf',
    note: null,
    temperature: 'cool',
    moods: ['botanical', 'garden', 'natural'],
    complement: 'bugambilya',
    triad: ['gabi', 'santan'],
  },
  {
    slug: 'pandan',
    filipino: 'Pandan',
    english: 'Pandan',
    kind: 'hue',
    degrees: 165,
    gloss: 'pandan leaf',
    note: null,
    temperature: 'cool',
    moods: ['fresh', 'botanical', 'kitchen'],
    complement: 'kalachuchi',
    triad: ['takipsilim', 'caballero'],
  },
  {
    slug: 'bakawan',
    filipino: 'Bakawan',
    english: 'Mangrove',
    kind: 'hue',
    degrees: 180,
    gloss: 'mangrove',
    note: null,
    temperature: 'cool',
    moods: ['coastal', 'jewel', 'moody'],
    complement: 'rosas',
    triad: ['ube', 'palayok'],
  },
  {
    slug: 'dagat',
    filipino: 'Dagat',
    english: 'Sea',
    kind: 'hue',
    degrees: 195,
    gloss: 'the sea',
    note: "Setnayan's verified teal",
    temperature: 'cool',
    moods: ['coastal', 'trust', 'signature'],
    complement: 'gumamela',
    triad: ['walingwaling', 'mangga'],
  },
  {
    slug: 'alon',
    filipino: 'Alon',
    english: 'Wave',
    kind: 'hue',
    degrees: 210,
    gloss: 'wave',
    note: null,
    temperature: 'cool',
    moods: ['coastal', 'airy', 'destination'],
    complement: 'santan',
    triad: ['bugambilya', 'araw'],
  },
  {
    slug: 'langit',
    filipino: 'Langit',
    english: 'Sky',
    kind: 'hue',
    degrees: 225,
    gloss: 'sky',
    note: null,
    temperature: 'cool',
    moods: ['airy', 'daytime', 'outdoor'],
    complement: 'caballero',
    triad: ['kalachuchi', 'narra'],
  },
  {
    slug: 'bughaw',
    filipino: 'Bughaw',
    english: 'Blue',
    kind: 'hue',
    degrees: 240,
    gloss: 'blue',
    note: null,
    temperature: 'cool',
    moods: ['classic', 'formal', 'black-tie'],
    complement: 'palayok',
    triad: ['rosas', 'kalamansi'],
  },
  {
    slug: 'karagatan',
    filipino: 'Karagatan',
    english: 'Ocean',
    kind: 'hue',
    degrees: 255,
    gloss: 'open ocean',
    note: null,
    temperature: 'cool',
    moods: ['formal', 'deep', 'evening'],
    complement: 'mangga',
    triad: ['gumamela', 'ilangilang'],
  },
  {
    slug: 'gabi',
    filipino: 'Gabi',
    english: 'Night',
    kind: 'hue',
    degrees: 270,
    gloss: 'night',
    note: null,
    temperature: 'cool',
    moods: ['evening', 'celestial', 'moody'],
    complement: 'araw',
    triad: ['santan', 'dahon'],
  },
  {
    slug: 'takipsilim',
    filipino: 'Takipsilim',
    english: 'Dusk',
    kind: 'hue',
    degrees: 285,
    gloss: 'dusk',
    note: "Setnayan's dark canvas",
    temperature: 'cool',
    moods: ['romantic', 'signature', 'evening'],
    complement: 'narra',
    triad: ['caballero', 'pandan'],
  },
  {
    slug: 'ube',
    filipino: 'Ube',
    english: 'Purple Yam',
    kind: 'hue',
    degrees: 300,
    gloss: 'purple yam',
    note: null,
    temperature: 'cool',
    moods: ['playful', 'filipino', 'dessert'],
    complement: 'kalamansi',
    triad: ['palayok', 'bakawan'],
  },
  {
    slug: 'walingwaling',
    filipino: 'Waling-Waling',
    english: 'Orchid',
    kind: 'hue',
    degrees: 315,
    gloss: 'waling-waling orchid',
    note: null,
    temperature: 'cool',
    moods: ['luxe', 'regal', 'floral'],
    complement: 'ilangilang',
    triad: ['mangga', 'dagat'],
  },
  {
    slug: 'bugambilya',
    filipino: 'Bugambilya',
    english: 'Bougainvillea',
    kind: 'hue',
    degrees: 330,
    gloss: 'bougainvillea',
    note: null,
    temperature: 'warm',
    moods: ['festive', 'bold', 'fiesta'],
    complement: 'dahon',
    triad: ['araw', 'alon'],
  },
  {
    slug: 'kalachuchi',
    filipino: 'Kalachuchi',
    english: 'Plumeria',
    kind: 'hue',
    degrees: 345,
    gloss: 'plumeria / frangipani',
    note: null,
    temperature: 'warm',
    moods: ['romantic', 'bridal', 'soft'],
    complement: 'pandan',
    triad: ['narra', 'langit'],
  },
  {
    slug: 'buhangin',
    filipino: 'Buhangin',
    english: 'Sand',
    kind: 'neutral',
    degrees: null,
    gloss: 'sand',
    note: 'warm neutral',
    temperature: 'warm',
    moods: [],
    complement: null,
    triad: [],
  },
  {
    slug: 'abo',
    filipino: 'Abo',
    english: 'Ash',
    kind: 'neutral',
    degrees: null,
    gloss: 'ash',
    note: 'true neutral',
    temperature: 'neutral',
    moods: [],
    complement: null,
    triad: [],
  },
  {
    slug: 'ulap',
    filipino: 'Ulap',
    english: 'Cloud',
    kind: 'neutral',
    degrees: null,
    gloss: 'cloud',
    note: 'cool neutral',
    temperature: 'cool',
    moods: [],
    complement: null,
    triad: [],
  },
  {
    slug: 'lupa',
    filipino: 'Lupa',
    english: 'Earth',
    kind: 'neutral',
    degrees: null,
    gloss: 'earth',
    note: 'brown neutral',
    temperature: null,
    moods: [],
    complement: null,
    triad: [],
  },
];

// ── the 336 named swatches ───────────────────────────────────────────────
//
// Grouped by family, in ladder order. Names are unique across the whole table
// and so are hexes — the generator refuses to emit if either stops being true.
export const SETNAYAN_SWATCHES: readonly SetnayanSwatch[] = [
  // Rosas · Rose (0°)
  { name: 'Rose Mist', hex: '#FFF8FA', family: 'rosas', step: 25, textOn: '#101010' },
  { name: 'Powder Rose', hex: '#FFEFF3', family: 'rosas', step: 50, textOn: '#101010' },
  { name: 'Rose Petal', hex: '#FFDEE7', family: 'rosas', step: 100, textOn: '#101010' },
  { name: 'Blush Rose', hex: '#FEC1D3', family: 'rosas', step: 200, textOn: '#101010' },
  { name: 'Rosé', hex: '#FE9FBC', family: 'rosas', step: 300, textOn: '#101010' },
  { name: 'Antique Rose', hex: '#F27DA4', family: 'rosas', step: 400, textOn: '#101010' },
  { name: 'Rosas', hex: '#DF5D8C', family: 'rosas', step: 500, textOn: '#101010' },
  { name: 'Old Rose', hex: '#C34576', family: 'rosas', step: 600, textOn: '#FFFFFF' },
  { name: 'Rosewood', hex: '#A3325F', family: 'rosas', step: 700, textOn: '#FFFFFF' },
  { name: 'Wine Rose', hex: '#812449', family: 'rosas', step: 800, textOn: '#FFFFFF' },
  { name: 'Claret', hex: '#5E1834', family: 'rosas', step: 900, textOn: '#FFFFFF' },
  { name: 'Rose Noir', hex: '#3E0D21', family: 'rosas', step: 950, textOn: '#FFFFFF' },
  // Gumamela · Hibiscus (15°)
  { name: 'Hibiscus Mist', hex: '#FFF8F8', family: 'gumamela', step: 25, textOn: '#101010' },
  { name: 'Hibiscus Veil', hex: '#FFEFF0', family: 'gumamela', step: 50, textOn: '#101010' },
  { name: 'Rose Quartz', hex: '#FFDFE0', family: 'gumamela', step: 100, textOn: '#101010' },
  { name: 'Watermelon', hex: '#FEC3C7', family: 'gumamela', step: 200, textOn: '#101010' },
  { name: 'Poppy Blush', hex: '#FEA2A9', family: 'gumamela', step: 300, textOn: '#101010' },
  { name: 'Chili Rose', hex: '#F67E8A', family: 'gumamela', step: 400, textOn: '#101010' },
  { name: 'Gumamela', hex: '#E45D6F', family: 'gumamela', step: 500, textOn: '#101010' },
  { name: 'Carmine', hex: '#C84559', family: 'gumamela', step: 600, textOn: '#FFFFFF' },
  { name: 'Ruby', hex: '#A73246', family: 'gumamela', step: 700, textOn: '#FFFFFF' },
  { name: 'Garnet', hex: '#842334', family: 'gumamela', step: 800, textOn: '#FFFFFF' },
  { name: 'Oxblood', hex: '#611825', family: 'gumamela', step: 900, textOn: '#FFFFFF' },
  { name: 'Black Cherry', hex: '#3F0D16', family: 'gumamela', step: 950, textOn: '#FFFFFF' },
  // Santan · Ixora (30°)
  { name: 'Ember Mist', hex: '#FFF8F7', family: 'santan', step: 25, textOn: '#101010' },
  { name: 'Seashell', hex: '#FFF0ED', family: 'santan', step: 50, textOn: '#101010' },
  { name: 'Peach Blush', hex: '#FFE0DA', family: 'santan', step: 100, textOn: '#101010' },
  { name: 'Salmon', hex: '#FEC5BB', family: 'santan', step: 200, textOn: '#101010' },
  { name: 'Coral Pink', hex: '#FEA596', family: 'santan', step: 300, textOn: '#101010' },
  { name: 'Flame Coral', hex: '#F7816F', family: 'santan', step: 400, textOn: '#101010' },
  { name: 'Santan', hex: '#E5614F', family: 'santan', step: 500, textOn: '#101010' },
  { name: 'Scarlet', hex: '#C94939', family: 'santan', step: 600, textOn: '#FFFFFF' },
  { name: 'Brick', hex: '#A83528', family: 'santan', step: 700, textOn: '#FFFFFF' },
  { name: 'Barn Red', hex: '#85261B', family: 'santan', step: 800, textOn: '#FFFFFF' },
  { name: 'Maroon', hex: '#611A12', family: 'santan', step: 900, textOn: '#FFFFFF' },
  { name: 'Ember Noir', hex: '#400F09', family: 'santan', step: 950, textOn: '#FFFFFF' },
  // Caballero · Fire Tree (45°)
  { name: 'Firelight', hex: '#FFF9F6', family: 'caballero', step: 25, textOn: '#101010' },
  { name: 'Apricot Cream', hex: '#FFF0EA', family: 'caballero', step: 50, textOn: '#101010' },
  { name: 'Apricot', hex: '#FFE1D4', family: 'caballero', step: 100, textOn: '#101010' },
  { name: 'Cantaloupe', hex: '#FEC7AE', family: 'caballero', step: 200, textOn: '#101010' },
  { name: 'Papaya', hex: '#FEA780', family: 'caballero', step: 300, textOn: '#101010' },
  { name: 'Persimmon', hex: '#F38754', family: 'caballero', step: 400, textOn: '#101010' },
  { name: 'Caballero', hex: '#E16827', family: 'caballero', step: 500, textOn: '#101010' },
  { name: 'Vermilion', hex: '#C45206', family: 'caballero', step: 600, textOn: '#FFFFFF' },
  { name: 'Rust', hex: '#A04104', family: 'caballero', step: 700, textOn: '#FFFFFF' },
  { name: 'Burnt Sienna', hex: '#7D3102', family: 'caballero', step: 800, textOn: '#FFFFFF' },
  { name: 'Mahogany', hex: '#5C2201', family: 'caballero', step: 900, textOn: '#FFFFFF' },
  { name: 'Rust Noir', hex: '#3D1400', family: 'caballero', step: 950, textOn: '#FFFFFF' },
  // Palayok · Terracotta (60°)
  { name: 'Clay Mist', hex: '#FFF9F4', family: 'palayok', step: 25, textOn: '#101010' },
  { name: 'Buff', hex: '#FFF1E6', family: 'palayok', step: 50, textOn: '#101010' },
  { name: 'Peach Sand', hex: '#FEE2CC', family: 'palayok', step: 100, textOn: '#101010' },
  { name: 'Melon', hex: '#F8CBA7', family: 'palayok', step: 200, textOn: '#101010' },
  { name: 'Adobe', hex: '#EFB17D', family: 'palayok', step: 300, textOn: '#101010' },
  { name: 'Terracotta', hex: '#E19451', family: 'palayok', step: 400, textOn: '#101010' },
  { name: 'Palayok', hex: '#CE7922', family: 'palayok', step: 500, textOn: '#101010' },
  { name: 'Burnt Orange', hex: '#B16306', family: 'palayok', step: 600, textOn: '#FFFFFF' },
  { name: 'Copper Clay', hex: '#915004', family: 'palayok', step: 700, textOn: '#FFFFFF' },
  { name: 'Cinnamon', hex: '#713D02', family: 'palayok', step: 800, textOn: '#FFFFFF' },
  { name: 'Umber', hex: '#532B01', family: 'palayok', step: 900, textOn: '#FFFFFF' },
  { name: 'Burnt Umber', hex: '#361A00', family: 'palayok', step: 950, textOn: '#FFFFFF' },
  // Mangga · Mango (75°)
  { name: 'Mango Mist', hex: '#FFF9F2', family: 'mangga', step: 25, textOn: '#101010' },
  { name: 'Sunrise Cream', hex: '#FCF2E4', family: 'mangga', step: 50, textOn: '#101010' },
  { name: 'Golden Peach', hex: '#F7E5CC', family: 'mangga', step: 100, textOn: '#101010' },
  { name: 'Marigold', hex: '#EED0A7', family: 'mangga', step: 200, textOn: '#101010' },
  { name: 'Mango', hex: '#E2B87E', family: 'mangga', step: 300, textOn: '#101010' },
  { name: 'Tangerine', hex: '#D19E52', family: 'mangga', step: 400, textOn: '#101010' },
  { name: 'Mangga', hex: '#BD8422', family: 'mangga', step: 500, textOn: '#101010' },
  { name: 'Amber', hex: '#A16C02', family: 'mangga', step: 600, textOn: '#FFFFFF' },
  { name: 'Caramel', hex: '#855904', family: 'mangga', step: 700, textOn: '#FFFFFF' },
  { name: 'Toffee', hex: '#674402', family: 'mangga', step: 800, textOn: '#FFFFFF' },
  { name: 'Molasses', hex: '#4B3001', family: 'mangga', step: 900, textOn: '#FFFFFF' },
  { name: 'Cacao Brown', hex: '#311E00', family: 'mangga', step: 950, textOn: '#FFFFFF' },
  // Araw · Sun (90°)
  { name: 'Dawnlight', hex: '#FDFAF1', family: 'araw', step: 25, textOn: '#101010' },
  { name: 'Champagne', hex: '#F9F3E4', family: 'araw', step: 50, textOn: '#101010' },
  { name: 'Buttercream', hex: '#F1E7CD', family: 'araw', step: 100, textOn: '#101010' },
  { name: 'Wheat', hex: '#E5D4A7', family: 'araw', step: 200, textOn: '#101010' },
  { name: 'Honey', hex: '#D5BE7E', family: 'araw', step: 300, textOn: '#101010' },
  { name: 'Golden Hour', hex: '#C3A552', family: 'araw', step: 400, textOn: '#101010' },
  { name: 'Araw', hex: '#AE8C22', family: 'araw', step: 500, textOn: '#101010' },
  { name: 'Old Gold', hex: '#95780A', family: 'araw', step: 600, textOn: '#101010' },
  { name: 'Antique Gold', hex: '#795F04', family: 'araw', step: 700, textOn: '#FFFFFF' },
  { name: 'Dark Amber', hex: '#5E4902', family: 'araw', step: 800, textOn: '#FFFFFF' },
  { name: 'Bronzed Earth', hex: '#443401', family: 'araw', step: 900, textOn: '#FFFFFF' },
  { name: 'Ember Gold', hex: '#2C2100', family: 'araw', step: 950, textOn: '#FFFFFF' },
  // Narra · Narra Bloom (105°)
  { name: 'Lemon Mist', hex: '#FBFBF1', family: 'narra', step: 25, textOn: '#101010' },
  { name: 'Vanilla', hex: '#F5F5E4', family: 'narra', step: 50, textOn: '#101010' },
  { name: 'Custard', hex: '#EBEACD', family: 'narra', step: 100, textOn: '#101010' },
  { name: 'Butter', hex: '#DBD8A7', family: 'narra', step: 200, textOn: '#101010' },
  { name: 'Maize', hex: '#C8C37E', family: 'narra', step: 300, textOn: '#101010' },
  { name: 'Sunflower', hex: '#B3AC52', family: 'narra', step: 400, textOn: '#101010' },
  { name: 'Narra', hex: '#9D9423', family: 'narra', step: 500, textOn: '#101010' },
  { name: 'Mustard', hex: '#867E08', family: 'narra', step: 600, textOn: '#101010' },
  { name: 'Ochre', hex: '#6C6504', family: 'narra', step: 700, textOn: '#FFFFFF' },
  { name: 'Olive Gold', hex: '#534E02', family: 'narra', step: 800, textOn: '#FFFFFF' },
  { name: 'Bronze Olive', hex: '#3C3801', family: 'narra', step: 900, textOn: '#FFFFFF' },
  { name: 'Dark Ochre', hex: '#262300', family: 'narra', step: 950, textOn: '#FFFFFF' },
  // Kalamansi · Citron (120°)
  { name: 'Citron Mist', hex: '#F9FCF1', family: 'kalamansi', step: 25, textOn: '#101010' },
  { name: 'Lemon Cream', hex: '#F1F6E4', family: 'kalamansi', step: 50, textOn: '#101010' },
  { name: 'Pale Citron', hex: '#E4EDCD', family: 'kalamansi', step: 100, textOn: '#101010' },
  { name: 'Citron', hex: '#CEDCA8', family: 'kalamansi', step: 200, textOn: '#101010' },
  { name: 'Lemongrass', hex: '#B7CA7F', family: 'kalamansi', step: 300, textOn: '#101010' },
  { name: 'Zest', hex: '#9EB453', family: 'kalamansi', step: 400, textOn: '#101010' },
  { name: 'Kalamansi', hex: '#869D23', family: 'kalamansi', step: 500, textOn: '#101010' },
  { name: 'Olive Citron', hex: '#708407', family: 'kalamansi', step: 600, textOn: '#101010' },
  { name: 'Dark Citron', hex: '#5B6C04', family: 'kalamansi', step: 700, textOn: '#FFFFFF' },
  { name: 'Olive Drab', hex: '#465302', family: 'kalamansi', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Olive', hex: '#313C01', family: 'kalamansi', step: 900, textOn: '#FFFFFF' },
  { name: 'Olive Noir', hex: '#1F2600', family: 'kalamansi', step: 950, textOn: '#FFFFFF' },
  // Ilang-Ilang · Ylang-Ylang (135°)
  { name: 'Blossom Mist', hex: '#F5FDF2', family: 'ilangilang', step: 25, textOn: '#101010' },
  { name: 'Pistachio Cream', hex: '#EBF8E5', family: 'ilangilang', step: 50, textOn: '#101010' },
  { name: 'Honeydew', hex: '#DAF0CE', family: 'ilangilang', step: 100, textOn: '#101010' },
  { name: 'Pistachio', hex: '#BDE2AA', family: 'ilangilang', step: 200, textOn: '#101010' },
  { name: 'Lime', hex: '#9FD183', family: 'ilangilang', step: 300, textOn: '#101010' },
  { name: 'Young Bamboo', hex: '#7EBD58', family: 'ilangilang', step: 400, textOn: '#101010' },
  { name: 'Ilang-Ilang', hex: '#60A62D', family: 'ilangilang', step: 500, textOn: '#101010' },
  { name: 'Avocado', hex: '#4A8E07', family: 'ilangilang', step: 600, textOn: '#101010' },
  { name: 'Moss', hex: '#3B7304', family: 'ilangilang', step: 700, textOn: '#FFFFFF' },
  { name: 'Cypress', hex: '#2C5902', family: 'ilangilang', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Cypress', hex: '#1E4001', family: 'ilangilang', step: 900, textOn: '#FFFFFF' },
  { name: 'Moss Noir', hex: '#112900', family: 'ilangilang', step: 950, textOn: '#FFFFFF' },
  // Dahon · Leaf (150°)
  { name: 'Leaf Mist', hex: '#F3FEF4', family: 'dahon', step: 25, textOn: '#101010' },
  { name: 'Green Tea', hex: '#E7F9EA', family: 'dahon', step: 50, textOn: '#101010' },
  { name: 'Celadon', hex: '#D1F2D7', family: 'dahon', step: 100, textOn: '#101010' },
  { name: 'Sage', hex: '#AEE5B8', family: 'dahon', step: 200, textOn: '#101010' },
  { name: 'Fern', hex: '#87D598', family: 'dahon', step: 300, textOn: '#101010' },
  { name: 'Leaf Green', hex: '#5AC275', family: 'dahon', step: 400, textOn: '#101010' },
  { name: 'Dahon', hex: '#28AC56', family: 'dahon', step: 500, textOn: '#101010' },
  { name: 'Verdant', hex: '#099243', family: 'dahon', step: 600, textOn: '#101010' },
  { name: 'Pine', hex: '#057735', family: 'dahon', step: 700, textOn: '#FFFFFF' },
  { name: 'Forest', hex: '#035C28', family: 'dahon', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Forest', hex: '#01431B', family: 'dahon', step: 900, textOn: '#FFFFFF' },
  { name: 'Forest Noir', hex: '#002B0F', family: 'dahon', step: 950, textOn: '#FFFFFF' },
  // Pandan · Pandan (165°)
  { name: 'Pandan Mist', hex: '#F3FDF8', family: 'pandan', step: 25, textOn: '#101010' },
  { name: 'Dew Green', hex: '#E7F8F0', family: 'pandan', step: 50, textOn: '#101010' },
  { name: 'Sea Glass', hex: '#D1F0E2', family: 'pandan', step: 100, textOn: '#101010' },
  { name: 'Willow', hex: '#AEE3CB', family: 'pandan', step: 200, textOn: '#101010' },
  { name: 'Eucalyptus', hex: '#87D2B1', family: 'pandan', step: 300, textOn: '#101010' },
  { name: 'Pandan Leaf', hex: '#5BBF97', family: 'pandan', step: 400, textOn: '#101010' },
  { name: 'Pandan', hex: '#28A97D', family: 'pandan', step: 500, textOn: '#101010' },
  { name: 'Rainforest', hex: '#098F68', family: 'pandan', step: 600, textOn: '#101010' },
  { name: 'Hunter Green', hex: '#057554', family: 'pandan', step: 700, textOn: '#FFFFFF' },
  { name: 'Evergreen', hex: '#035A40', family: 'pandan', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Evergreen', hex: '#01412D', family: 'pandan', step: 900, textOn: '#FFFFFF' },
  { name: 'Evergreen Noir', hex: '#002A1C', family: 'pandan', step: 950, textOn: '#FFFFFF' },
  // Bakawan · Mangrove (180°)
  { name: 'Jade Mist', hex: '#F3FDFA', family: 'bakawan', step: 25, textOn: '#101010' },
  { name: 'Mint Cream', hex: '#E7F8F4', family: 'bakawan', step: 50, textOn: '#101010' },
  { name: 'Mint', hex: '#D1F0E9', family: 'bakawan', step: 100, textOn: '#101010' },
  { name: 'Seafoam', hex: '#AEE1D6', family: 'bakawan', step: 200, textOn: '#101010' },
  { name: 'Jade', hex: '#87D0C1', family: 'bakawan', step: 300, textOn: '#101010' },
  { name: 'Verdigris', hex: '#5BBCAB', family: 'bakawan', step: 400, textOn: '#101010' },
  { name: 'Bakawan', hex: '#28A693', family: 'bakawan', step: 500, textOn: '#101010' },
  { name: 'Deep Jade', hex: '#098D7C', family: 'bakawan', step: 600, textOn: '#101010' },
  { name: 'Pine Teal', hex: '#057365', family: 'bakawan', step: 700, textOn: '#FFFFFF' },
  { name: 'Mangrove', hex: '#03594D', family: 'bakawan', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Mangrove', hex: '#014038', family: 'bakawan', step: 900, textOn: '#FFFFFF' },
  { name: 'Mangrove Noir', hex: '#002923', family: 'bakawan', step: 950, textOn: '#FFFFFF' },
  // Dagat · Sea (195°)
  { name: 'Teal Mist', hex: '#F3FCFC', family: 'dagat', step: 25, textOn: '#101010' },
  { name: 'Ice Teal', hex: '#E7F7F7', family: 'dagat', step: 50, textOn: '#101010' },
  { name: 'Pale Teal', hex: '#D1EFEE', family: 'dagat', step: 100, textOn: '#101010' },
  { name: 'Aquamarine', hex: '#AEE0DF', family: 'dagat', step: 200, textOn: '#101010' },
  { name: 'Lagoon', hex: '#87CFCE', family: 'dagat', step: 300, textOn: '#101010' },
  { name: 'Teal', hex: '#5ABABA', family: 'dagat', step: 400, textOn: '#101010' },
  { name: 'Dagat', hex: '#28A4A4', family: 'dagat', step: 500, textOn: '#101010' },
  { name: 'Deep Teal', hex: '#098B8B', family: 'dagat', step: 600, textOn: '#101010' },
  { name: 'Peacock', hex: '#057171', family: 'dagat', step: 700, textOn: '#FFFFFF' },
  { name: 'Deep Peacock', hex: '#035858', family: 'dagat', step: 800, textOn: '#FFFFFF' },
  { name: 'Abyss Teal', hex: '#013F3F', family: 'dagat', step: 900, textOn: '#FFFFFF' },
  { name: 'Teal Noir', hex: '#002828', family: 'dagat', step: 950, textOn: '#FFFFFF' },
  // Alon · Wave (210°)
  { name: 'Aqua Mist', hex: '#F3FCFE', family: 'alon', step: 25, textOn: '#101010' },
  { name: 'Glacier', hex: '#E7F7FA', family: 'alon', step: 50, textOn: '#101010' },
  { name: 'Pale Aqua', hex: '#D1EEF3', family: 'alon', step: 100, textOn: '#101010' },
  { name: 'Aqua', hex: '#AEDFE8', family: 'alon', step: 200, textOn: '#101010' },
  { name: 'Turquoise', hex: '#86CDDA', family: 'alon', step: 300, textOn: '#101010' },
  { name: 'Cyan Wave', hex: '#5AB8C8', family: 'alon', step: 400, textOn: '#101010' },
  { name: 'Alon', hex: '#28A2B4', family: 'alon', step: 500, textOn: '#101010' },
  { name: 'Deep Aqua', hex: '#08899A', family: 'alon', step: 600, textOn: '#101010' },
  { name: 'Deep Cyan', hex: '#056F7D', family: 'alon', step: 700, textOn: '#FFFFFF' },
  { name: 'Marine', hex: '#035661', family: 'alon', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Marine', hex: '#013E47', family: 'alon', step: 900, textOn: '#FFFFFF' },
  { name: 'Marine Noir', hex: '#00282D', family: 'alon', step: 950, textOn: '#FFFFFF' },
  // Langit · Sky (225°)
  { name: 'Sky Mist', hex: '#F4FCFF', family: 'langit', step: 25, textOn: '#101010' },
  { name: 'Powder Blue', hex: '#E6F7FD', family: 'langit', step: 50, textOn: '#101010' },
  { name: 'Baby Blue', hex: '#D1EDF9', family: 'langit', step: 100, textOn: '#101010' },
  { name: 'Sky', hex: '#ADDEF1', family: 'langit', step: 200, textOn: '#101010' },
  { name: 'Cerulean', hex: '#85CBE7', family: 'langit', step: 300, textOn: '#101010' },
  { name: 'Azure', hex: '#59B6D8', family: 'langit', step: 400, textOn: '#101010' },
  { name: 'Langit', hex: '#279FC5', family: 'langit', step: 500, textOn: '#101010' },
  { name: 'Deep Sky', hex: '#0886A9', family: 'langit', step: 600, textOn: '#101010' },
  { name: 'Denim', hex: '#056D8A', family: 'langit', step: 700, textOn: '#FFFFFF' },
  { name: 'Prussian', hex: '#03546C', family: 'langit', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Prussian', hex: '#013D4E', family: 'langit', step: 900, textOn: '#FFFFFF' },
  { name: 'Prussian Noir', hex: '#002733', family: 'langit', step: 950, textOn: '#FFFFFF' },
  // Bughaw · Blue (240°)
  { name: 'Blue Mist', hex: '#F6FBFF', family: 'bughaw', step: 25, textOn: '#101010' },
  { name: 'Frost Blue', hex: '#E9F5FF', family: 'bughaw', step: 50, textOn: '#101010' },
  { name: 'Cloud Blue', hex: '#D3ECFF', family: 'bughaw', step: 100, textOn: '#101010' },
  { name: 'Cornflower', hex: '#ACDCFE', family: 'bughaw', step: 200, textOn: '#101010' },
  { name: 'Bluebell', hex: '#84C8F8', family: 'bughaw', step: 300, textOn: '#101010' },
  { name: 'Sapphire Light', hex: '#58B2ED', family: 'bughaw', step: 400, textOn: '#101010' },
  { name: 'Bughaw', hex: '#269ADC', family: 'bughaw', step: 500, textOn: '#101010' },
  { name: 'Sapphire', hex: '#0983BF', family: 'bughaw', step: 600, textOn: '#101010' },
  { name: 'Royal Blue', hex: '#05699C', family: 'bughaw', step: 700, textOn: '#FFFFFF' },
  { name: 'Navy', hex: '#03517A', family: 'bughaw', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Navy', hex: '#013A59', family: 'bughaw', step: 900, textOn: '#FFFFFF' },
  { name: 'Navy Noir', hex: '#00253B', family: 'bughaw', step: 950, textOn: '#FFFFFF' },
  // Karagatan · Ocean (255°)
  { name: 'Ocean Mist', hex: '#F7FAFF', family: 'karagatan', step: 25, textOn: '#101010' },
  { name: 'Sea Frost', hex: '#ECF4FF', family: 'karagatan', step: 50, textOn: '#101010' },
  { name: 'Pale Cobalt', hex: '#D9EAFF', family: 'karagatan', step: 100, textOn: '#101010' },
  { name: 'Chambray', hex: '#BAD8FE', family: 'karagatan', step: 200, textOn: '#101010' },
  { name: 'Cobalt', hex: '#95C3FE', family: 'karagatan', step: 300, textOn: '#101010' },
  { name: 'Ultramarine', hex: '#69ABFE', family: 'karagatan', step: 400, textOn: '#101010' },
  { name: 'Karagatan', hex: '#3F91F4', family: 'karagatan', step: 500, textOn: '#101010' },
  { name: 'Deep Cobalt', hex: '#287BDD', family: 'karagatan', step: 600, textOn: '#101010' },
  { name: 'Admiral', hex: '#1361B7', family: 'karagatan', step: 700, textOn: '#FFFFFF' },
  { name: 'Midnight Blue', hex: '#084B91', family: 'karagatan', step: 800, textOn: '#FFFFFF' },
  { name: 'Abyss', hex: '#05356A', family: 'karagatan', step: 900, textOn: '#FFFFFF' },
  { name: 'Abyss Noir', hex: '#032146', family: 'karagatan', step: 950, textOn: '#FFFFFF' },
  // Gabi · Night (270°)
  { name: 'Indigo Mist', hex: '#F8FAFF', family: 'gabi', step: 25, textOn: '#101010' },
  { name: 'Moon Blue', hex: '#EFF3FF', family: 'gabi', step: 50, textOn: '#101010' },
  { name: 'Periwinkle', hex: '#DFE7FF', family: 'gabi', step: 100, textOn: '#101010' },
  { name: 'Lavender Blue', hex: '#C5D4FE', family: 'gabi', step: 200, textOn: '#101010' },
  { name: 'Iris', hex: '#A7BDFE', family: 'gabi', step: 300, textOn: '#101010' },
  { name: 'Blue Iris', hex: '#87A3FE', family: 'gabi', step: 400, textOn: '#101010' },
  { name: 'Gabi', hex: '#6A87F6', family: 'gabi', step: 500, textOn: '#101010' },
  { name: 'Indigo', hex: '#546FDA', family: 'gabi', step: 600, textOn: '#FFFFFF' },
  { name: 'Deep Indigo', hex: '#4259B8', family: 'gabi', step: 700, textOn: '#FFFFFF' },
  { name: 'Midnight Indigo', hex: '#314492', family: 'gabi', step: 800, textOn: '#FFFFFF' },
  { name: 'Ink', hex: '#22306B', family: 'gabi', step: 900, textOn: '#FFFFFF' },
  { name: 'Ink Noir', hex: '#141E47', family: 'gabi', step: 950, textOn: '#FFFFFF' },
  // Takipsilim · Dusk (285°)
  { name: 'Dusk Mist', hex: '#F9F9FF', family: 'takipsilim', step: 25, textOn: '#101010' },
  { name: 'Lilac Haze', hex: '#F2F2FF', family: 'takipsilim', step: 50, textOn: '#101010' },
  { name: 'Lavender', hex: '#E5E5FF', family: 'takipsilim', step: 100, textOn: '#101010' },
  { name: 'Wisteria', hex: '#D0D0FE', family: 'takipsilim', step: 200, textOn: '#101010' },
  { name: 'Amethyst', hex: '#B8B7FE', family: 'takipsilim', step: 300, textOn: '#101010' },
  { name: 'Dusk Violet', hex: '#A09AFE', family: 'takipsilim', step: 400, textOn: '#101010' },
  { name: 'Takipsilim', hex: '#887EF2', family: 'takipsilim', step: 500, textOn: '#101010' },
  { name: 'Deep Violet', hex: '#7366D6', family: 'takipsilim', step: 600, textOn: '#FFFFFF' },
  { name: 'Twilight', hex: '#5D50B4', family: 'takipsilim', step: 700, textOn: '#FFFFFF' },
  { name: 'Deep Twilight', hex: '#473D8F', family: 'takipsilim', step: 800, textOn: '#FFFFFF' },
  { name: 'Nightfall', hex: '#332B69', family: 'takipsilim', step: 900, textOn: '#FFFFFF' },
  { name: 'Nightfall Noir', hex: '#201A45', family: 'takipsilim', step: 950, textOn: '#FFFFFF' },
  // Ube · Purple Yam (300°)
  { name: 'Ube Mist', hex: '#FBF9FF', family: 'ube', step: 25, textOn: '#101010' },
  { name: 'Ube Cream', hex: '#F5F1FF', family: 'ube', step: 50, textOn: '#101010' },
  { name: 'Taro', hex: '#EBE3FF', family: 'ube', step: 100, textOn: '#101010' },
  { name: 'Lilac', hex: '#DCCBFE', family: 'ube', step: 200, textOn: '#101010' },
  { name: 'Violet Bloom', hex: '#CBAFFE', family: 'ube', step: 300, textOn: '#101010' },
  { name: 'Halaya', hex: '#B791F7', family: 'ube', step: 400, textOn: '#101010' },
  { name: 'Ube', hex: '#A274E7', family: 'ube', step: 500, textOn: '#101010' },
  { name: 'Royal Purple', hex: '#8A5DCC', family: 'ube', step: 600, textOn: '#FFFFFF' },
  { name: 'Grape', hex: '#7148AB', family: 'ube', step: 700, textOn: '#FFFFFF' },
  { name: 'Plum', hex: '#583687', family: 'ube', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Plum', hex: '#3F2663', family: 'ube', step: 900, textOn: '#FFFFFF' },
  { name: 'Plum Noir', hex: '#281741', family: 'ube', step: 950, textOn: '#FFFFFF' },
  // Waling-Waling · Orchid (315°)
  { name: 'Orchid Mist', hex: '#FDF8FF', family: 'walingwaling', step: 25, textOn: '#101010' },
  { name: 'Petal Lilac', hex: '#FAEFFF', family: 'walingwaling', step: 50, textOn: '#101010' },
  { name: 'Pale Orchid', hex: '#F4DFFF', family: 'walingwaling', step: 100, textOn: '#101010' },
  { name: 'Orchid', hex: '#EAC5FB', family: 'walingwaling', step: 200, textOn: '#101010' },
  { name: 'Mauve', hex: '#DCA8F4', family: 'walingwaling', step: 300, textOn: '#101010' },
  { name: 'Heather', hex: '#CB8AE8', family: 'walingwaling', step: 400, textOn: '#101010' },
  { name: 'Waling-Waling', hex: '#B66CD6', family: 'walingwaling', step: 500, textOn: '#101010' },
  { name: 'Deep Amethyst', hex: '#9E55BC', family: 'walingwaling', step: 600, textOn: '#FFFFFF' },
  { name: 'Mulberry', hex: '#82419D', family: 'walingwaling', step: 700, textOn: '#FFFFFF' },
  { name: 'Aubergine', hex: '#66307C', family: 'walingwaling', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Aubergine', hex: '#4A225A', family: 'walingwaling', step: 900, textOn: '#FFFFFF' },
  { name: 'Aubergine Noir', hex: '#30143B', family: 'walingwaling', step: 950, textOn: '#FFFFFF' },
  // Bugambilya · Bougainvillea (330°)
  { name: 'Magenta Mist', hex: '#FFF7FE', family: 'bugambilya', step: 25, textOn: '#101010' },
  { name: 'Sugar Pink', hex: '#FFEDFC', family: 'bugambilya', step: 50, textOn: '#101010' },
  { name: 'Bubblegum', hex: '#FCDCF8', family: 'bugambilya', step: 100, textOn: '#101010' },
  { name: 'Rose Fuchsia', hex: '#F5C1EF', family: 'bugambilya', step: 200, textOn: '#101010' },
  { name: 'Fuchsia', hex: '#EBA4E4', family: 'bugambilya', step: 300, textOn: '#101010' },
  { name: 'Magenta', hex: '#DC84D4', family: 'bugambilya', step: 400, textOn: '#101010' },
  { name: 'Bugambilya', hex: '#C865C1', family: 'bugambilya', step: 500, textOn: '#101010' },
  { name: 'Deep Magenta', hex: '#AE4EA8', family: 'bugambilya', step: 600, textOn: '#FFFFFF' },
  { name: 'Raspberry', hex: '#903B8B', family: 'bugambilya', step: 700, textOn: '#FFFFFF' },
  { name: 'Boysenberry', hex: '#712B6D', family: 'bugambilya', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Boysenberry', hex: '#521E4F', family: 'bugambilya', step: 900, textOn: '#FFFFFF' },
  { name: 'Berry Noir', hex: '#361133', family: 'bugambilya', step: 950, textOn: '#FFFFFF' },
  // Kalachuchi · Plumeria (345°)
  { name: 'Blush Mist', hex: '#FFF8FB', family: 'kalachuchi', step: 25, textOn: '#101010' },
  { name: 'Ballet Pink', hex: '#FFEEF7', family: 'kalachuchi', step: 50, textOn: '#101010' },
  { name: 'Blush', hex: '#FFDDEF', family: 'kalachuchi', step: 100, textOn: '#101010' },
  { name: 'Petal Pink', hex: '#FEBFE2', family: 'kalachuchi', step: 200, textOn: '#101010' },
  { name: 'Peony', hex: '#F6A0D1', family: 'kalachuchi', step: 300, textOn: '#101010' },
  { name: 'Flamingo', hex: '#E87FBD', family: 'kalachuchi', step: 400, textOn: '#101010' },
  { name: 'Kalachuchi', hex: '#D560A8', family: 'kalachuchi', step: 500, textOn: '#101010' },
  { name: 'Cerise', hex: '#BA4990', family: 'kalachuchi', step: 600, textOn: '#FFFFFF' },
  { name: 'Cranberry', hex: '#9B3676', family: 'kalachuchi', step: 700, textOn: '#FFFFFF' },
  { name: 'Wine', hex: '#7A265C', family: 'kalachuchi', step: 800, textOn: '#FFFFFF' },
  { name: 'Deep Wine', hex: '#591A42', family: 'kalachuchi', step: 900, textOn: '#FFFFFF' },
  { name: 'Wine Noir', hex: '#3A0F2A', family: 'kalachuchi', step: 950, textOn: '#FFFFFF' },
  // Buhangin · Sand (neutral)
  { name: 'Cotton', hex: '#FCFAF7', family: 'buhangin', step: 25, textOn: null },
  { name: 'Ivory', hex: '#F6F3EF', family: 'buhangin', step: 50, textOn: null },
  { name: 'Cream', hex: '#ECE7E0', family: 'buhangin', step: 100, textOn: null },
  { name: 'Linen', hex: '#DCD3C7', family: 'buhangin', step: 200, textOn: null },
  { name: 'Oatmeal', hex: '#CABEAD', family: 'buhangin', step: 300, textOn: null },
  { name: 'Sand', hex: '#B5A692', family: 'buhangin', step: 400, textOn: null },
  { name: 'Buhangin', hex: '#9F8E77', family: 'buhangin', step: 500, textOn: null },
  { name: 'Taupe', hex: '#877761', family: 'buhangin', step: 600, textOn: null },
  { name: 'Driftwood', hex: '#6F604D', family: 'buhangin', step: 700, textOn: null },
  { name: 'Bark', hex: '#564A3A', family: 'buhangin', step: 800, textOn: null },
  { name: 'Espresso', hex: '#3E3529', family: 'buhangin', step: 900, textOn: null },
  { name: 'Warm Charcoal', hex: '#272119', family: 'buhangin', step: 950, textOn: null },
  // Abo · Ash (neutral)
  { name: 'Whitewash', hex: '#FAFAFB', family: 'abo', step: 25, textOn: null },
  { name: 'Pearl Gray', hex: '#F3F3F4', family: 'abo', step: 50, textOn: null },
  { name: 'Fog', hex: '#E6E8EA', family: 'abo', step: 100, textOn: null },
  { name: 'Mist Gray', hex: '#D3D5D8', family: 'abo', step: 200, textOn: null },
  { name: 'Silver Gray', hex: '#BDC0C4', family: 'abo', step: 300, textOn: null },
  { name: 'Ash', hex: '#A5A9AD', family: 'abo', step: 400, textOn: null },
  { name: 'Abo', hex: '#8D9196', family: 'abo', step: 500, textOn: null },
  { name: 'Slate', hex: '#767A7F', family: 'abo', step: 600, textOn: null },
  { name: 'Graphite', hex: '#5F6367', family: 'abo', step: 700, textOn: null },
  { name: 'Charcoal', hex: '#494C50', family: 'abo', step: 800, textOn: null },
  { name: 'Onyx', hex: '#343739', family: 'abo', step: 900, textOn: null },
  { name: 'Obsidian', hex: '#212224', family: 'abo', step: 950, textOn: null },
  // Ulap · Cloud (neutral)
  { name: 'Cloud White', hex: '#F9FAFC', family: 'ulap', step: 25, textOn: null },
  { name: 'Cloud', hex: '#F1F4F6', family: 'ulap', step: 50, textOn: null },
  { name: 'Frost Gray', hex: '#E3E9ED', family: 'ulap', step: 100, textOn: null },
  { name: 'Dove', hex: '#CED6DD', family: 'ulap', step: 200, textOn: null },
  { name: 'Stone Blue', hex: '#B6C1CA', family: 'ulap', step: 300, textOn: null },
  { name: 'Bluestone', hex: '#9CABB6', family: 'ulap', step: 400, textOn: null },
  { name: 'Ulap', hex: '#83939F', family: 'ulap', step: 500, textOn: null },
  { name: 'Storm', hex: '#6C7C88', family: 'ulap', step: 600, textOn: null },
  { name: 'Gunmetal', hex: '#57656F', family: 'ulap', step: 700, textOn: null },
  { name: 'Deep Storm', hex: '#424E56', family: 'ulap', step: 800, textOn: null },
  { name: 'Midnight Gray', hex: '#2F383E', family: 'ulap', step: 900, textOn: null },
  { name: 'Storm Noir', hex: '#1D2327', family: 'ulap', step: 950, textOn: null },
  // Lupa · Earth (neutral)
  { name: 'Bone', hex: '#FDF9F6', family: 'lupa', step: 25, textOn: null },
  { name: 'Parchment', hex: '#F8F2ED', family: 'lupa', step: 50, textOn: null },
  { name: 'Almond', hex: '#F0E6DC', family: 'lupa', step: 100, textOn: null },
  { name: 'Khaki', hex: '#E3D1C2', family: 'lupa', step: 200, textOn: null },
  { name: 'Camel', hex: '#D3BBA5', family: 'lupa', step: 300, textOn: null },
  { name: 'Clay', hex: '#BFA287', family: 'lupa', step: 400, textOn: null },
  { name: 'Lupa', hex: '#AA8A6B', family: 'lupa', step: 500, textOn: null },
  { name: 'Chestnut', hex: '#927356', family: 'lupa', step: 600, textOn: null },
  { name: 'Walnut', hex: '#785D42', family: 'lupa', step: 700, textOn: null },
  { name: 'Coffee', hex: '#5D4731', family: 'lupa', step: 800, textOn: null },
  { name: 'Cacao', hex: '#433322', family: 'lupa', step: 900, textOn: null },
  { name: 'Earth Noir', hex: '#2B1F14', family: 'lupa', step: 950, textOn: null },
];

// ── the 13 metallics ─────────────────────────────────────────────────────
//
// 🛑 DELIBERATELY NOT IN THE NAMING TABLE. A metallic is a FINISH — polished,
// brushed, satin, matte, iridescent — and a finish is not a property a hex can
// carry. Nothing in a hex distinguishes polished Ginto from a flat yellow paint
// at the same coordinates, so a nearest-match namer that could answer "Ginto"
// would be promising a couple a metal it cannot see. The source says this of
// itself: Perlas is "bridal detail, not a field color".
//
// They stay here as DATA because a palette builder legitimately needs them —
// "which metal goes with this palette" is a real question and these hexes are
// the honest answer to it. Reach for them by slug, never by proximity.
export const SETNAYAN_METALLICS: readonly SetnayanMetallic[] = [
  {
    slug: 'ginto',
    filipino: 'Ginto',
    english: 'Gold',
    hex: '#D4AF37',
    finish: 'polished',
    note: 'Primary metallic. Pairs with araw-300 for invitations.',
  },
  {
    slug: 'gintongantigo',
    filipino: 'Gintong Antigo',
    english: 'Antique Gold',
    hex: '#B08D3F',
    finish: 'brushed',
    note: 'Aged gold for heritage and church weddings.',
  },
  {
    slug: 'champagneginto',
    filipino: 'Champagne Ginto',
    english: 'Champagne Gold',
    hex: '#D6C09A',
    finish: 'satin',
    note: 'The safest metallic for pale palettes.',
  },
  {
    slug: 'rosasginto',
    filipino: 'Rosas Ginto',
    english: 'Rose Gold',
    hex: '#B76E79',
    finish: 'polished',
    note: 'Reads pink at a distance — test against blush swatches.',
  },
  {
    slug: 'tanso',
    filipino: 'Tanso',
    english: 'Copper',
    hex: '#B87333',
    finish: 'polished',
    note: 'Industrial-romantic; strong with terracotta and greenery.',
  },
  {
    slug: 'bronse',
    filipino: 'Bronse',
    english: 'Bronze',
    hex: '#8C7853',
    finish: 'brushed',
    note: 'Muted metallic for earthy and garden palettes.',
  },
  {
    slug: 'tumbaga',
    filipino: 'Tumbaga',
    english: 'Brass',
    hex: '#B5A642',
    finish: 'brushed',
    note: 'Pre-colonial gold-copper alloy; heritage accent.',
  },
  {
    slug: 'pilak',
    filipino: 'Pilak',
    english: 'Silver',
    hex: '#C0C0C0',
    finish: 'polished',
    note: 'Cool-metal anchor for winter and black-tie.',
  },
  {
    slug: 'platino',
    filipino: 'Platino',
    english: 'Platinum',
    hex: '#E5E4E2',
    finish: 'satin',
    note: 'Near-white metallic; keeps pale palettes from going flat.',
  },
  {
    slug: 'peltre',
    filipino: 'Peltre',
    english: 'Pewter',
    hex: '#8E9294',
    finish: 'matte',
    note: 'Matte cool grey metal for modern minimal.',
  },
  {
    slug: 'bakal',
    filipino: 'Bakal',
    english: 'Gunmetal',
    hex: '#2C3539',
    finish: 'matte',
    note: 'Darkest metallic; hardware and signage.',
  },
  {
    slug: 'perlas',
    filipino: 'Perlas',
    english: 'Pearl',
    hex: '#F0E9DD',
    finish: 'iridescent',
    note: 'Warm iridescent; bridal detail, not a field color.',
  },
  {
    slug: 'nakar',
    filipino: 'Nakar',
    english: 'Mother of Pearl',
    hex: '#DCE6E4',
    finish: 'iridescent',
    note: 'Cool iridescent shell; capiz-window reference.',
  },
];

// ── the 12 curated palettes ────────────────────────────────────────────────
//
// Ready-made theme starters, each 6 swatches drawn from the tables above. These
// belong to the MOOD BOARD / theme layer, not to naming — a palette is an
// authored recommendation, and the naming module answers a different question
// (what is this one colour called). Every member hex is a swatch in
// SETNAYAN_SWATCHES, so a starter can never introduce an unnamed colour.
export const SETNAYAN_PALETTES: readonly SetnayanPalette[] = [
  {
    slug: 'takipsilimginto',
    filipino: 'Takipsilim Ginto',
    english: 'Dusk & Gold',
    description: "Setnayan's house palette. Warm dark canvas, gold light, coral accent.",
    season: 'year-round',
    formality: 'formal',
    members: [
      { hex: '#201A45', name: 'Nightfall Noir' },
      { hex: '#473D8F', name: 'Deep Twilight' },
      { hex: '#AE8C22', name: 'Araw' },
      { hex: '#E5D4A7', name: 'Wheat' },
      { hex: '#F7816F', name: 'Flame Coral' },
      { hex: '#F6F3EF', name: 'Ivory' },
    ],
  },
  {
    slug: 'hardinsaumaga',
    filipino: 'Hardin sa Umaga',
    english: 'Morning Garden',
    description: 'Garden ceremony before the heat — sage, cream, soft coral.',
    season: 'dry season',
    formality: 'semi-formal',
    members: [
      { hex: '#AEE5B8', name: 'Sage' },
      { hex: '#28AC56', name: 'Dahon' },
      { hex: '#ECE7E0', name: 'Cream' },
      { hex: '#FEBFE2', name: 'Petal Pink' },
      { hex: '#D5BE7E', name: 'Honey' },
      { hex: '#927356', name: 'Chestnut' },
    ],
  },
  {
    slug: 'dagatatbuhangin',
    filipino: 'Dagat at Buhangin',
    english: 'Sea & Sand',
    description: 'Beach wedding without the cliché — deep teal grounding pale sand.',
    season: 'summer',
    formality: 'casual',
    members: [
      { hex: '#057171', name: 'Peacock' },
      { hex: '#5ABABA', name: 'Teal' },
      { hex: '#AEDFE8', name: 'Aqua' },
      { hex: '#F6F3EF', name: 'Ivory' },
      { hex: '#CABEAD', name: 'Oatmeal' },
      { hex: '#C3A552', name: 'Golden Hour' },
    ],
  },
  {
    slug: 'pistangbayan',
    filipino: 'Pistang Bayan',
    english: 'Town Fiesta',
    description: 'Full fiesta saturation, controlled by one deep neutral.',
    season: 'year-round',
    formality: 'casual',
    members: [
      { hex: '#C865C1', name: 'Bugambilya' },
      { hex: '#BD8422', name: 'Mangga' },
      { hex: '#28A4A4', name: 'Dagat' },
      { hex: '#B3AC52', name: 'Sunflower' },
      { hex: '#8A5DCC', name: 'Royal Purple' },
      { hex: '#343739', name: 'Onyx' },
    ],
  },
  {
    slug: 'simbahan',
    filipino: 'Simbahan',
    english: 'Old Church',
    description: 'Stone, candlelight, and aged gold — for heritage church ceremonies.',
    season: 'year-round',
    formality: 'formal',
    members: [
      { hex: '#F0E6DC', name: 'Almond' },
      { hex: '#BFA287', name: 'Clay' },
      { hex: '#BDC0C4', name: 'Silver Gray' },
      { hex: '#795F04', name: 'Antique Gold' },
      { hex: '#812449', name: 'Wine Rose' },
      { hex: '#564A3A', name: 'Bark' },
    ],
  },
  {
    slug: 'bulaklakblush',
    filipino: 'Bulaklak Blush',
    english: 'Blush Bloom',
    description: 'The classic bridal palette, with enough depth to photograph well.',
    season: 'year-round',
    formality: 'formal',
    members: [
      { hex: '#FFDDEF', name: 'Blush' },
      { hex: '#F6A0D1', name: 'Peony' },
      { hex: '#F27DA4', name: 'Antique Rose' },
      { hex: '#F6F3EF', name: 'Ivory' },
      { hex: '#87D598', name: 'Fern' },
      { hex: '#812449', name: 'Wine Rose' },
    ],
  },
  {
    slug: 'gabiatlamig',
    filipino: 'Gabi at Lamig',
    english: 'Cold Night',
    description: 'Black-tie reception. Navy field, silver metal, one ice accent.',
    season: 'cool months',
    formality: 'black-tie',
    members: [
      { hex: '#05356A', name: 'Abyss' },
      { hex: '#05699C', name: 'Royal Blue' },
      { hex: '#CED6DD', name: 'Dove' },
      { hex: '#83939F', name: 'Ulap' },
      { hex: '#212224', name: 'Obsidian' },
      { hex: '#D1EDF9', name: 'Baby Blue' },
    ],
  },
  {
    slug: 'lupaatluntian',
    filipino: 'Lupa at Luntian',
    english: 'Earth & Green',
    description: 'Terracotta and foliage — the modern rustic standard.',
    season: 'year-round',
    formality: 'semi-formal',
    members: [
      { hex: '#CE7922', name: 'Palayok' },
      { hex: '#EFB17D', name: 'Adobe' },
      { hex: '#3B7304', name: 'Moss' },
      { hex: '#099243', name: 'Verdant' },
      { hex: '#E3D1C2', name: 'Khaki' },
      { hex: '#ECE7E0', name: 'Cream' },
    ],
  },
  {
    slug: 'ubeatperlas',
    filipino: 'Ube at Perlas',
    english: 'Ube & Pearl',
    description: 'Filipino dessert palette — purple, cream, and a pearl finish.',
    season: 'year-round',
    formality: 'semi-formal',
    members: [
      { hex: '#8A5DCC', name: 'Royal Purple' },
      { hex: '#CBAFFE', name: 'Violet Bloom' },
      { hex: '#EBE3FF', name: 'Taro' },
      { hex: '#F6F3EF', name: 'Ivory' },
      { hex: '#66307C', name: 'Aubergine' },
      { hex: '#E5D4A7', name: 'Wheat' },
    ],
  },
  {
    slug: 'takipsilimsadagat',
    filipino: 'Takipsilim sa Dagat',
    english: 'Dusk at Sea',
    description: 'Sunset reception by water — violet dusk against teal water.',
    season: 'summer',
    formality: 'semi-formal',
    members: [
      { hex: '#473D8F', name: 'Deep Twilight' },
      { hex: '#546FDA', name: 'Indigo' },
      { hex: '#28A4A4', name: 'Dagat' },
      { hex: '#F38754', name: 'Persimmon' },
      { hex: '#D5BE7E', name: 'Honey' },
      { hex: '#E3E9ED', name: 'Frost Gray' },
    ],
  },
  {
    slug: 'putiatluntian',
    filipino: 'Puti at Luntian',
    english: 'White & Green',
    description: 'Minimal: white, greenery, one warm neutral. Hard to get wrong.',
    season: 'year-round',
    formality: 'formal',
    members: [
      { hex: '#FAFAFB', name: 'Whitewash' },
      { hex: '#F6F3EF', name: 'Ivory' },
      { hex: '#87D2B1', name: 'Eucalyptus' },
      { hex: '#098F68', name: 'Rainforest' },
      { hex: '#035C28', name: 'Forest' },
      { hex: '#A5A9AD', name: 'Ash' },
    ],
  },
  {
    slug: 'ginintuanganihan',
    filipino: 'Ginintuang Anihan',
    english: 'Golden Harvest',
    description: 'Harvest palette — narra yellow, mango, and deep olive.',
    season: 'harvest / late year',
    formality: 'casual',
    members: [
      { hex: '#B3AC52', name: 'Sunflower' },
      { hex: '#BD8422', name: 'Mangga' },
      { hex: '#465302', name: 'Olive Drab' },
      { hex: '#AA8A6B', name: 'Lupa' },
      { hex: '#DCD3C7', name: 'Linen' },
      { hex: '#915004', name: 'Copper Clay' },
    ],
  },
];

// ── brand anchors ────────────────────────────────────────────────────────
export const SETNAYAN_ANCHORS: readonly SetnayanAnchor[] = [
  { token: 'arawGold', name: 'Golden Hour', ref: 'araw-400', hex: '#C3A552' },
  { token: 'arawGoldDeep', name: 'Araw', ref: 'araw-500', hex: '#AE8C22' },
  { token: 'rosasCoral', name: 'Flame Coral', ref: 'santan-400', hex: '#F7816F' },
  { token: 'verifiedTeal', name: 'Dagat', ref: 'dagat-500', hex: '#28A4A4' },
  { token: 'takipsilimSurface', name: 'Nightfall Noir', ref: 'takipsilim-950', hex: '#201A45' },
  { token: 'takipsilimWarmInk', name: 'Earth Noir', ref: 'lupa-950', hex: '#2B1F14' },
  { token: 'canvasLight', name: 'Ivory', ref: 'buhangin-50', hex: '#F6F3EF' },
];

// ── the naming table ─────────────────────────────────────────────────────
//
// Every swatch is a nameable entry: 336 `{ name, hex }` pairs, structurally the
// same shape as `NamedColor` in ./color-names. This is what replaces the
// hand-curated `WEDDING_NAMES` table; `CSS_NAMES` stays the never-fails floor
// underneath it, unchanged.
//
// ⚠ METALLICS ARE NOT IN HERE, ON PURPOSE — see SETNAYAN_METALLICS above.
export const SETNAYAN_NAMES: readonly { name: string; hex: string }[] = SETNAYAN_SWATCHES.map(
  ({ name, hex }) => ({ name, hex }),
);
