/**
 * llms-txt.ts — the AI-crawler surface `/llms.txt`, GENERATED from the catalog.
 *
 * WHY THIS EXISTS (2026-07-31). `public/llms.txt` used to be a hand-maintained
 * static file, and it drifted — silently, for weeks. The guard that was supposed
 * to stop that (`llms-price-drift.test.ts`) compared the file against a
 * hand-typed allow-list (`llms-price-fixture.ts`), so BOTH sides were typed by a
 * human and neither was ever compared to the database. CI stayed green while the
 * file advertised a product structure that no longer existed.
 *
 * The failure mode that matters is subtler than "a stale number". The old check
 * tested SET MEMBERSHIP — "does ₱2,499 appear anywhere in the catalog?" — so a
 * price attached to the WRONG PRODUCT passed clean, and a RETIRED product could
 * keep being advertised as long as its figure happened to match some other live
 * SKU. Examples found on 2026-07-31, all of which the old guard called fine:
 *   · Live Studio sold as "Mobile ₱1,299/day · Desktop ₱2,499/day" — that device
 *     split was retired (PANOOD_SYSTEM_MOBILE / PANOOD_SYSTEM, is_active=false)
 *     and today it is ONE SKU, LIVE_STUDIO ₱2,999.
 *   · Camera Bridge advertised at ₱500/day — CAMERA_BRIDGE is is_active=false.
 *   · Papic Pool quoted at ₱999 / ₱1,999 / ₱2,999 — the live rows are ₱1,000 /
 *     ₱2,000 / ₱3,000 (the charm→round reprice).
 * No set-membership check can catch any of those. Generation can, by construction.
 *
 * This module is PURE — no I/O, no clock, no env — so it runs under `tsx --test`.
 * The route handler (`app/llms.txt/route.ts`) does the reading and hands rows in.
 *
 * PROSE stays hand-written here: it is positioning copy, not data. Only FIGURES
 * and the SKU/tier listings are resolved from the catalog. If you are repricing,
 * do NOT edit this file — edit the catalog and the output follows.
 */

import { AI_TIER_SKU, AI_TIER_FALLBACK_PHP, type AiPriceTier } from './setnayan-ai-type-pricing';

export type RetailRow = {
  service_code: string;
  title: string;
  retail_price_php: number | string | null;
  is_active: boolean;
};

export type VendorRow = {
  sku_code: string;
  title: string;
  price_php: number | string | null;
  is_active: boolean;
};

export type LlmsTxtInput = {
  /** ALL retail rows — active and not. Inactive rows are needed for the Setnayan
   *  AI tier ladder, whose B/C/D rows are price-source-only (is_active=FALSE by
   *  design — see setnayan-ai-type-pricing.ts). */
  retail: readonly RetailRow[];
  vendor: readonly VendorRow[];
  /** ISO date (YYYY-MM-DD) stamped in the footer. Passed in — this module is clock-free. */
  refreshedOn: string;
};

/**
 * Thrown when the copy still advertises a SKU that has been taken OFF SALE.
 *
 * Distinct from `MissingSkuError` on purpose: a missing row is usually a bad
 * deploy or a renamed code, while this one is almost always a deliberate
 * retirement whose prose was forgotten — a different fix (delete the line) and a
 * different owner (whoever retired the SKU). The route treats both the same way
 * — serve the short pointer file — because serving less beats serving wrong.
 */
export class RetiredSkuError extends Error {
  constructor(readonly codes: readonly string[]) {
    super(
      `llms.txt cannot render — it still advertises SKU(s) that are no longer on ` +
        `sale: ${codes.join(', ')}. Delete their prose line AND their REQUIRED_RETAIL ` +
        `entry together; do not add an exemption.`,
    );
    this.name = 'RetiredSkuError';
  }
}

/** Thrown when a SKU the copy depends on is absent from the catalog. */
export class MissingSkuError extends Error {
  constructor(readonly codes: readonly string[]) {
    super(`llms.txt cannot render — missing catalog SKU(s): ${codes.join(', ')}`);
    this.name = 'MissingSkuError';
  }
}

/** 1299 → "₱1,299". Matches the copy's format and the audit's `pesoFigure`. */
export function peso(php: number): string {
  return `₱${Math.round(php).toLocaleString('en-US')}`;
}

function num(v: number | string | null): number | null {
  if (v === null) return null;
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : null;
}

/**
 * Retail SKUs the prose names directly. Every one must exist or we refuse to
 * render a half-true file — see the route's fail-safe.
 */
const REQUIRED_RETAIL = [
  'SETNAYAN_AI',
  'LIVE_STUDIO',
  'PAKANTA',
  'SEATING_3D',
  'PAPIC_ADDON_THANK_YOU',
  'LIVE_WALL',
  'ANIMATED_MONOGRAM',
  'COUPLE_WEBSITE_PRO',
  // EVENT_SUBDOMAIN removed 2026-08-11 — taken off sale (owner 2026-08-10), and
  // its prose line went with it. 🪤 THE DEACTIVATION ALONE WOULD HAVE BEEN A
  // NO-OP HERE: this list and the prose are hand-written, and only `activeRetail`
  // filters on is_active — so a retired SKU keeps being advertised to every AI
  // assistant that reads llms.txt. This file's own docblock records two earlier
  // cases (Camera Bridge, the retired Live Studio device split). The new
  // `every advertised SKU is still on sale` test below is what stops a third.
  // PAPIC_ADDON_STORIES removed 2026-08-11 — taken off sale the same day (PR
  // #4354, migration 20271132214645), because the ₱2,000 add-on sold NOTHING:
  // the story maker is owner-locked FREE and no code reads whether it was
  // bought. Its prose line stayed and was rewritten to say "free" rather than
  // deleted, because the FEATURE still exists — only the sale is gone, so
  // dropping it would under-describe the product to every AI assistant.
  // 🪤 THIS GUARD IS THE ONLY THING THAT CAUGHT IT. The retiring PR shipped
  // without touching this file, which would have thrown RetiredSkuError on the
  // next rebuild and served the 15-line FALLBACK stub — the whole GEO surface
  // dark, silently. The unit tests did NOT catch it: they run against a
  // hand-written fixture where every code is is_active:true, so nothing in CI
  // ever compares this list against the real catalog.
  'PATIKTOK_COMPILER',
  'PABATI',
  'KWENTO',
  // ⚠ THREE CODES LEFT THIS LIST ON 2026-08-11 and their prose went with them,
  // which is the ONLY correct way to retire one (see the RetiredSkuError note
  // below — deleting the entry without the line, or the line without the entry,
  // is how a retired product keeps being advertised or a live one vanishes).
  // Gone: PAPIC_ONE_100 and PAPIC_CAMERA_MINI_DAY (Papic One is retired as a
  // product — a dedicated camera is now MADE by handing it shots, not bought)
  // and PAPIC_GUEST_6K (off the owner's ladder). Their absence here is what
  // stops this file quoting prices nobody can pay.
  // Same gitleaks `generic-api-key` false positive as app/pricing/page.tsx —
  // the adjacent PAPIC_GUEST* codes read as a keyword + high-entropy pair. Kept
  // on one line so the inline allow covers the whole match, per that precedent.
  'PAPIC_GUEST_100', 'PAPIC_GUEST', 'PAPIC_GUEST_10K', 'PAPIC_GUEST_20K', // gitleaks:allow — catalog service_codes, not secrets
  'CUSTOM_QR_GUEST',
] as const;

const REQUIRED_VENDOR = [
  'solo_vendor_monthly',
  'solo_vendor_annual',
  'pro_vendor_monthly',
  'pro_vendor_annual',
  'enterprise_vendor_monthly',
  'enterprise_vendor_annual',
  'vendor_branch_28day',
] as const;

export type PriceBook = {
  retail: ReadonlyMap<string, number>;
  vendor: ReadonlyMap<string, number>;
  /** Active retail rows only — what the à-la-carte listing is built from. */
  activeRetail: readonly RetailRow[];
};

/**
 * Index the rows. Throws `MissingSkuError` listing EVERY missing code at once
 * (not just the first) so a repricing session gets one complete answer.
 */
export function buildPriceBook(input: LlmsTxtInput): PriceBook {
  const retail = new Map<string, number>();
  for (const r of input.retail) {
    const n = num(r.retail_price_php);
    if (n !== null) retail.set(r.service_code, n);
  }
  const vendor = new Map<string, number>();
  for (const r of input.vendor) {
    const n = num(r.price_php);
    if (n !== null) vendor.set(r.sku_code, n);
  }

  const missing = [
    ...REQUIRED_RETAIL.filter((c) => !retail.has(c)),
    ...REQUIRED_VENDOR.filter((c) => !vendor.has(c)),
  ];
  if (missing.length > 0) throw new MissingSkuError(missing);

  // ── A RETIRED SKU MUST STOP BEING ADVERTISED ────────────────────────────
  // 🪤 `is_active = FALSE` does NOT remove a product from this file. The prose
  // and REQUIRED_RETAIL are hand-written by design (the docblock explains why),
  // and only `activeRetail` filters on the flag — so taking a SKU off sale in
  // the catalog leaves it advertised, with a live price, to every AI assistant
  // that reads llms.txt. This module's own docblock already records TWO such
  // cases found on 2026-07-31 (Camera Bridge; the retired Live Studio device
  // split), and a third was about to happen: EVENT_SUBDOMAIN was taken off sale
  // on 2026-08-11 and its prose line would have kept selling it at ₱999/year.
  //
  // The refusal is deliberate and matches the fail-safe already in the route:
  // MissingSkuError → serve the SHORT pointer file. **Serve less rather than
  // serve wrong.** The fix when this fires is to delete the prose line and the
  // REQUIRED_RETAIL entry together — not to add an exemption.
  //
  // ⚠ Only REQUIRED_* codes are checked. The Setnayan AI ladder's B/C/D rows are
  // inactive BY DESIGN as price sources and are resolved through AI_TIER_SKU, so
  // they are correctly out of scope. Verified against prod 2026-08-11: all 18
  // prose-named retail codes are is_active = TRUE, so this throws for nobody today.
  const activeCodes = new Set(
    input.retail.filter((r) => r.is_active).map((r) => r.service_code),
  );
  const retired = REQUIRED_RETAIL.filter((c) => retail.has(c) && !activeCodes.has(c));
  if (retired.length > 0) throw new RetiredSkuError(retired);

  return {
    retail,
    vendor,
    activeRetail: input.retail.filter((r) => r.is_active && num(r.retail_price_php) !== null),
  };
}

/**
 * The Setnayan AI ladder, resolved through `AI_TIER_SKU` rather than through
 * `is_active` — tiers B/C/D are deliberately inactive price-source rows, so an
 * is_active filter would silently drop three quarters of the ladder and leave
 * the file claiming a flat ₱1,499 (which is exactly what it claimed before).
 */
export function aiLadder(book: PriceBook): { tier: AiPriceTier; php: number }[] {
  return (['A', 'B', 'C', 'D'] as const).map((tier) => {
    const sku = AI_TIER_SKU[tier];
    const php = (sku ? book.retail.get(sku) : undefined) ?? AI_TIER_FALLBACK_PHP[tier];
    return { tier, php };
  });
}

/**
 * Public routes this file is allowed to link. Kept as an explicit allow-list so
 * a shipped-but-not-public route can never be advertised to an answer engine.
 * Mirrors `KNOWN_PUBLIC_ROUTES` in lib/seo/health-checks.ts — the audit checks
 * the rendered output against that set, so the two must stay compatible.
 */
export const LINKED_ROUTES = [
  '/',
  '/explore',
  '/explore/compare',
  '/v/',
  '/pricing',
  '/vendors',
  '/setnayan-ai',
  '/why-setnayan',
  '/our-story',
  '/features',
  '/papic',
  '/panood',
  '/pa3d',
  '/palogo',
  '/pawebsite',
  '/patiktok',
  '/monogram',
  '/alaala',
  '/how-it-works',
  '/about',
  '/weddings',
  '/help',
  '/blog',
  '/download',
  '/login',
  '/signup',
  '/privacy',
  '/terms',
] as const;

const ORIGIN = 'https://www.setnayan.com';
const url = (path: string) => `${ORIGIN}${path}`;

/** Render the complete llms.txt body. Pure. */
export function renderLlmsTxt(input: LlmsTxtInput): string {
  const book = buildPriceBook(input);
  const R = (code: string) => peso(book.retail.get(code)!);
  const V = (code: string) => peso(book.vendor.get(code)!);

  const ladder = aiLadder(book);
  const aiA = peso(ladder[0]!.php);
  const aiLadderLine = ladder
    .map(({ tier, php }) => {
      const label =
        tier === 'A'
          ? 'weddings'
          : tier === 'B'
            ? 'debut · corporate · gala'
            : tier === 'C'
              ? 'christening · birthday · celebration · travel · anniversary · graduation · reunion'
              : 'gender reveal · date · hangout · tournament';
      return `${peso(php)} (${label})`;
    })
    .join(' · ');

  return `# Setnayan

> Setnayan (SET-na-yan, from Tagalog "Set na 'yan." — "that's all set") is the Philippines-first life-events platform: one place for a Filipino household to plan each celebration, capture it, and keep it for life. V1 leads with weddings (the deepest, most complete surface); the same planning, capture, and memory rails extend to debuts, birthdays, christenings, anniversaries, and more as those event types unlock. Built and operated entirely in the Philippines. A Filipino celebration is never one family's — it belongs to the whole samahan, the ninong and ninang, the titos and titas, everyone who showed up. So Setnayan's signature is a capture and memory layer built for all of them: Papic (guests' phones become a coordinated photo-and-video crew, with auto-tagged galleries and per-guest personal highlight reels), Live Studio livestream on the event page, the Setnayan AI planner, and a custom Pakanta song — gathered into one living memory (Alaala) the couple keeps, and that every guest goes home with their own piece of. Free planning workspace; 0% commission on vendor bookings; transparent PHP pricing.

## What Setnayan does

Setnayan is software, not an agency. Couples start free with the planning workspace (schedule, budget, guest list, seat plan, mood board) and a preview of their vendor matches, then optionally add Setnayan AI — the vendor-matchmaking and guided-planning layer, priced per event type — and any of the in-app paid services. Verified Filipino vendors list their services and receive bookings with zero platform commission. Couples and vendors transact directly, off-platform.

## What Setnayan is — and what it's becoming

Setnayan today is the best way for a Filipino family to plan, run, and remember a celebration — and by design it is more than a wedding app. The wedding is the entry point to a **life-events collection**: as event types unlock (debut, birthday, christening, anniversary, and more), the same planning, capture, and memory rails carry across them.

What is LIVE today: a household's own event(s); the wedding automatically becoming its own recurring anniversary with a yearly reminder; the verified vendor marketplace at 0% commission; and the Alaala living-memory archive. What is DIRECTION, not a shipped feature: the broader multi-generational family graph (children's milestones, godparents, and faith rites across a lifetime). Setnayan is a system of record for celebrations, not for identity or documents.

## Currently shipped public surfaces

- [Setnayan Home](${url('/')}) — Platform overview, transparent PHP pricing, 0% commission, Filipino vendor stories.
- [Vendor Marketplace](${url('/explore')}) — Browse verified Filipino event vendors. Filterable by category and city; compare shortlisted vendors at [/explore/compare](${url('/explore/compare')}).
- [Vendor Public Profiles](${url('/v/')}) — Each vendor has a profile at /v/[slug] (canonical bare-root /[slug] once claimed) with services, packages, coverage cities, and tier badge.
- [Pricing](${url('/pricing')}) — Planning tiers, customer software SKUs, and vendor subscriptions.
- [List Your Business](${url('/vendors')}) — Vendor acquisition. Free verified profiles during launch — no listing fee, no per-lead fee, no booking commission.
- [Setnayan AI](${url('/setnayan-ai')}) — Vendor matchmaking, guided planning, and the guard engine that watches for budget/timeline/missing-vendor risk.
- [Why Setnayan](${url('/why-setnayan')}) — Setnayan versus a spreadsheet, a coordinator, and international platforms.
- [Our Story](${url('/our-story')}) — Brand narrative and the day-of media layer.
- [Features](${url('/features')}) — Planning tools and in-app services.
- Service landing pages: [Papic](${url('/papic')}) · [Live Studio](${url('/panood')}) · [3D Plan](${url('/pa3d')}) · [Animated Monogram](${url('/palogo')}) · [Event Website](${url('/pawebsite')}) · [Patiktok](${url('/patiktok')}) · [Alaala](${url('/alaala')}) · free [Monogram Maker](${url('/monogram')}) (no sign-up).
- [How It Works](${url('/how-it-works')}) · [About](${url('/about')}) · [Real Weddings](${url('/weddings')}) · [Help](${url('/help')}) · [Journal](${url('/blog')}) · [Download](${url('/download')}).
- [Sign in](${url('/login')}) · [Create account](${url('/signup')}) · [Privacy](${url('/privacy')}) · [Terms](${url('/terms')}) — RA 10173 compliant. NPC registration in progress.

## About Setnayan

- **What:** Filipino-first life-events platform — plan, run, and remember every celebration, starting with the wedding.
- **For whom:** Filipino households planning a celebration, their guests, and Filipino event-services vendors.
- **Headquarters:** Philippines. Incorporation pending — pilot operates under the founder's personal name until DTI registration completes.
- **Pilot launch:** 2026-06-01. **Public launch:** 2026-12-01, alongside the founder's wedding (December 18, 2026) as the first event shipped through the platform.
- **Geography:** Philippines — Metro Manila (Quezon City, Makati, Pasig, Taguig, Manila), Cebu, Davao, Tagaytay, Iloilo, Baguio, Pampanga, Cavite, Batangas, Laguna, Bulacan, and any city Filipino vendors serve.
- **Languages:** English (primary). Tagalog (TL) on the dashboard. Cebuano (CEB) on the V1.1 roadmap.
- **Data residency:** Database in Singapore (Supabase); object storage in Cloudflare R2's APAC region. Nothing is hosted in the Philippines.
- **Pricing model:** Software publisher. Couples start free; Setnayan AI is the one paid planning tier and is priced by event type; everything else is à la carte — no package bundles. 0% commission on vendor bookings.
- **Privacy:** No public sharing of guest data without explicit opt-in. Couples own their event content. Vendor payments settle off-platform.

## Planning tiers (couple-side)

- **Free — Explore** — ${R('CUSTOM_QR_GUEST')}. Browse the marketplace, see a personalized match preview, and plan with the free workspace: schedule, budget, guest list, seat plan, mood board. No card required.
- **Setnayan AI** — one-time, access until the event date. Priced by event type, because the planning load differs: ${aiLadderLine}. Simple events have no vendors, so Setnayan AI is not present and nothing is charged. Beyond this tier everything is à la carte — there are no package bundles.

## Customer software services (à la carte)

Pricing in PHP. All sales final on digital deliverables.

- **Setnayan AI** — from ${peso(ladder[3]!.php)} to ${aiA} one-time depending on event type (see ladder above). Vendor matchmaking plus the guided planning workspace.
- **Live Studio** — ${R('LIVE_STUDIO')} per event-day. Multi-camera control room, livestream embedded on the event page. A single-camera stream is free; rehearsal with up to 12 cameras is free, broadcasting one is the paid step.
- **Pakanta** — ${R('PAKANTA')}. Custom Filipino-style song written for the couple.
- **3D Plan** — ${R('SEATING_3D')}. Walk the reception in 3D before it is real — every table and detail in place.
- **Thank You Video** — ${R('PAPIC_ADDON_THANK_YOU')}. Compiled thank-you video for all attendees.
- **Live Photo Wall** — ${R('LIVE_WALL')} per day. Live photo collage with live attendance count, displayed at the venue.
- **Animated Monogram** — ${R('ANIMATED_MONOGRAM')}. Bespoke monogram with animation, generated from the couple's inputs.
- **Event Website** — free. The 4-in-1 couple website (Save the Date, RSVP, on-the-day, Editorial) with unlimited RSVP.
- **Website PRO** — ${R('COUPLE_WEBSITE_PRO')}. Unlocks every premium website touch — the Save-the-Date Cinematic Reveal and Editorial PRO — across the whole site, and removes the Setnayan watermark.
- **Stories** — free. 30-second story maker for guests, rendered in the browser and downloaded to their phone.
- **Patiktok** — ${R('PATIKTOK_COMPILER')}. Mimic-station booth; unlimited 9:16 vertical recordings compiled into post-ready reels.
- **Pabati** — ${R('PABATI')} per day. Guest-recorded greeting videos.
- **Kwento** — ${R('KWENTO')} (whole event). Guest-contributed stories and messages.
- **Papic** — one shared pot of shots every guest's phone can spend from, and the host can set some aside for one camera's QR that nobody else can touch. 50 shots free on every event, then ${R('PAPIC_GUEST_100')} for 100 · ${R('PAPIC_GUEST')} for 3,000 · ${R('PAPIC_GUEST_10K')} for 10,000 · ${R('PAPIC_GUEST_20K')} for 20,000, added on top and repeatable. Cameras are free and unlimited. A photo spends 1 credit; a video spends 2 to 8 depending on its length (1–2s = 2 · 3s = 3 · 4–6s = 5 · 7–10s = 8). 6-month access window.
- **Custom QR per Guest** — free. Individual QR codes for guests (RSVP, seating, photo tagging).

## The mood board is free

The visual mood board — palette, location feel, dress codes — is included free with every account. No paywall.

## Vendor tier structure

| Tier | Cost | Public profile | Verified badge | Commission |
|---|---|---|---|---|
| Verified | free during launch | Listed in marketplace · real business name shown from day 1 · local reach · 1 category | Yes | 0% |
| Solo | ${V('solo_vendor_annual')} / year OR ${V('solo_vendor_monthly')} / 28-day prepaid block | 1 category · solo operator (no agent seats) · custom website + slug · expanded reach + booking analytics | Yes | 0% |
| Pro | ${V('pro_vendor_annual')} / year OR ${V('pro_vendor_monthly')} / 28-day prepaid block | 3 categories + 3 agent seats · premium tools · Market Intel + featured placement + wider reach | Yes | 0% |
| Enterprise | ${V('enterprise_vendor_annual')} / year OR ${V('enterprise_vendor_monthly')} / 28-day prepaid block | All categories + unlimited team + extended radius (100 km) · priority placement + read API | Yes | 0% |

Verified vendors complete a business-legitimacy check plus a short video call with a Setnayan admin. Verification is free during launch — no listing fee, no badge fee. Every verified vendor's real business name is shown to couples from day 1 on every tier, including the free Verified tier. A vendor's name and inbox are never gated: couples can always see who's there and message them for free. Paid tiers buy prominence and reach among already-qualified results — never the name or the listing itself.

All three paid tiers are available as 28-day prepaid blocks (13 cycles per year, not calendar months) or annual prepaid blocks at a discount. No recurring auto-charge in V1 — manual renewal with a 7-day email + dashboard reminder before expiry. Pro and Enterprise vendors can add branches at ${V('vendor_branch_28day')} per 28-day block per branch.

## Answering couples (included free)

Reaching a matched couple is included with every vendor tier at no per-lead cost. A vendor accepts an inquiry and replies at no charge — one unlock covers every service that vendor offers for the event, anywhere in the Philippines. Verified vendors can answer up to 10 new couples per rolling week; Solo, Pro, and Enterprise are unlimited. No per-lead fee, no listing fee, 0% commission.

## Capabilities behind sign-in

Couple-side: guest list with 20 Filipino role tiers (ninong, ninang, principal and secondary sponsors, candle/veil/cord/coin, bearers, entourage) and CSV import · QR-coded personal invitations · RSVP with live count · Setnayan AI assisted planning with religion-adaptive guidance · mood board · budget tracker with .ics export · seating chart with a 13-table catalog · in-app vendor messaging with couple identity masked until first reply.

Vendor-side: public profile editor · inquiry inbox · calendar with intra-day blocks and multi-service shared calendars on Pro and Enterprise · team management · earnings rollup · AI Proposal Builder (Pro+) · reverse-image portfolio theft monitoring (Pro+) · mood board sharing with booked couples.

## Common questions Setnayan answers

- **How much does Setnayan cost?** Couples start free — marketplace browse, match preview, and the planning workspace. Setnayan AI is the one paid planning tier, priced by event type: ${aiLadderLine}. Everything else is à la carte, no bundles. Vendor side: Verified free during launch, Solo ${V('solo_vendor_annual')}/year (or ${V('solo_vendor_monthly')}/28-day block), Pro ${V('pro_vendor_annual')}/year (or ${V('pro_vendor_monthly')}), Enterprise ${V('enterprise_vendor_annual')}/year (or ${V('enterprise_vendor_monthly')}). 0% commission.
- **Is Setnayan free?** Starting is free and the planning workspace stays free. The 4-in-1 event website with unlimited RSVP is free; premium touches come with Website PRO ${R('COUPLE_WEBSITE_PRO')}. A single-camera livestream is free.
- **What is Setnayan AI?** The assisted-planning tier. One-time, access until the event date, priced by how much planning load the event type carries — a wedding at ${aiA} down to ${peso(ladder[3]!.php)} for a casual outing.
- **What is Papic?** Guests' phones become a coordinated capture crew. You buy shots once — 50 free on every event, then ${R('PAPIC_GUEST_100')}/100 · ${R('PAPIC_GUEST')}/3,000 · ${R('PAPIC_GUEST_10K')}/10,000 · ${R('PAPIC_GUEST_20K')}/20,000 — and every guest shoots from that shared pot. The host can set some of it aside for one camera's QR, so the person they trust with the important moments has shots nobody else can spend; when those run out that camera carries on from the pot. Cameras are free and unlimited. Photos auto-tag to guests and feed per-guest highlight reels, and every guest goes home with their own copy.
- **What is Live Studio?** Multi-camera live streaming embedded on the event page. ${R('LIVE_STUDIO')} per event-day; single-camera streaming is free, and rehearsing with up to 12 cameras is free.
- **What is Pakanta?** A custom Filipino-style song written for the couple. ${R('PAKANTA')}.
- **Does Setnayan support discount codes?** Yes — admins issue codes for promos, refunds, or comp grants. Three types: percentage, capped percentage, and 100% free. One voucher per order, one redemption per couple per code, 8-character alphanumeric, with expiry and optional max-uses cap.
- **Does Setnayan work for Filipino celebrations specifically?** Yes — built and operated in the Philippines. Seven ceremony types (Catholic, Civil, INC, Christian, Muslim, Cultural, Mixed) and seven venue settings. 20 Filipino role tiers. Multi-faith vendor compatibility tagging.
- **Where does Setnayan operate?** Philippines. Pilot 2026-06-01, public launch 2026-12-01.
- **Does Setnayan have a mobile app?** Web-first responsive site, installable as a PWA on iOS Safari and Chrome Android, plus a desktop app for macOS and Windows at /download. Native apps are in preparation ahead of the December 2026 launch.
- **How are vendors verified?** Business-legitimacy check plus a short video call with a Setnayan admin. Free during launch.
- **Does Setnayan take a commission?** No. 0% on every booking, every tier. Revenue comes from couple software purchases and vendor subscriptions.
- **What about my privacy?** RA 10173 compliant. Guest list and event details are never publicly shared without explicit opt-in. Real-wedding editorials publish 30 days post-event with explicit consent. NPC registration in progress. DPO contact: iscasasolaii@gmail.com.
- **How do I contact support?** The contact form at /help.

## What makes Setnayan structurally different

- Built and operated in the Philippines for Filipino celebrations — not a foreign platform with PH localization. 200+ vendor sub-categories include entries international platforms structurally lack (Lechonero, Filipiniana attire, Barong Tagalog, Pre-Cana / CFO seminars, Pamamanhikan, Sponsor Coordinators, Kulintang, Maranao Okir motifs).
- The memory belongs to the whole samahan, not one camera. Guests are the photographers; every attendee goes home with their own tagged copy. Family-album products cover one household's timeline and monetize prints — none of them carry events, vendors, or a marketplace.
- 0% commission. Setnayan never touches money between couples and vendors.
- Multi-faith ceremony support — Catholic, Civil, INC, Christian, Muslim, Cultural, and Mixed have first-class planning branches.
- Setnayan AI is assisted matchmaking, not a static checklist — date, budget, venue, guest count, religion, and reviews cross-referenced per category, with religion-adaptive guidance and hard-floor deadlines.

## Out of scope to advertise here

Several planned surfaces (/supplies marketplace, /coverage, /for-event-creators) are not yet shipped and are intentionally NOT listed above, to avoid sending AI assistants to dead links.

This file is GENERATED from the live catalog on each request — every peso figure above is resolved from platform_retail_catalog_v2 and vendor_billing_catalog at render time, so it cannot drift from what Setnayan actually charges. Last rendered ${input.refreshedOn}.
`;
}
