// AUTO-GENERATED from the icon-menu-registry-map discovery workflow (2026-06-16).
// The canonical default NAME + ICON for every menu/route slot across Setnayan,
// all account types. This is the route-meta successor: the single in-code source
// the admin /admin/menus overrides layer on top of. Regenerate from the design doc
// `Nav_Icon_Menu_Registry_Design_2026-06-16.md` when slots change.
//
// DO hand-edit to add NEW slots / fix a default; keep keys stable (overrides key off them).

import type { NavSlotDefault } from './nav-registry-types';

export const NAV_SLOT_DEFAULTS: readonly NavSlotDefault[] = [
  {
    key: "public.marketing.home",
    scope: "public",
    area: "marketing-site",
    route: "/",
    label: "Setnayan brand logo / Home",
    labelKind: "literal",
    iconKind: "custom",
    lucideName: null,
    customRef: "SetnayanMark",
    sortOrder: 0,
  },
  {
    key: "public.site-nav.explore",
    scope: "public",
    area: "marketing-site-nav",
    route: "/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.site-nav.setnayan-ai",
    scope: "public",
    area: "marketing-site-nav",
    route: "/setnayan-ai",
    label: "Setnayan AI",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.site-nav.for-vendors",
    scope: "public",
    area: "marketing-site-nav",
    route: "/vendors",
    label: "For vendors",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.site-nav.our-story",
    scope: "public",
    area: "marketing-site-nav",
    route: "/our-story",
    label: "Our story",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "public.site-nav.journal",
    scope: "public",
    area: "marketing-site-nav",
    route: "/blog",
    label: "Journal",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "public.site-nav.real-stories",
    scope: "public",
    area: "marketing-site-nav",
    route: "/realstories",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 4,
  },
  // ── Reskin glass nav (2026-07-03) — the marketing chrome now mirrors the
  // homepage's floating glass nav: Prices / Download / Vendors open overlays
  // (route = the overlay's "see full" destination), Sign in opens the auth
  // popup. The six link slots above are seeded-but-inert (retired from the
  // nav, kept so any admin overrides never orphan).
  {
    key: "public.site-nav.prices",
    scope: "public",
    area: "marketing-site-nav",
    route: "/pricing",
    label: "Prices",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "public.site-nav.download",
    scope: "public",
    area: "marketing-site-nav",
    route: "/download",
    label: "Download",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "public.site-nav.vendors-overlay",
    scope: "public",
    area: "marketing-site-nav",
    route: "/vendors",
    label: "Vendors",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "public.site-nav.sign-in",
    scope: "public",
    area: "marketing-site-nav",
    route: "/login",
    label: "Sign in",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "public.download.page",
    scope: "public",
    area: "download-page",
    route: "/download",
    label: "Mac app",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Apple",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.download.mac-api",
    scope: "public",
    area: "download-page",
    route: "/api/download/mac",
    label: "Download for Mac",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Download",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.download.qr-png",
    scope: "public",
    area: "download-page",
    route: "/api/website/qr/detail",
    label: "Download PNG",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Download",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "public.guest.find-my-table",
    scope: "public",
    area: "guest-experience",
    route: "/guests/find-my-table",
    label: "Find my table",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.guest.find-seat",
    scope: "public",
    area: "guest-experience",
    route: "/guests/find-seat",
    label: "Find your seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.papic.guest",
    scope: "public",
    area: "papic-guest-gallery",
    route: "/papic/guest",
    label: "Be a candid camera",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.account.events",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard",
    label: "My Events",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarHeart",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.account.notifications",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard/notifications",
    label: "Notifications",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.account.profile",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard/profile",
    label: "Profile & Settings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Settings",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.account.marketplace",
    scope: "customer",
    area: "customer-account",
    route: "/explore",
    label: "Marketplace",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Store",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.account.new-event",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard/create-event",
    label: "New event",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Plus",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.account.library",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard/library",
    label: "Memories Hub",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.account.people",
    scope: "customer",
    area: "customer-account",
    route: "/dashboard/people",
    label: "People",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "customer.sidebar.home",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]",
    label: "Home",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.bottom-nav.home",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]",
    label: "Home",
    labelKind: "literal",
    iconKind: "custom",
    lucideName: null,
    customRef: "SetnayanMark",
    sortOrder: 0,
  },
  {
    key: "customer.bottom-nav.guests",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/guests",
    label: "Guests",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.bottom-nav.explore",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.bottom-nav.studio",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/studio",
    label: "Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.sidebar.studio",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/studio",
    label: "Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.sidebar.explore",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.sidebar.guests",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests",
    label: "Guests",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.sidebar.guests-build",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PencilLine",
    customRef: null,
    sortOrder: 31,
  },
  {
    key: "customer.sidebar.guests-invite",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/invite",
    label: "Invite",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 32,
  },
  {
    key: "customer.sidebar.guests-confirm",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleCheck",
    customRef: null,
    sortOrder: 33,
  },
  {
    // "Seat" stage — reuses the existing seating slot key so the admin can
    // still rename / reicon it whether it's a top-level row or a child row.
    key: "customer.sidebar.seating",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/seating",
    label: "Seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 34,
  },
  {
    key: "customer.sidebar.guests-dayof",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 35,
  },
  {
    key: "customer.sidebar.schedule",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/schedule",
    label: "Schedule",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarClock",
    customRef: null,
    sortOrder: 5,
  },
  // Budget nav item REMOVED 2026-07-10 (owner): budget now lives inside the
  // Merkado (Vendors → Build · Budget · Compare), so the standalone item was
  // redundant. The full budget surface (/dashboard/[eventId]/budget) stays
  // reachable from the Merkado's Budget tab ("Open budget & payments") + direct
  // links; only the top-level nav entry is gone.
  // Day-of phase bottom-nav tabs (lifecycle phase 'dayof' in
  // lib/customer-menu.ts buildCustomerMenuTree). Same `customer.bottom-nav.*`
  // area + lookup the customer-bottom-nav chokepoint uses for the plan tabs, so
  // /admin/menus renames/re-icons reach the Day-of roster too. The 'now' anchor
  // keeps the SetnayanMark in code (custom mark, not registry-icon-overridable),
  // matching the plan-phase 'home' anchor.
  {
    key: "customer.bottom-nav.now",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]",
    label: "Now",
    labelKind: "literal",
    iconKind: "custom",
    lucideName: null,
    customRef: "SetnayanMark",
    sortOrder: 10,
  },
  {
    key: "customer.bottom-nav.checkin",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Check-in",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "customer.bottom-nav.seats",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/seating",
    label: "Seats",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "customer.bottom-nav.services",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/launch",
    label: "Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Rocket",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "customer.bottom-nav.schedule",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/schedule",
    label: "Schedule",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarClock",
    customRef: null,
    sortOrder: 14,
  },
  // After phase bottom-nav tabs (lifecycle phase 'after'). The 'home' anchor
  // reuses the existing `customer.bottom-nav.home` slot above (same key/route),
  // so only the three post-event tabs need their own slots here.
  {
    key: "customer.bottom-nav.review",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/vendors",
    label: "Review",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "customer.bottom-nav.editorial",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/website/editorial",
    label: "Editorial",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Newspaper",
    customRef: null,
    sortOrder: 16,
  },
  {
    key: "customer.bottom-nav.galleries",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/galleries",
    label: "Galleries",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Images",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "customer.sidebar.messages",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/messages",
    label: "Messages",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquare",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "customer.sidebar.contracts",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/contracts",
    label: "Contracts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 8,
  },
  {
    // "Event page" — the host's doorway to the live /[slug] page (owner
    // 2026-06-26). Sits at the top of the Studio group; admin-editable here.
    key: "customer.sidebar.event-page",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/event-page",
    label: "Event page",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Eye",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.sidebar.website",
    scope: "customer",
    area: "customer-sidebar",
    route: "/site-editor/[eventId]",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 9,
  },
  {
    // "Launch" — preview every part + go live now or on a schedule (owner
    // 2026-06-28). Sibling of Website; gated to website-enabled event types.
    key: "customer.sidebar.launch",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/website/launch",
    label: "Launch",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Rocket",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.sidebar.mood-board",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/studio/mood-board",
    label: "Mood Board",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "customer.sidebar.monogram",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/monogram",
    label: "Monogram",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Type",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "customer.sidebar.live",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/live",
    label: "Live Wall",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MonitorPlay",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "customer.sidebar.event-qr",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/event-qr",
    label: "Event QR",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "customer.sidebar.activity",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/activity",
    label: "Activity",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Activity",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "customer.sidebar.disputes",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/disputes",
    label: "Disputes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shield",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "customer.home-subnav.overview",
    scope: "customer",
    area: "home-section-subnav",
    route: "/dashboard/[eventId]",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutDashboard",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.home-subnav.checklist",
    scope: "customer",
    area: "home-section-subnav",
    route: "/dashboard/[eventId]/checklist",
    label: "Checklist",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ClipboardList",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.guest-journey.build",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PencilLine",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.guest-journey.invite",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/invite",
    label: "Invite",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.guest-journey.confirm",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleCheck",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-journey.seat",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/seating",
    label: "Seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.guest-journey.dayof",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.profile-menu.hosts",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/[eventId]/hosts",
    label: "Hosts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Heart",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.profile-menu.personalization",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/[eventId]/details",
    label: "Personalization",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.profile-menu.profile",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/profile",
    label: "Profile",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.profile-menu.settings",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/profile#settings",
    label: "Settings",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.profile-menu.sign-out",
    scope: "customer",
    area: "profile-menu",
    route: "/auth/sign-out",
    label: "Sign out",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.route.documents",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/documents",
    label: "Documents",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.route.guests-checkin",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.route.guests-claims",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Invite / Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.route.hosts",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/hosts",
    label: "nav.hosts",
    labelKind: "i18nKey",
    iconKind: "lucide",
    lucideName: "UserPlus",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.route.invitation",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/invitation",
    label: "Invitation & URL",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Pencil",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.route.manpower",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/manpower",
    label: "Manpower",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "HardHat",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.route.notifications",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/notifications",
    label: "nav.notifications",
    labelKind: "i18nKey",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "customer.route.orders",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/orders",
    label: "Orders",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "customer.route.paperwork",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/paperwork",
    label: "Paperwork / Government paperwork",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ScrollText",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "customer.route.profile",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/profile",
    label: "My account",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleUser",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.route.sponsors",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/sponsors",
    label: "Sponsors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "customer.website-editor.dress-code",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/dress-code",
    label: "Edit dress code",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shirt",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.website-editor.photo-moments",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/photo-moments",
    label: "Edit photo moments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.website-editor.privacy",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/privacy",
    label: "Who can view",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Lock",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.website-editor.site-chrome",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/site-chrome",
    label: "Edit music & video",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.website-editor.widgets",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/widgets",
    label: "Customize widgets",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 4,
  },
  // (The "customer.budget-subnav.summary" slot was removed 2026-06-25 — owner
  // "start with shortlist right away": the Services takeover's Summary cover
  // tab is gone, so its sub-nav child default went too, mirroring the 2026-06-20
  // lock-tab removal below. Shortlist is now the first (sortOrder 0) section.)
  {
    key: "customer.budget-subnav.shortlist",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=shortlist",
    label: "Shortlist",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bookmark",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.budget-subnav.build",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=build",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Hammer",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.budget-subnav.budget",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/vendors?tab=budget",
    label: "Budget",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.budget-subnav.compare",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=compare",
    label: "Compare",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Scale",
    customRef: null,
    sortOrder: 3,
  },
  // (The "customer.budget-subnav.lock" slot was removed 2026-06-20 — "Build
  // absorbs Lock" PR2: the standalone Lock tab is gone; the lock surface now
  // lives inside the Build tab, so its sub-nav child + slot default went too.
  // customer-menu.ts derives the Explore children from BUDGET_BUILD_TABS, which
  // no longer includes 'lock'.)
  // Studio docked sub-nav — the 4 sections of the /add-ons hub (customer-menu
  // redesign 2026-06-17). The mobile <SubNav> overlays these admin overrides on
  // its code defaults (lib/customer-menu.ts child.slotKey).
  {
    key: "customer.studio-subnav.setnayan-ai",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/studio#studio-ai",
    label: "Setnayan AI",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gem",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.studio-subnav.website",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/studio#studio-website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.studio-subnav.capture",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/studio#studio-capture",
    label: "Capture",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.studio-subnav.branding",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/studio#studio-branding",
    label: "Branding",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 3,
  },
  {
    // "Event page" — a ROUTE child in the Studio docked sub-nav (the others
    // are on-page anchors). Taps through to /event-page → the live /[slug].
    // Owner 2026-06-26 "host should see the same event page we created".
    key: "customer.studio-subnav.event-page",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/event-page",
    label: "Event page",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Eye",
    customRef: null,
    sortOrder: 4,
  },
  {
    // "Launch" route child (owner 2026-06-28) — preview + go-live surface.
    key: "customer.studio-subnav.launch",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/website/launch",
    label: "Launch",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Rocket",
    customRef: null,
    sortOrder: 5,
  },
  // Budget docked sub-nav — the 3 on-page scroll sections of /budget.
  {
    key: "customer.budget-anchors.overview",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-overview",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gauge",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.budget-anchors.allocate",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-allocate",
    label: "Allocate",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PieChart",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.budget-anchors.payments",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-payments",
    label: "Payments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.build-pin.budget",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Budget",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.build-pin.services",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ListChecks",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.build-pin.date",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Date",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarRange",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-carousel.summary",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=summary",
    label: "Summary",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart3",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.guest-carousel.search",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=find",
    label: "Search",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Search",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.guest-carousel.add",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=add",
    label: "Add",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UserPlus",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-carousel.customize",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=customize",
    label: "Customize",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "SlidersHorizontal",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.guest-carousel.journey",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=journey",
    label: "Journey",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Route",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.sidebar.overview",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    // My Shop — the storefront destination (proto-shell 6-menu flat sidebar).
    key: "vendor.sidebar.shop",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/shop",
    label: "My Shop",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShoppingBag",
    customRef: null,
    sortOrder: 1,
  },
  {
    // My Customers — the booking-pipeline destination (proto-shell 6-menu).
    key: "vendor.sidebar.customers",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/customers",
    label: "My Customers",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 2,
  },
  {
    // Overview tab (key 'home' — the flat item key stays 'profile', mapped to
    // this 'home' slot in vendor-bottom-nav for localStorage continuity).
    key: "vendor.bottom-nav.home",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.sidebar.profile",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/profile",
    label: "Profile",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "User",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.sidebar.website",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "vendor.sidebar.bookings",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/bookings",
    label: "Bookings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "vendor.sidebar.calendar",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/calendar",
    label: "Calendar",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarDays",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.sidebar.clients",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/clients",
    label: "Clients",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "vendor.sidebar.messages",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/messages",
    label: "Messages",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquare",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "vendor.sidebar.services",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/services",
    label: "My Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ClipboardList",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "vendor.sidebar.contracts",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/contracts",
    label: "Contracts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileSignature",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "vendor.sidebar.proposals",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/proposals",
    label: "Proposals",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "vendor.sidebar.repertoire",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/repertoire",
    label: "Repertoire",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "vendor.sidebar.attributes",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/attributes",
    label: "Attributes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "vendor.sidebar.subscription",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/subscription",
    label: "Plan & tokens",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Crown",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "vendor.sidebar.verify",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/verify",
    label: "Verify",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShieldCheck",
    customRef: null,
    sortOrder: 16,
  },
  {
    // Vendor partnerships — declare vendor-to-vendor relationships; HQ reviews
    // before badges appear on couple search results.
    key: "vendor.sidebar.partnerships",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/partnerships",
    label: "Partnerships",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Handshake",
    customRef: null,
    sortOrder: 17,
  },
  {
    // "Recommend to your couples" (Phase 3a) — curated add-on map keyed to the
    // vendor's own leaves. Grow group · owner/admin only.
    key: "vendor.sidebar.recommendations",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/recommendations",
    label: "Recommend",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Lightbulb",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "vendor.sidebar.reviews",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/reviews",
    label: "Reviews",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "vendor.sidebar.real-stories",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/real-stories",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "vendor.sidebar.recaps",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/recaps",
    label: "Recaps",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Images",
    customRef: null,
    sortOrder: 19,
  },
  {
    key: "vendor.sidebar.moodboard-library",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/moodboard-library",
    label: "Moodboard library",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 20,
  },
  {
    key: "vendor.sidebar.earnings",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/earnings",
    label: "Earnings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 21,
  },
  {
    key: "vendor.sidebar.payment-options",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/payment-options",
    label: "How clients pay you",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 22,
  },
  {
    key: "vendor.sidebar.manpower",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/manpower",
    label: "Manpower",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "HardHat",
    customRef: null,
    sortOrder: 23,
  },
  {
    key: "vendor.sidebar.branches",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/branches",
    label: "Branches",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Building2",
    customRef: null,
    sortOrder: 24,
  },
  {
    key: "vendor.sidebar.team",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/team",
    label: "Team & Setnayan",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 25,
  },
  {
    key: "vendor.sidebar.on-the-day",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/on-the-day",
    label: "On the Day",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarCheck",
    customRef: null,
    sortOrder: 26,
  },
  {
    // My Performance — the flat 6-menu destination. Keys match the sidebar item
    // keys 1:1 so /admin/menus can rename/hide them (previously hardcoded-only,
    // no slot). Default seeded from the group-tree sub-item label ("Overview")
    // by mistake; the flat destination reads "My Performance".
    key: "vendor.sidebar.performance",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/performance",
    label: "My Performance",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gauge",
    customRef: null,
    sortOrder: 27,
  },
  {
    key: "vendor.sidebar.demand",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/demand",
    label: "Demand Radar",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Radar",
    customRef: null,
    sortOrder: 28,
  },
  // vendor.sidebar.funnel RETIRED 2026-07-02 — the Quote-to-Booking Funnel was
  // folded into /vendor-dashboard/performance (owner "just integrate this to My
  // Performance"). Slot removed so it stops surfacing in the sidebar + /admin/menus.
  {
    // My Customers group — Payday (cash-flow / installment surface).
    key: "vendor.sidebar.payday",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/payday",
    label: "Payday",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarClock",
    customRef: null,
    sortOrder: 30,
  },
  {
    // Bottom-nav strip rerostered 2026-07-01 to the 6-tab proto-shell (Overview
    // · Shop · Customers · Performance · Services · On the Day). The 'home' slot
    // above carries Overview; these five cover the other tabs. The legacy
    // bookings/calendar/messages/more bottom-nav slots were replaced — those
    // surfaces still live in the /more landing + the sidebar routing.
    key: "vendor.bottom-nav.shop",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/shop",
    label: "Shop",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShoppingBag",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.bottom-nav.customers",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/customers",
    label: "Customers",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "vendor.bottom-nav.performance",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/performance",
    label: "Performance",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart2",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "vendor.bottom-nav.services",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/services",
    label: "Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.bottom-nav.onday",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/on-the-day",
    label: "On the Day",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarCheck",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "vendor.topbar.notifications",
    scope: "vendor",
    area: "vendor-topbar",
    route: "/vendor-dashboard/notifications",
    label: "Notifications",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.payment-options.bank",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "Bank / e-wallet",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Landmark",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.payment-options.qr",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "QR code",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.payment-options.link",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "Payment link",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Link2",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "admin.sidebar.overview",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    // 6-menu respine 2026-07-03: the mobile Home tab is now "Overview" — the
    // merged Home+Work task inbox (key stays 'home' so an existing admin
    // label/icon override survives).
    key: "admin.bottom-nav.home",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    // "All work" — desktop entry to the /admin/work command center (the ranked
    // worklist). Sits at the top of the Work group; renamable/hideable here.
    key: "admin.sidebar.work-home",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/work",
    label: "All work",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ListChecks",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "admin.sidebar.verify",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/verify",
    label: "Verify",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BadgeCheck",
    customRef: null,
    sortOrder: 2,
  },
  {
    // Vendor partnerships two-admin verification queue (PR #11 vendor-quality).
    key: "admin.sidebar.vendor-partnerships",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/vendor-partnerships",
    label: "Partnerships",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Handshake",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "admin.sidebar.payments",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payments",
    label: "Payments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Banknote",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "admin.sidebar.payouts",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payouts",
    label: "Payouts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "admin.sidebar.token-purchases",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/token-purchases",
    label: "Token sales",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShoppingBag",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "admin.sidebar.menus",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/menus",
    label: "Menus & icons",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shapes",
    customRef: null,
    sortOrder: 55,
  },
  {
    // Vendor "recommend to your couples" map — leaf → SKU recommendation table
    // + two-way curation review queue (Monetization group). Item key matches
    // the admin-sidebar item suffix 1:1 so the registry overlay applies.
    key: "admin.sidebar.vendor-recommendations",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/vendor-recommendations",
    label: "Vendor recommendations",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Lightbulb",
    customRef: null,
    sortOrder: 56,
  },
  {
    key: "admin.sidebar.subscriptions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/subscriptions",
    label: "Subscriptions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "RefreshCw",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "admin.sidebar.payment-options",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payment-options",
    label: "Payment options",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CreditCard",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "admin.sidebar.disputes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/disputes",
    label: "Disputes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shield",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "admin.sidebar.pax-changes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pax-changes",
    label: "Pax changes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UsersRound",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "admin.sidebar.force-majeure",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/force-majeure",
    label: "Force majeure",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "AlertOctagon",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "admin.sidebar.completions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/completions",
    label: "Completions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Handshake",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "admin.sidebar.reviews",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/reviews",
    label: "Reviews",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "admin.sidebar.concierge-abuse",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/concierge-abuse",
    label: "Setnayan AI abuse",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Flag",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "admin.sidebar.account-deletions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/account-deletions",
    label: "Account deletions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UserX",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "admin.sidebar.user-reports",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/user-reports",
    label: "User reports",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquareWarning",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "admin.sidebar.fraud",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/fraud",
    label: "Fraud queue",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShieldAlert",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "admin.sidebar.approvals",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/approvals",
    label: "Approvals",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CheckCheck",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "admin.sidebar.social-queue",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/social-queue",
    label: "Social queue",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Share2",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "admin.sidebar.pakanta",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pakanta",
    label: "Pakanta queue",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 16,
  },
  {
    // Editorial review queue — couple/vendor editorial submissions awaiting
    // the publish gate. Lives in the Work group in ADMIN_NAV_GROUPS; this
    // default makes its label + icon admin-editable via /admin/menus.
    key: "admin.sidebar.editorial-review",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/editorial-review",
    label: "Editorial review",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Newspaper",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "admin.sidebar.help",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/help",
    label: "Help",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LifeBuoy",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "admin.sidebar.users",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/users",
    label: "Users",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "admin.sidebar.vendors",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/vendors",
    label: "Vendors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 19,
  },
  {
    key: "admin.sidebar.demo-vendors",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/demo-vendors",
    label: "Demo vendors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "TestTube",
    customRef: null,
    sortOrder: 20,
  },
  {
    key: "admin.sidebar.spotlight-awards",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/spotlight-awards",
    label: "Spotlight Awards",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Trophy",
    customRef: null,
    sortOrder: 20.5,
  },
  {
    key: "admin.sidebar.journal-spotlights",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/journal-spotlights",
    label: "Journal Spotlights",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BookOpen",
    customRef: null,
    sortOrder: 20.6,
  },
  {
    key: "admin.sidebar.events",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/events",
    label: "Events",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarDays",
    customRef: null,
    sortOrder: 21,
  },
  {
    key: "admin.sidebar.venues",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/venues",
    label: "Venues",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 22,
  },
  {
    // App Performance cockpit — leads the renamed (2026-07-03) sidebar group;
    // registry slot so /admin/menus can rename/re-icon/hide it like siblings.
    key: "admin.sidebar.app-performance",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/app-performance",
    label: "App Performance",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Activity",
    customRef: null,
    sortOrder: 22.5,
  },
  {
    key: "admin.sidebar.growth",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/growth",
    label: "Growth",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LineChart",
    customRef: null,
    sortOrder: 23,
  },
  {
    key: "admin.sidebar.intelligence",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/intelligence",
    label: "Intelligence",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Radar",
    customRef: null,
    sortOrder: 24,
  },
  {
    key: "admin.sidebar.funnels",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/funnels",
    label: "Funnels",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart3",
    customRef: null,
    sortOrder: 25,
  },
  {
    key: "admin.sidebar.operations-hiring",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/operations-hiring",
    label: "Operations & Hiring",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "TrendingUp",
    customRef: null,
    sortOrder: 26,
  },
  {
    key: "admin.sidebar.connection-logs",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/connection-logs",
    label: "Connection logs",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bug",
    customRef: null,
    sortOrder: 27,
  },
  {
    key: "admin.sidebar.offline",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/offline",
    label: "Offline daemon",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "WifiOff",
    customRef: null,
    sortOrder: 28,
  },
  {
    key: "admin.sidebar.pricing",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pricing",
    label: "Pricing",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "DollarSign",
    customRef: null,
    sortOrder: 29,
  },
  {
    key: "admin.sidebar.addons",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/addons",
    label: "Add-ons",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 30,
  },
  {
    key: "admin.sidebar.discount-codes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/discount-codes",
    label: "Discount codes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 31,
  },
  {
    key: "admin.sidebar.token-bands",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/token-bands",
    label: "Token bands",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Coins",
    customRef: null,
    sortOrder: 32,
  },
  {
    key: "admin.sidebar.price-bands",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/price-bands",
    label: "Price bands",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gauge",
    customRef: null,
    sortOrder: 32,
  },
  {
    key: "admin.sidebar.budget-planner",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/budget-planner",
    label: "Budget Planner",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PiggyBank",
    customRef: null,
    sortOrder: 33,
  },
  {
    key: "admin.sidebar.receipts",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/receipts",
    label: "Receipts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 34,
  },
  {
    key: "admin.sidebar.payment-methods",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings/payment-methods",
    label: "Payment methods",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Landmark",
    customRef: null,
    sortOrder: 35,
  },
  {
    key: "admin.sidebar.settings",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings",
    label: "Settings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Settings",
    customRef: null,
    sortOrder: 36,
  },
  {
    // Compliance — RA 10173 / NPC registration facts (settings-tail item).
    key: "admin.sidebar.compliance",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/compliance",
    label: "Compliance",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShieldCheck",
    customRef: null,
    sortOrder: 37,
  },
  {
    key: "admin.sidebar.onboarding",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/onboarding",
    label: "Onboarding",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 37,
  },
  {
    key: "admin.sidebar.taxonomy",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/taxonomy",
    label: "Taxonomy",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 38,
  },
  // admin.sidebar.event-types REMOVED 2026-07-03 — /admin/event-types was folded
  // into the Taxonomy Studio's Vocabularies → Event types rail
  // (/admin/taxonomy?view=vocab-event); the event-type roster (couple-launch
  // `enabled` lever + picker-card presentation + retire/un-retire) now lives
  // there beside category scoping. The standalone page redirects. Seed default
  // dropped so it stops seeding into /admin/menus. Any stale nav_slot_override
  // row for this key is inert — the renderer iterates code defaults and overlays
  // overrides (lib/nav-registry.ts), so an override with no matching default is
  // never rendered.
  // admin.sidebar.refinements REMOVED 2026-07-03 — /admin/refinements was retired
  // to a redirect(/admin/taxonomy); refinements are now edited in the Taxonomy
  // Studio inspector's Refinements tab. Seed default dropped so it stops seeding
  // into /admin/menus. Any stale nav_slot_override row for this key is inert — the
  // renderer iterates code defaults and overlays overrides (lib/nav-registry.ts),
  // so an override with no matching default is never rendered.
  {
    key: "admin.sidebar.website",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 41,
  },
  {
    key: "admin.sidebar.hero-video",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/hero-video",
    label: "Hero video",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Video",
    customRef: null,
    sortOrder: 42,
  },
  {
    key: "admin.sidebar.background-videos",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/background-videos",
    label: "Background videos",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Film",
    customRef: null,
    sortOrder: 42,
  },
  {
    key: "admin.sidebar.reveal-studio",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/reveal-studio",
    label: "Reveal Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 42,
  },
  {
    key: "admin.sidebar.real-stories",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/real-stories",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Newspaper",
    customRef: null,
    sortOrder: 43,
  },
  {
    key: "admin.sidebar.recaps",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/recaps",
    label: "Recaps",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Images",
    customRef: null,
    sortOrder: 44,
  },
  {
    key: "admin.sidebar.brain",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/brain",
    label: "Setnayan AI brain",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Brain",
    customRef: null,
    sortOrder: 46,
  },
  {
    key: "admin.sidebar.moodboard-library",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/moodboard-library",
    label: "Moodboard library",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 47,
  },
  {
    key: "admin.sidebar.songs",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/songs",
    label: "Songs",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 48,
  },
  // admin.sidebar.wedding-types REMOVED 2026-07-03 — /admin/wedding-types was
  // retired to a redirect(/admin/taxonomy?view=vocab-faith); the per-faith launch
  // gate now lives in the Taxonomy Studio's Vocabularies → Faiths rail. Seed
  // default dropped so it stops seeding into /admin/menus. Any stale
  // nav_slot_override row for this key is inert — the renderer iterates code
  // defaults and overlays overrides (lib/nav-registry.ts), so an override with no
  // matching default is never rendered.
  {
    key: "admin.sidebar.wedding-traditions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/wedding-traditions",
    label: "Wedding traditions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BookOpen",
    customRef: null,
    sortOrder: 50,
  },
  {
    key: "admin.sidebar.notifications",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/notifications",
    label: "Notifications",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 51,
  },
  {
    key: "admin.sidebar.demo-mode",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings/demo-mode",
    label: "Demo mode",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Settings",
    customRef: null,
    sortOrder: 52,
  },
  {
    key: "admin.sidebar.my-account",
    scope: "admin",
    area: "admin-sidebar",
    route: "/dashboard/profile",
    label: "My account",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleUser",
    customRef: null,
    sortOrder: 53,
  },
  {
    // 6-menu respine 2026-07-03: Directory tab renders "Accounts" (key stays
    // 'directory' so an existing override survives). The old Work + Money tab
    // defaults were REMOVED with their tabs — Work merged into Overview, Money
    // config moved to System Settings (More) + Marketing.
    key: "admin.bottom-nav.directory",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/directory",
    label: "Accounts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 1,
  },
  {
    // Marketing tab (6-menu respine 2026-07-03) — social queue + featuring +
    // growth incentives; lands on the /admin/marketing card grid.
    key: "admin.bottom-nav.marketing",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/marketing",
    label: "Marketing",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Megaphone",
    customRef: null,
    sortOrder: 2,
  },
  {
    // Performance tab (6-menu respine 2026-07-03) — lands directly on the App
    // Performance cockpit.
    key: "admin.bottom-nav.performance",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/app-performance",
    label: "Performance",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Activity",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "admin.bottom-nav.more",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/more",
    label: "More",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Menu",
    customRef: null,
    sortOrder: 4,
  },
];
