// AUTO-GENERATED from the icon-menu-registry-map discovery workflow (2026-06-16).
// The canonical default NAME + ICON for every menu/route slot across Setnayan,
// all account types. This is the route-meta successor: the single in-code source
// the admin /admin/menus overrides layer on top of. Regenerate from the design doc
// `Nav_Icon_Menu_Registry_Design_2026-06-16.md` when slots change.
//
// DO hand-edit to add NEW slots / fix a default; keep keys stable (overrides key off them).

import type { NavSlotDefault } from './nav-registry-types';

export const NAV_SLOT_DEFAULTS: readonly NavSlotDefault[] = [
  {
    key: "public.marketing.home",
    scope: "public",
    area: "marketing-site",
    route: "/",
    label: "Setnayan brand logo / Home",
    labelKind: "literal",
    iconKind: "custom",
    lucideName: null,
    customRef: "SetnayanMark",
    sortOrder: 0,
  },
  {
    key: "public.site-nav.explore",
    scope: "public",
    area: "marketing-site-nav",
    route: "/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.site-nav.for-vendors",
    scope: "public",
    area: "marketing-site-nav",
    route: "/for-vendors",
    label: "For vendors",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.site-nav.our-story",
    scope: "public",
    area: "marketing-site-nav",
    route: "/our-story",
    label: "Our story",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "public.site-nav.journal",
    scope: "public",
    area: "marketing-site-nav",
    route: "/blog",
    label: "Journal",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "public.site-nav.real-stories",
    scope: "public",
    area: "marketing-site-nav",
    route: "/weddings",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "public.download.page",
    scope: "public",
    area: "download-page",
    route: "/download",
    label: "Mac app",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Apple",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.download.mac-api",
    scope: "public",
    area: "download-page",
    route: "/api/download/mac",
    label: "Download for Mac",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Download",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.download.qr-png",
    scope: "public",
    area: "download-page",
    route: "/api/website/qr/detail",
    label: "Download PNG",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Download",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "public.guest.find-my-table",
    scope: "public",
    area: "guest-experience",
    route: "/guests/find-my-table",
    label: "Find my table",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "public.guest.find-seat",
    scope: "public",
    area: "guest-experience",
    route: "/guests/find-seat",
    label: "Find your seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "public.papic.guest",
    scope: "public",
    area: "papic-guest-gallery",
    route: "/papic/guest",
    label: "Be a candid camera",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.sidebar.home",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]",
    label: "Home",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.bottom-nav.home",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]",
    label: "Home",
    labelKind: "literal",
    iconKind: "custom",
    lucideName: null,
    customRef: "SetnayanMark",
    sortOrder: 0,
  },
  {
    key: "customer.bottom-nav.guests",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/guests",
    label: "Guests",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.bottom-nav.explore",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.bottom-nav.studio",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/add-ons",
    label: "Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.bottom-nav.budget",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/budget",
    label: "Budget",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.sidebar.studio",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/add-ons",
    label: "Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.sidebar.explore",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/vendors",
    label: "Explore",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.sidebar.guests",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests",
    label: "Guests",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.sidebar.guests.build",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PencilLine",
    customRef: null,
    sortOrder: 31,
  },
  {
    key: "customer.sidebar.guests.invite",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/invite",
    label: "Invite",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 32,
  },
  {
    key: "customer.sidebar.guests.confirm",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleCheck",
    customRef: null,
    sortOrder: 33,
  },
  {
    // "Seat" stage — reuses the existing seating slot key so the admin can
    // still rename / reicon it whether it's a top-level row or a child row.
    key: "customer.sidebar.seating",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/seating",
    label: "Seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 34,
  },
  {
    key: "customer.sidebar.guests.dayof",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 35,
  },
  {
    key: "customer.sidebar.schedule",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/schedule",
    label: "Schedule",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarClock",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.sidebar.budget",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/budget",
    label: "Budget",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "customer.bottom-nav.design",
    scope: "customer",
    area: "customer-bottom-nav",
    route: "/dashboard/[eventId]/design",
    label: "Design",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.sidebar.messages",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/messages",
    label: "Messages",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquare",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "customer.sidebar.contracts",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/contracts",
    label: "Contracts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "customer.sidebar.website",
    scope: "customer",
    area: "customer-sidebar",
    route: "/site-editor/[eventId]",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.sidebar.mood-board",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/add-ons/mood-board",
    label: "Mood Board",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "customer.sidebar.monogram",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/monogram",
    label: "Monogram",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Type",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "customer.sidebar.live",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/live",
    label: "Live Wall",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MonitorPlay",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "customer.sidebar.event-qr",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/event-qr",
    label: "Event QR",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "customer.sidebar.activity",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/activity",
    label: "Activity",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Activity",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "customer.sidebar.disputes",
    scope: "customer",
    area: "customer-sidebar",
    route: "/dashboard/[eventId]/disputes",
    label: "Disputes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shield",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "customer.guest-journey.build",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PencilLine",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.guest-journey.invite",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/invite",
    label: "Invite",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.guest-journey.confirm",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleCheck",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-journey.seat",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/seating",
    label: "Seat",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.guest-journey.dayof",
    scope: "customer",
    area: "guests-section-subnav",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.profile-menu.hosts",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/[eventId]/hosts",
    label: "Hosts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Heart",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.profile-menu.personalization",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/[eventId]/details",
    label: "Personalization",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.profile-menu.profile",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/profile",
    label: "Profile",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.profile-menu.settings",
    scope: "customer",
    area: "profile-menu",
    route: "/dashboard/profile#settings",
    label: "Settings",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.profile-menu.sign-out",
    scope: "customer",
    area: "profile-menu",
    route: "/auth/sign-out",
    label: "Sign out",
    labelKind: "literal",
    iconKind: "none",
    lucideName: null,
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.route.documents",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/documents",
    label: "Documents",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.route.guests-checkin",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/guests/checkin",
    label: "Day-of",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.route.guests-claims",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/guests/claims",
    label: "Invite / Confirm",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Send",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.route.hosts",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/hosts",
    label: "nav.hosts",
    labelKind: "i18nKey",
    iconKind: "lucide",
    lucideName: "UserPlus",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.route.invitation",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/invitation",
    label: "Invitation & URL",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Pencil",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.route.manpower",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/manpower",
    label: "Manpower",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "HardHat",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.route.notifications",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/notifications",
    label: "nav.notifications",
    labelKind: "i18nKey",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "customer.route.orders",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/orders",
    label: "Orders",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "customer.route.paperwork",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/paperwork",
    label: "Paperwork / Government paperwork",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ScrollText",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "customer.route.profile",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/profile",
    label: "My account",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleUser",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.route.sponsors",
    scope: "customer",
    area: "customer-route-meta",
    route: "/dashboard/[eventId]/sponsors",
    label: "Sponsors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "customer.website-editor.dress-code",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/dress-code",
    label: "Edit dress code",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shirt",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.website-editor.photo-moments",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/photo-moments",
    label: "Edit photo moments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.website-editor.privacy",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/privacy",
    label: "Who can view",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Lock",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.website-editor.site-chrome",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/site-chrome",
    label: "Edit music & video",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.website-editor.widgets",
    scope: "customer",
    area: "website-editor",
    route: "/dashboard/[eventId]/website/widgets",
    label: "Customize widgets",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LayoutGrid",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.studio.setnayan-ai",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/setnayan-ai",
    label: "Setnayan AI",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gem",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.studio.orders",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/orders",
    label: "Orders",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.studio.save-the-date",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/save-the-date",
    label: "Save the Date",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.studio.landing-page",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/landing-page",
    label: "Landing Page",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe2",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.studio.music-creator",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/music-creator",
    label: "Music Creator",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "customer.studio.playlist",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/playlist",
    label: "Playlist",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "customer.studio.pakanta",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/pakanta",
    label: "Pakanta",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "customer.studio.animated-monogram",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/animated-monogram",
    label: "Monogram Creator",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Type",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "customer.studio.custom-qr-guest",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/custom-qr-guest",
    label: "Custom QR per guest",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "customer.studio.papic",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/papic",
    label: "Papic",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "customer.studio.panood",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/panood",
    label: "Panood",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tv",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "customer.studio.panood-broadcast",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/panood/broadcast",
    label: "Open broadcaster preview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tv",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "customer.studio.photo-delivery",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/photo-delivery",
    label: "Photo Delivery",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ImageDown",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "customer.studio.patiktok",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/patiktok",
    label: "Patiktok",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Film",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "customer.studio.supplies-marketplace",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/supplies-marketplace",
    label: "Paprint",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Printer",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "customer.studio.led",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/led",
    label: "LED Background",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "customer.studio.indoor-blueprint",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/indoor-blueprint",
    label: "Indoor Blueprint",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 16,
  },
  {
    key: "customer.studio.mood-board",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons/mood-board",
    label: "Mood Board",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "customer.studio.index",
    scope: "customer",
    area: "studio-addon-hub",
    route: "/dashboard/[eventId]/add-ons",
    label: "Studio",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "customer.budget-subnav.summary",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=summary",
    label: "Summary",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gauge",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.budget-subnav.shortlist",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=shortlist",
    label: "Shortlist",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bookmark",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.budget-subnav.build",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=build",
    label: "Build",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Hammer",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.budget-subnav.compare",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=compare",
    label: "Compare",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Scale",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.budget-subnav.lock",
    scope: "customer",
    area: "budget-build-subnav",
    route: "/dashboard/[eventId]/budget?tab=lock",
    label: "Lock",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Lock",
    customRef: null,
    sortOrder: 4,
  },
  // Studio docked sub-nav — the 4 sections of the /add-ons hub (customer-menu
  // redesign 2026-06-17). The mobile <SubNav> overlays these admin overrides on
  // its code defaults (lib/customer-menu.ts child.slotKey).
  {
    key: "customer.studio-subnav.setnayan_ai",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/add-ons#studio-ai",
    label: "Setnayan AI",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gem",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.studio-subnav.website",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/add-ons#studio-website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.studio-subnav.capture",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/add-ons#studio-capture",
    label: "Capture",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Camera",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.studio-subnav.branding",
    scope: "customer",
    area: "studio-subnav",
    route: "/dashboard/[eventId]/add-ons#studio-branding",
    label: "Branding",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 3,
  },
  // Budget docked sub-nav — the 3 on-page scroll sections of /budget.
  {
    key: "customer.budget-anchors.overview",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-overview",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Gauge",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.budget-anchors.allocate",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-allocate",
    label: "Allocate",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PieChart",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.budget-anchors.payments",
    scope: "customer",
    area: "budget-anchors-subnav",
    route: "/dashboard/[eventId]/budget#budget-payments",
    label: "Payments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.build-pin.budget",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Budget",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.build-pin.services",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ListChecks",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.build-pin.date",
    scope: "customer",
    area: "budget-build-control",
    route: null,
    label: "Date",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarRange",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-carousel.summary",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=summary",
    label: "Summary",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart3",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "customer.guest-carousel.search",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=find",
    label: "Search",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Search",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "customer.guest-carousel.add",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=add",
    label: "Add",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UserPlus",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "customer.guest-carousel.customize",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=customize",
    label: "Customize",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "SlidersHorizontal",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "customer.guest-carousel.journey",
    scope: "customer",
    area: "guests-mobile-carousel",
    route: "/dashboard/[eventId]/guests?panel=journey",
    label: "Journey",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Route",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.sidebar.overview",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.bottom-nav.home",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard",
    label: "Home",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.sidebar.profile",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/profile",
    label: "Profile",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "User",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.sidebar.website",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "vendor.bottom-nav.website",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.sidebar.bookings",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/bookings",
    label: "Bookings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "vendor.sidebar.calendar",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/calendar",
    label: "Calendar",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarDays",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.sidebar.clients",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/clients",
    label: "Clients",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "vendor.sidebar.messages",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/messages",
    label: "Messages",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquare",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "vendor.sidebar.services",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/services",
    label: "Services",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ClipboardList",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "vendor.sidebar.contracts",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/contracts",
    label: "Contracts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileSignature",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "vendor.sidebar.proposals",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/proposals",
    label: "Proposals",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "FileText",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "vendor.sidebar.repertoire",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/repertoire",
    label: "Repertoire",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "vendor.sidebar.attributes",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/attributes",
    label: "Attributes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "vendor.sidebar.subscription",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/subscription",
    label: "Subscription",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Crown",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "vendor.sidebar.tokens",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/tokens",
    label: "Tokens",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Coins",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "vendor.sidebar.redeem-code",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/redeem-code",
    label: "Redeem code",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "vendor.sidebar.marketing",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/marketing",
    label: "Marketing",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Megaphone",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "vendor.sidebar.verify",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/verify",
    label: "Verify",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShieldCheck",
    customRef: null,
    sortOrder: 16,
  },
  {
    key: "vendor.sidebar.reviews",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/reviews",
    label: "Reviews",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "vendor.sidebar.real-stories",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/real-stories",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "vendor.sidebar.recaps",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/recaps",
    label: "Recaps",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Images",
    customRef: null,
    sortOrder: 19,
  },
  {
    key: "vendor.sidebar.moodboard-library",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/moodboard-library",
    label: "Moodboard library",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 20,
  },
  {
    key: "vendor.sidebar.earnings",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/earnings",
    label: "Earnings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 21,
  },
  {
    key: "vendor.sidebar.payment-options",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/payment-options",
    label: "How clients pay you",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 22,
  },
  {
    key: "vendor.sidebar.manpower",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/manpower",
    label: "Manpower",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "HardHat",
    customRef: null,
    sortOrder: 23,
  },
  {
    key: "vendor.sidebar.branches",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/branches",
    label: "Branches",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Building2",
    customRef: null,
    sortOrder: 24,
  },
  {
    key: "vendor.sidebar.team",
    scope: "vendor",
    area: "vendor-sidebar",
    route: "/vendor-dashboard/team",
    label: "Team & Setnayan",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 25,
  },
  {
    key: "vendor.bottom-nav.bookings",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/bookings",
    label: "Bookings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "vendor.bottom-nav.calendar",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/calendar",
    label: "Calendar",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarDays",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "vendor.bottom-nav.messages",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/messages",
    label: "Messages",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquare",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "vendor.bottom-nav.more",
    scope: "vendor",
    area: "vendor-bottom-nav",
    route: "/vendor-dashboard/more",
    label: "More",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Menu",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "vendor.topbar.notifications",
    scope: "vendor",
    area: "vendor-topbar",
    route: "/vendor-dashboard/notifications",
    label: "Notifications",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.payment-options.bank",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "Bank / e-wallet",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Landmark",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "vendor.payment-options.qr",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "QR code",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "QrCode",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "vendor.payment-options.link",
    scope: "vendor",
    area: "vendor-payment-options",
    route: null,
    label: "Payment link",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Link2",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "admin.sidebar.overview",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin",
    label: "Overview",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "admin.bottom-nav.home",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin",
    label: "Home",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Home",
    customRef: null,
    sortOrder: 0,
  },
  {
    key: "admin.sidebar.verify",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/verify",
    label: "Verify",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BadgeCheck",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "admin.sidebar.payments",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payments",
    label: "Payments",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Banknote",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "admin.sidebar.payouts",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payouts",
    label: "Payouts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Wallet",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "admin.sidebar.token-purchases",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/token-purchases",
    label: "Token sales",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ShoppingBag",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "admin.sidebar.menus",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/menus",
    label: "Menus & icons",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shapes",
    customRef: null,
    sortOrder: 55,
  },
  {
    key: "admin.sidebar.subscriptions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/subscriptions",
    label: "Subscriptions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "RefreshCw",
    customRef: null,
    sortOrder: 5,
  },
  {
    key: "admin.sidebar.payment-options",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/payment-options",
    label: "Payment options",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CreditCard",
    customRef: null,
    sortOrder: 6,
  },
  {
    key: "admin.sidebar.disputes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/disputes",
    label: "Disputes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Shield",
    customRef: null,
    sortOrder: 7,
  },
  {
    key: "admin.sidebar.pax-changes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pax-changes",
    label: "Pax changes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UsersRound",
    customRef: null,
    sortOrder: 8,
  },
  {
    key: "admin.sidebar.force-majeure",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/force-majeure",
    label: "Force majeure",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "AlertOctagon",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "admin.sidebar.completions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/completions",
    label: "Completions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Handshake",
    customRef: null,
    sortOrder: 9,
  },
  {
    key: "admin.sidebar.reviews",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/reviews",
    label: "Reviews",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Star",
    customRef: null,
    sortOrder: 10,
  },
  {
    key: "admin.sidebar.concierge-abuse",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/concierge-abuse",
    label: "Setnayan AI abuse",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Flag",
    customRef: null,
    sortOrder: 11,
  },
  {
    key: "admin.sidebar.account-deletions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/account-deletions",
    label: "Account deletions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "UserX",
    customRef: null,
    sortOrder: 12,
  },
  {
    key: "admin.sidebar.user-reports",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/user-reports",
    label: "User reports",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MessageSquareWarning",
    customRef: null,
    sortOrder: 13,
  },
  {
    key: "admin.sidebar.approvals",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/approvals",
    label: "Approvals",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CheckCheck",
    customRef: null,
    sortOrder: 14,
  },
  {
    key: "admin.sidebar.social-queue",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/social-queue",
    label: "Social queue",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Share2",
    customRef: null,
    sortOrder: 15,
  },
  {
    key: "admin.sidebar.pakanta",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pakanta",
    label: "Pakanta queue",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 16,
  },
  {
    key: "admin.sidebar.help",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/help",
    label: "Help",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LifeBuoy",
    customRef: null,
    sortOrder: 17,
  },
  {
    key: "admin.sidebar.users",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/users",
    label: "Users",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 18,
  },
  {
    key: "admin.sidebar.vendors",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/vendors",
    label: "Vendors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Briefcase",
    customRef: null,
    sortOrder: 19,
  },
  {
    key: "admin.sidebar.demo-vendors",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/demo-vendors",
    label: "Demo vendors",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "TestTube",
    customRef: null,
    sortOrder: 20,
  },
  {
    key: "admin.sidebar.events",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/events",
    label: "Events",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CalendarDays",
    customRef: null,
    sortOrder: 21,
  },
  {
    key: "admin.sidebar.venues",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/venues",
    label: "Venues",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "MapPin",
    customRef: null,
    sortOrder: 22,
  },
  {
    key: "admin.sidebar.growth",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/growth",
    label: "Growth",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "LineChart",
    customRef: null,
    sortOrder: 23,
  },
  {
    key: "admin.sidebar.intelligence",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/intelligence",
    label: "Intelligence",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Radar",
    customRef: null,
    sortOrder: 24,
  },
  {
    key: "admin.sidebar.funnels",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/funnels",
    label: "Funnels",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart3",
    customRef: null,
    sortOrder: 25,
  },
  {
    key: "admin.sidebar.operations-hiring",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/operations-hiring",
    label: "Operations & Hiring",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "TrendingUp",
    customRef: null,
    sortOrder: 26,
  },
  {
    key: "admin.sidebar.connection-logs",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/connection-logs",
    label: "Connection logs",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bug",
    customRef: null,
    sortOrder: 27,
  },
  {
    key: "admin.sidebar.offline",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/offline",
    label: "Offline daemon",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "WifiOff",
    customRef: null,
    sortOrder: 28,
  },
  {
    key: "admin.sidebar.pricing",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/pricing",
    label: "Pricing",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "DollarSign",
    customRef: null,
    sortOrder: 29,
  },
  {
    key: "admin.sidebar.addons",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/addons",
    label: "Add-ons",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Sparkles",
    customRef: null,
    sortOrder: 30,
  },
  {
    key: "admin.sidebar.discount-codes",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/discount-codes",
    label: "Discount codes",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 31,
  },
  {
    key: "admin.sidebar.token-bands",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/token-bands",
    label: "Token bands",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Coins",
    customRef: null,
    sortOrder: 32,
  },
  {
    key: "admin.sidebar.budget-planner",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/budget-planner",
    label: "Budget Planner",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PiggyBank",
    customRef: null,
    sortOrder: 33,
  },
  {
    key: "admin.sidebar.receipts",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/receipts",
    label: "Receipts",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Receipt",
    customRef: null,
    sortOrder: 34,
  },
  {
    key: "admin.sidebar.payment-methods",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings/payment-methods",
    label: "Payment methods",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Landmark",
    customRef: null,
    sortOrder: 35,
  },
  {
    key: "admin.sidebar.settings",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings",
    label: "Settings",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Settings",
    customRef: null,
    sortOrder: 36,
  },
  {
    key: "admin.sidebar.onboarding",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/onboarding",
    label: "Onboarding",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Compass",
    customRef: null,
    sortOrder: 37,
  },
  {
    key: "admin.sidebar.taxonomy",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/taxonomy",
    label: "Taxonomy",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Tag",
    customRef: null,
    sortOrder: 38,
  },
  {
    key: "admin.sidebar.event-types",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/event-types",
    label: "Event Types",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "PartyPopper",
    customRef: null,
    sortOrder: 39,
  },
  {
    key: "admin.sidebar.refinements",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/refinements",
    label: "Refinements",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "SlidersHorizontal",
    customRef: null,
    sortOrder: 40,
  },
  {
    key: "admin.sidebar.website",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/website",
    label: "Website",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Globe",
    customRef: null,
    sortOrder: 41,
  },
  {
    key: "admin.sidebar.hero-video",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/hero-video",
    label: "Hero video",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Video",
    customRef: null,
    sortOrder: 42,
  },
  {
    key: "admin.sidebar.real-stories",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/real-stories",
    label: "Real Stories",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Newspaper",
    customRef: null,
    sortOrder: 43,
  },
  {
    key: "admin.sidebar.recaps",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/recaps",
    label: "Recaps",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Images",
    customRef: null,
    sortOrder: 44,
  },
  {
    key: "admin.sidebar.ads",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/ads",
    label: "Ads",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Megaphone",
    customRef: null,
    sortOrder: 45,
  },
  {
    key: "admin.sidebar.brain",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/brain",
    label: "Setnayan AI brain",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Brain",
    customRef: null,
    sortOrder: 46,
  },
  {
    key: "admin.sidebar.moodboard-library",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/moodboard-library",
    label: "Moodboard library",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Palette",
    customRef: null,
    sortOrder: 47,
  },
  {
    key: "admin.sidebar.songs",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/songs",
    label: "Songs",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Music",
    customRef: null,
    sortOrder: 48,
  },
  {
    key: "admin.sidebar.wedding-types",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/wedding-types",
    label: "Wedding types",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Church",
    customRef: null,
    sortOrder: 49,
  },
  {
    key: "admin.sidebar.wedding-traditions",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/wedding-traditions",
    label: "Wedding traditions",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BookOpen",
    customRef: null,
    sortOrder: 50,
  },
  {
    key: "admin.sidebar.notifications",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/notifications",
    label: "Notifications",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Bell",
    customRef: null,
    sortOrder: 51,
  },
  {
    key: "admin.sidebar.demo-mode",
    scope: "admin",
    area: "admin-sidebar",
    route: "/admin/settings/demo-mode",
    label: "Demo mode",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Settings",
    customRef: null,
    sortOrder: 52,
  },
  {
    key: "admin.sidebar.my-account",
    scope: "admin",
    area: "admin-sidebar",
    route: "/dashboard/profile",
    label: "My account",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "CircleUser",
    customRef: null,
    sortOrder: 53,
  },
  {
    key: "admin.bottom-nav.work",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/work",
    label: "Work",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "ListChecks",
    customRef: null,
    sortOrder: 1,
  },
  {
    key: "admin.bottom-nav.directory",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/directory",
    label: "Directory",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Users",
    customRef: null,
    sortOrder: 2,
  },
  {
    key: "admin.bottom-nav.money",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/money",
    label: "Money",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "DollarSign",
    customRef: null,
    sortOrder: 3,
  },
  {
    key: "admin.bottom-nav.insights",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/insights",
    label: "Insights",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "BarChart3",
    customRef: null,
    sortOrder: 4,
  },
  {
    key: "admin.bottom-nav.more",
    scope: "admin",
    area: "admin-bottom-nav",
    route: "/admin/more",
    label: "More",
    labelKind: "literal",
    iconKind: "lucide",
    lucideName: "Menu",
    customRef: null,
    sortOrder: 5,
  },
];
