/**
 * THE LIBRARY SEED, GENERATED FROM THE POOL.
 *
 * The 631 challenges are authored once in `papic-challenge-pool.ts` and this
 * turns them into the `INSERT` a migration carries. Nothing is typed twice.
 *
 * ── WHY THIS IS TYPESCRIPT AND NOT THE SCRIPT ──────────────────────────────
 * It started life inside `scripts/emit-papic-challenge-pool.mjs`, and the test
 * that keeps the migration honest imported that file. Typecheck refused it:
 * `TS7016 — could not find a declaration file for '…/emit-papic-challenge-pool
 * .mjs'`. So the logic lives here, fully typed, next to the data it reads, and
 * the script is a thin CLI over it.
 *
 * 🔑 THE TEST NOW IMPORTS THE SAME FUNCTION THE MIGRATION WAS BUILT WITH, not a
 * parallel implementation of it. A guard that re-implements what it checks is
 * two hand-typed things again, wearing a lab coat.
 */
import { CHALLENGE_POOL, type PoolRow } from './papic-challenge-pool';

/** A Postgres string literal. Doubling the quote is the only escape SQL has. */
function lit(v: string | null): string {
  if (v === null) return 'NULL';
  return `'${v.replace(/'/g, "''")}'`;
}

/**
 * A `text[]` literal, or NULL.
 *
 * Used for TWO columns now, and they mean opposite things by NULL:
 * `event_types` NULL is PERMISSIVE ("fits any celebration"), `moment_keys`
 * NULL is RESTRICTIVE ("suits no ceremony moment"). Same rendering, different
 * reading — the columns' own COMMENTs say which, because a reader querying the
 * table never sees this file.
 */
function arr(v: string[] | null): string {
  if (v === null) return 'NULL';
  return `ARRAY[${v.map(lit).join(', ')}]::text[]`;
}

function valuesRow(r: PoolRow): string {
  return (
    `  (${r.libraryId}, ${lit(r.slug)}, ${lit(r.category)}, ${lit(r.title)}, ` +
    `${lit(r.prompt)}, ${lit(r.captureKind)}, ${lit(r.missionType)}, ` +
    `${r.priorityRank === null ? 'NULL' : r.priorityRank}, ${arr(r.eventTypes)}, ` +
    `${arr(r.momentKeys)})`
  );
}

/**
 * ⚠ AN UPSERT, ON PURPOSE. Sixty of these rows are already in production. A
 * plain INSERT aborts the whole migration on the first of them; `ON CONFLICT
 * (library_id) DO UPDATE` re-states the row instead, which is also how a
 * wording fix reaches the table later.
 */
export function emitChallengeSeedSql(pool: PoolRow[] = CHALLENGE_POOL): {
  sql: string;
  count: number;
} {
  const sql = `-- GENERATED by scripts/emit-papic-challenge-pool.mjs — DO NOT EDIT BY HAND.
-- Source of truth: apps/web/lib/papic-challenge-pool.ts (${pool.length} challenges).
INSERT INTO public.papic_challenge_library
  (library_id, slug, category, title, prompt, capture_kind, mission_type, priority_rank, event_types, moment_keys)
VALUES
${pool.map(valuesRow).join(',\n')}
ON CONFLICT (library_id) DO UPDATE SET
  slug          = EXCLUDED.slug,
  category      = EXCLUDED.category,
  title         = EXCLUDED.title,
  prompt        = EXCLUDED.prompt,
  capture_kind  = EXCLUDED.capture_kind,
  mission_type  = EXCLUDED.mission_type,
  priority_rank = EXCLUDED.priority_rank,
  event_types   = EXCLUDED.event_types,
  moment_keys   = EXCLUDED.moment_keys;
`;
  // ⚠ The count comes from the ARRAY, never from counting lines in the SQL. A
  // first cut matched `\n  (` and reported 632 for 631 rows, because the column
  // list is also an indented open-paren. A guard that prints a wrong number
  // teaches the reader to distrust the right ones.
  return { sql, count: pool.length };
}

/**
 * Where the generated block is expected to live. One place, two readers.
 *
 * ⚠ IT MOVES EVERY TIME THE POOL GAINS A COLUMN. An applied migration is never
 * edited, so a regenerated seed ships as a NEW migration and this constant
 * follows it. `20271154904649` (631 rows, no `moment_keys`) stays exactly as it
 * was applied; the ceremony-sequence migration below re-states every row with
 * the new column through the same ON CONFLICT UPSERT.
 */
export const CHALLENGE_SEED_MIGRATION =
  'supabase/migrations/20271189223426_challenges_hang_on_the_ceremony.sql';
