/**
 * route-meta.ts — the icon + label that belong to each route, the visual SIBLING
 * of routes.ts. routes.ts owns the PATH; route-meta owns the GLYPH. Keyed in the
 * SAME nested shape (routeMeta.dashboard.guests.index ↔ routes.dashboard.guests.index)
 * so a nav item reads both from one place:
 *   { href: routes.dashboard.guests.index(e), ...routeMeta.dashboard.guests.index }
 *
 * Single source of truth for a route's IDENTITY icon — change a glyph once here and
 * every nav/sidebar/tile/launcher that reads from it follows. Generated from the
 * whole-app icon↔route audit (172 bindings across all 5 actor surfaces; directional
 * affordance glyphs + dynamic-catalog placeholders excluded).
 *
 * DEFER for dynamic catalogs: add-on detail icons come from lib/add-ons-catalog.ts
 * (ADD_ONS[].Icon) and the admin overview map (_overview-tile ICONS) — those routes
 * read THROUGH their catalog, not a fork here.
 *
 * AUTO-GENERATED skeleton — safe to hand-edit; additive (nothing imports it yet).
 */
import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertOctagon,
  Apple,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Building2,
  CalendarClock,
  CalendarDays,
  Camera,
  CheckCheck,
  Church,
  CircleUser,
  ClipboardList,
  Coins,
  Compass,
  CreditCard,
  Crown,
  DollarSign,
  Download,
  FileSignature,
  FileText,
  Film,
  Flag,
  Gem,
  Globe,
  Globe2,
  HardHat,
  Home,
  ImageDown,
  Images,
  Landmark,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  ListChecks,
  Lock,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  MessageSquareWarning,
  MonitorPlay,
  Music,
  Newspaper,
  Palette,
  PartyPopper,
  Pencil,
  PiggyBank,
  Printer,
  QrCode,
  Radar,
  Receipt,
  RefreshCw,
  ScrollText,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tag,
  TestTube,
  TrendingUp,
  Tv,
  Type,
  User,
  UserPlus,
  UserX,
  Users,
  UsersRound,
  Video,
  Wallet,
  WifiOff,
} from 'lucide-react';
import { SetnayanMark } from '@/app/_components/setnayan-mark-icon';

export type RouteMeta = { icon: LucideIcon; label: string };

export const routeMeta = {
  admin: {
    index: { icon: Home, label: 'Home / Overview' },
    accountDeletions: { icon: UserX, label: 'Account deletions' },
    addons: { icon: Sparkles, label: 'Add-ons' },
    ads: { icon: Megaphone, label: 'Ads' },
    approvals: { icon: CheckCheck, label: 'Approvals' },
    brain: { icon: Brain, label: 'Setnayan AI brain' },
    budgetPlanner: { icon: PiggyBank, label: 'Budget Planner' },
    conciergeAbuse: { icon: Flag, label: 'Setnayan AI abuse' },
    connectionLogs: { icon: Bug, label: 'Connection logs' },
    demoVendors: { icon: TestTube, label: 'Demo vendors' },
    directory: { icon: Users, label: 'Directory' },
    discountCodes: { icon: Tag, label: 'Discount codes' },
    disputes: { icon: Shield, label: 'Disputes' },
    eventTypes: { icon: PartyPopper, label: 'Event Types' },
    events: { icon: CalendarDays, label: 'Events' },
    forceMajeure: { icon: AlertOctagon, label: 'Force majeure' },
    funnels: { icon: BarChart3, label: 'Funnels' },
    growth: { icon: LineChart, label: 'Growth' },
    help: { icon: LifeBuoy, label: 'Help' },
    heroVideo: { icon: Video, label: 'Hero video' },
    insights: { icon: BarChart3, label: 'Insights' },
    intelligence: { icon: Radar, label: 'Intelligence' },
    money: { icon: DollarSign, label: 'Money' },
    moodboardLibrary: { icon: Palette, label: 'Moodboard library' },
    more: { icon: Menu, label: 'More' },
    notifications: { icon: Bell, label: 'Notifications' },
    offline: { icon: WifiOff, label: 'Offline daemon' },
    onboarding: { icon: Compass, label: 'Onboarding' },
    operationsHiring: { icon: TrendingUp, label: 'Operations & Hiring' },
    pakanta: { icon: Music, label: 'Pakanta queue' },
    paxChanges: { icon: UsersRound, label: 'Pax changes' },
    paymentOptions: { icon: CreditCard, label: 'Payment options' },
    payments: { icon: Banknote, label: 'Payments' },
    payouts: { icon: Wallet, label: 'Payouts' },
    pricing: { icon: DollarSign, label: 'Pricing' },
    realStories: { icon: Newspaper, label: 'Real Stories' },
    recaps: { icon: Images, label: 'Recaps' },
    receipts: { icon: Receipt, label: 'Receipts' },
    refinements: { icon: SlidersHorizontal, label: 'Refinements' },
    reviews: { icon: Star, label: 'Reviews' },
    settings: {
      index: { icon: Settings, label: 'Settings' },
      demoMode: { icon: Settings, label: 'Demo mode' },
      paymentMethods: { icon: Landmark, label: 'Payment methods' },
    },
    socialQueue: { icon: Share2, label: 'Social queue' },
    songs: { icon: Music, label: 'Songs' },
    subscriptions: { icon: RefreshCw, label: 'Subscriptions' },
    taxonomy: { icon: Tag, label: 'Taxonomy' },
    tokenBands: { icon: Coins, label: 'Token bands' },
    tokenPurchases: { icon: ShoppingBag, label: 'Token sales' },
    userReports: { icon: MessageSquareWarning, label: 'User reports' },
    users: { icon: Users, label: 'Users' },
    vendors: { icon: Briefcase, label: 'Vendors' },
    venues: { icon: MapPin, label: 'Venues' },
    verify: { icon: BadgeCheck, label: 'Verify' },
    website: { icon: Globe, label: 'Website' },
    weddingTraditions: { icon: BookOpen, label: 'Wedding traditions' },
    weddingTypes: { icon: Church, label: 'Wedding types' },
    work: { icon: ListChecks, label: 'Work' },
  },
  api: {
    download: {
      mac: { icon: Download, label: 'Download for Mac' },
    },
    website: {
      qr: {
        detail: { icon: Download, label: 'Download PNG' },
      },
    },
  },
  dashboard: {
    activity: { icon: Activity, label: 'Activity' },
    addOns: {
      index: { icon: Sparkles, label: 'Studio' },
      animatedMonogram: { icon: Type, label: 'Monogram Creator' },
      customQrGuest: { icon: QrCode, label: 'Custom QR per guest' },
      indoorBlueprint: { icon: MapPin, label: 'Indoor Blueprint' },
      landingPage: { icon: Globe2, label: 'Landing Page' },
      led: { icon: Sparkles, label: 'LED Background' },
      moodBoard: { icon: Palette, label: 'Mood Board' },
      musicCreator: { icon: Music, label: 'Music Creator' },
      pakanta: { icon: Music, label: 'Pakanta' },
      panood: {
        index: { icon: Tv, label: 'Panood' },
        broadcast: { icon: Tv, label: 'Open broadcaster preview' },
      },
      papic: { icon: Camera, label: 'Papic' },
      patiktok: { icon: Film, label: 'Patiktok' },
      photoDelivery: { icon: ImageDown, label: 'Photo Delivery' },
      playlist: { icon: Music, label: 'Playlist' },
      saveTheDate: { icon: Sparkles, label: 'Save the Date' },
      setnayanAi: { icon: Gem, label: 'Setnayan AI' },
      suppliesMarketplace: { icon: Printer, label: 'Paprint' },
    },
    budget: { icon: Wallet, label: 'Budget' },
    contracts: { icon: FileText, label: 'Contracts' },
    detail: { icon: Home, label: 'Home' },
    disputes: { icon: Shield, label: 'Disputes' },
    documents: { icon: FileText, label: 'Documents' },
    eventQr: { icon: QrCode, label: 'Event QR' },
    guests: {
      index: { icon: Users, label: 'Guests' },
      checkin: { icon: QrCode, label: 'Day-of' },
      claims: { icon: Send, label: 'Invite / Confirm' },
    },
    hosts: { icon: UserPlus, label: 'nav.hosts' },
    invitation: { icon: Pencil, label: 'Invitation & URL' },
    live: { icon: MonitorPlay, label: 'Live Wall' },
    manpower: { icon: HardHat, label: 'Manpower' },
    messages: { icon: MessageSquare, label: 'Messages' },
    monogram: { icon: Type, label: 'Monogram' },
    notifications: { icon: Bell, label: 'nav.notifications' },
    orders: { icon: Receipt, label: 'Orders' },
    paperwork: { icon: ScrollText, label: 'Paperwork / Government paperwork' },
    profile: { icon: CircleUser, label: 'My account' },
    schedule: { icon: CalendarClock, label: 'Schedule' },
    seating: { icon: LayoutGrid, label: 'Seating' },
    sponsors: { icon: Star, label: 'Sponsors' },
    vendors: { icon: Compass, label: 'Explore' },
    website: {
      dressCode: { icon: Shirt, label: 'Edit dress code' },
      photoMoments: { icon: Camera, label: 'Edit photo moments' },
      privacy: { icon: Lock, label: 'Who can view' },
      siteChrome: { icon: Music, label: 'Edit music & video' },
      widgets: { icon: LayoutGrid, label: 'Customize widgets' },
    },
  },
  download: { icon: Apple, label: 'Mac app' },
  guest: {
    findMyTable: { icon: MapPin, label: 'Find my table' },
    findSeat: { icon: MapPin, label: 'Find your seat' },
  },
  home: { icon: SetnayanMark, label: 'Setnayan brand logo / Home' },
  papic: {
    guest: { icon: Camera, label: 'Be a candid camera' },
  },
  siteEditor: {
    detail: { icon: Globe, label: 'Website' },
  },
  vendorDashboard: {
    index: { icon: Home, label: 'Home / Overview' },
    attributes: { icon: Tag, label: 'Attributes' },
    bookings: { icon: Briefcase, label: 'Bookings' },
    branches: { icon: Building2, label: 'Branches' },
    calendar: { icon: CalendarDays, label: 'Calendar' },
    clients: { icon: Users, label: 'Clients' },
    contracts: { icon: FileSignature, label: 'Contracts' },
    earnings: { icon: Wallet, label: 'Earnings' },
    manpower: { icon: HardHat, label: 'Manpower' },
    marketing: { icon: Megaphone, label: 'Marketing' },
    messages: { icon: MessageSquare, label: 'Messages' },
    moodboardLibrary: { icon: Palette, label: 'Moodboard library' },
    more: { icon: Menu, label: 'More' },
    paymentOptions: { icon: Wallet, label: 'How clients pay you' },
    profile: { icon: User, label: 'Profile' },
    proposals: { icon: FileText, label: 'Proposals' },
    realStories: { icon: Sparkles, label: 'Real Stories' },
    recaps: { icon: Images, label: 'Recaps' },
    redeemCode: { icon: Tag, label: 'Redeem code' },
    repertoire: { icon: Music, label: 'Repertoire' },
    reviews: { icon: Star, label: 'Reviews' },
    services: { icon: ClipboardList, label: 'Services' },
    subscription: { icon: Crown, label: 'Subscription' },
    team: { icon: Users, label: 'Team & Setnayan' },
    tokens: { icon: Coins, label: 'Tokens' },
    verify: { icon: ShieldCheck, label: 'Verify' },
    website: { icon: Globe, label: 'Website' },
  },
} as const;
