/**
 * Pricing Report route handler — markdown snapshot of every SKU in
 * `public.service_catalog`.
 *
 * Spec corpus: iteration 0023 § 3.12 (Add-on Management) · CLAUDE.md
 * 2026-05-17 row 5 lock. The "Download pricing report" button on
 * /admin/addons hits this route and the browser saves a Markdown file
 * named `setnayan-pricing-{ISO timestamp}.md` per the Content-Disposition
 * attachment header.
 *
 * Auth: route lives under /admin/addons which itself lives under
 * app/admin/layout.tsx — that layout already gates non-admins via
 * `notFound()`. We still re-check at the route handler level because
 * Next.js Route Handlers are NOT auto-wrapped in the layout's auth
 * check (only the page render is). Without the explicit guard a
 * non-admin who knows the URL would download the report directly.
 *
 * Output: plain UTF-8 markdown; no PDF / no XLSX in V1.
 */
import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getCurrentUser } from '@/lib/auth';
import { formatCentavosPhp } from '@/lib/sku-catalog';

type ServiceCatalogRow = {
  sku_code: string;
  display_name: string;
  description: string | null;
  category: string;
  price_centavos: number;
  unit: string;
  multi_purchase: boolean;
  subscription: boolean;
  purchaser_role: 'couple' | 'vendor' | 'either';
  is_active: boolean;
  launch_promo_until: string | null;
};

// Retired 2026-05-28 V2 cutover — the `concierge` category here surfaces
// retired SKU rows (₱2,499 Concierge supplanted by ₱1,499 TODAYS_FOCUS).
// V2 catalog lives in `platform_retail_catalog_v2`; this report still reads
// the legacy `service_catalog` so historical audit + retired rows stay
// downloadable.
const CUSTOMER_CATEGORIES = new Set<string>([
  'couple_addon',
  'panood',
  'papic',
  'patiktok',
  'concierge',
]);

export async function GET() {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  }
  const supabase = await createClient();
  const { data: profile } = await supabase
    .from('users')
    .select('account_type,is_internal,is_team_member')
    .eq('user_id', user.id)
    .maybeSingle();
  const isAdmin =
    profile?.is_internal ||
    profile?.is_team_member ||
    profile?.account_type === 'admin';
  if (!isAdmin) {
    // Mirrors the admin layout's notFound() posture — we don't want to leak
    // the existence of this surface to non-admins.
    return NextResponse.json({ error: 'not found' }, { status: 404 });
  }

  const admin = createAdminClient();
  const { data, error } = await admin
    .from('service_catalog')
    .select(
      'sku_code,display_name,description,category,price_centavos,unit,multi_purchase,subscription,purchaser_role,is_active,launch_promo_until',
    )
    .order('is_active', { ascending: false })
    .order('category', { ascending: true })
    .order('sku_code', { ascending: true });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const rows = (data ?? []) as ServiceCatalogRow[];

  // Three buckets: active customer · active vendor · inactive (all kinds).
  // Mirrors the page's tab split + adds an Inactive section because the
  // report is the audit surface where retired SKUs matter.
  const activeCustomer: ServiceCatalogRow[] = [];
  const activeVendor: ServiceCatalogRow[] = [];
  const inactive: ServiceCatalogRow[] = [];
  rows.forEach((r) => {
    if (!r.is_active) {
      inactive.push(r);
      return;
    }
    if (
      CUSTOMER_CATEGORIES.has(r.category) &&
      r.purchaser_role !== 'vendor'
    ) {
      activeCustomer.push(r);
    } else {
      activeVendor.push(r);
    }
  });

  const generatedAt = new Date();
  const isoTimestamp = generatedAt.toISOString();
  const fileSafeStamp = isoTimestamp.replace(/[:.]/g, '-');
  const fileName = `setnayan-pricing-${fileSafeStamp}.md`;

  const body = [
    `# Setnayan Pricing Report — ${isoTimestamp}`,
    '',
    'Generated by /admin/addons → Download pricing report.',
    '',
    `## Active customer SKUs (${activeCustomer.length})`,
    '',
    renderTable(activeCustomer),
    '',
    `## Active vendor SKUs (${activeVendor.length})`,
    '',
    renderTable(activeVendor),
    '',
    `## Inactive SKUs (${inactive.length})`,
    '',
    renderTable(inactive),
    '',
    '---',
    '',
    'Source of truth: legacy `public.service_catalog`. The V2 canonical',
    'catalog lives in `platform_retail_catalog_v2`; this report is being',
    'migrated to read both. Run again any time to refresh.',
    '',
  ].join('\n');

  return new NextResponse(body, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
      'Cache-Control': 'no-store',
    },
  });
}

function renderTable(rows: ServiceCatalogRow[]): string {
  if (rows.length === 0) {
    return '_No rows in this bucket._';
  }
  // "Legacy promo until" → the V1 16-SKU launch-promo window retired
  // 2026-05-28 V2 cutover (replaced by 100 complimentary vendor tokens
  // on verification). Column kept for historical audit on rows that still
  // carry the timestamp.
  const header =
    '| SKU | Name | Category | Price | Billing | Multi-purchase | Legacy promo until |';
  const sep =
    '|-----|------|----------|-------|---------|---------------|--------------------|';
  const lines = rows.map(
    (r) =>
      `| \`${r.sku_code}\` | ${escapeCell(r.display_name)} | ${r.category} | ${formatCentavosPhp(r.price_centavos)} | per ${r.unit} | ${r.multi_purchase ? 'yes' : 'no'} | ${r.launch_promo_until ? new Date(r.launch_promo_until).toISOString().slice(0, 10) : '—'} |`,
  );
  return [header, sep, ...lines].join('\n');
}

function escapeCell(value: string): string {
  // Markdown table cells: pipes and newlines break the row. Replace pipes
  // with a typographic alternative and collapse whitespace.
  return value.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}
