// AUTO-GENERATED by scripts/gen-admin-map.ts — do not hand-edit.
// Regenerate with: pnpm --filter @setnayan/web admin:map
//
// Every place inside /admin a person can land, scanned from the route tree.
// 98 destinations (57 real pages, 41 redirect stubs)
// as of c514a55cc. admin-map-is-generated.test.ts fails if this drifts from the tree.

import type { AdminRoute } from './scan-admin-routes';

export const ADMIN_ROUTES: readonly AdminRoute[] = [
  {
    "path": "/admin",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/account-deletions",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/accounts",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/addons",
    "kind": "redirect",
    "redirectsTo": "/admin/pricing",
    "inMenuSource": false
  },
  {
    "path": "/admin/app-performance",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/approvals",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/background-videos",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/booking-fees",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/brain",
    "kind": "redirect",
    "redirectsTo": "/admin/ugat?tab=brain",
    "inMenuSource": true
  },
  {
    "path": "/admin/budget-planner",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/chat-flags",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/completions",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/compliance",
    "kind": "redirect",
    "redirectsTo": "/admin/settings?tab=compliance",
    "inMenuSource": true
  },
  {
    "path": "/admin/compliance/data-sheet",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/concierge-abuse",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/connection-logs",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=connection-logs",
    "inMenuSource": true
  },
  {
    "path": "/admin/corrections",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/custom-plans",
    "kind": "redirect",
    "redirectsTo": "/admin/pricing?tab=custom-plans",
    "inMenuSource": true
  },
  {
    "path": "/admin/data-privacy",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/demand",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/demo-vendors",
    "kind": "redirect",
    "redirectsTo": "/admin/accounts?tab=demo-vendors",
    "inMenuSource": true
  },
  {
    "path": "/admin/demo-vendors/inquiries",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/directory",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/discount-codes",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=discount-codes",
    "inMenuSource": true
  },
  {
    "path": "/admin/discount-codes/new",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/disputes",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/editorial-review",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/event-types",
    "kind": "redirect",
    "redirectsTo": "/admin/taxonomy?view=vocab-event",
    "inMenuSource": false
  },
  {
    "path": "/admin/events",
    "kind": "redirect",
    "redirectsTo": "/admin/accounts?tab=events",
    "inMenuSource": true
  },
  {
    "path": "/admin/force-majeure",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/founder-seats",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/fraud",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/funnels",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=funnels",
    "inMenuSource": true
  },
  {
    "path": "/admin/growth",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=growth",
    "inMenuSource": true
  },
  {
    "path": "/admin/help",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/insights",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=intelligence",
    "inMenuSource": false
  },
  {
    "path": "/admin/integrations",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/integrity-watch",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/intelligence",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=intelligence",
    "inMenuSource": true
  },
  {
    "path": "/admin/journal-spotlights",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=journal-spotlights",
    "inMenuSource": true
  },
  {
    "path": "/admin/live-studio-channels",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/marketing",
    "kind": "redirect",
    "redirectsTo": "/admin/studio",
    "inMenuSource": false
  },
  {
    "path": "/admin/menus",
    "kind": "redirect",
    "redirectsTo": "/admin/ugat?tab=menus",
    "inMenuSource": true
  },
  {
    "path": "/admin/money",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/moodboard-library",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=moodboard-library",
    "inMenuSource": true
  },
  {
    "path": "/admin/more",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/notifications",
    "kind": "redirect",
    "redirectsTo": "/admin/settings?tab=notifications",
    "inMenuSource": true
  },
  {
    "path": "/admin/npc-readiness",
    "kind": "redirect",
    "redirectsTo": "/admin/data-privacy?tab=checklist",
    "inMenuSource": false
  },
  {
    "path": "/admin/offline",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=offline",
    "inMenuSource": true
  },
  {
    "path": "/admin/onboarding",
    "kind": "redirect",
    "redirectsTo": "/admin/ugat?tab=onboarding",
    "inMenuSource": true
  },
  {
    "path": "/admin/operations-hiring",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=operations",
    "inMenuSource": true
  },
  {
    "path": "/admin/pakanta",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/papic-storage",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/patiktok",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=patiktok",
    "inMenuSource": true
  },
  {
    "path": "/admin/pax-changes",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/payment-options",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/payments",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/payouts",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/price-bands",
    "kind": "redirect",
    "redirectsTo": "/admin/pricing?tab=price-bands",
    "inMenuSource": true
  },
  {
    "path": "/admin/pricing",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/queues",
    "kind": "redirect",
    "redirectsTo": "/admin/work",
    "inMenuSource": false
  },
  {
    "path": "/admin/real-stories",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=real-stories",
    "inMenuSource": true
  },
  {
    "path": "/admin/recaps",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=recaps",
    "inMenuSource": true
  },
  {
    "path": "/admin/receipts",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/referrals",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=referrals",
    "inMenuSource": true
  },
  {
    "path": "/admin/refinements",
    "kind": "redirect",
    "redirectsTo": "/admin/taxonomy",
    "inMenuSource": false
  },
  {
    "path": "/admin/repost-watch",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/reveal-studio",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=reveal-studio",
    "inMenuSource": true
  },
  {
    "path": "/admin/reviews",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/search-memory",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/secrets",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/seo",
    "kind": "redirect",
    "redirectsTo": "/admin/app-performance?tab=seo",
    "inMenuSource": true
  },
  {
    "path": "/admin/settings",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/settings/demo-mode",
    "kind": "redirect",
    "redirectsTo": "/admin/settings?tab=demo-mode",
    "inMenuSource": true
  },
  {
    "path": "/admin/settings/payment-methods",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/social-queue",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=social-queue",
    "inMenuSource": true
  },
  {
    "path": "/admin/songs",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=songs",
    "inMenuSource": true
  },
  {
    "path": "/admin/spotlight-awards",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=spotlight-awards",
    "inMenuSource": true
  },
  {
    "path": "/admin/studio",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/subscriptions",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/taxonomy",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/taxonomy/aliases",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/ugat",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/ugat/map",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/user-reports",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/users",
    "kind": "redirect",
    "redirectsTo": "/admin/accounts?tab=users",
    "inMenuSource": true
  },
  {
    "path": "/admin/vendor-partnerships",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/vendor-recommendations",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/vendors",
    "kind": "redirect",
    "redirectsTo": "/admin/accounts?tab=vendors",
    "inMenuSource": true
  },
  {
    "path": "/admin/venues",
    "kind": "redirect",
    "redirectsTo": "/admin/accounts?tab=venues",
    "inMenuSource": true
  },
  {
    "path": "/admin/venues/new",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": false
  },
  {
    "path": "/admin/verification-docs",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/verify",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/website",
    "kind": "redirect",
    "redirectsTo": "/admin/studio?tab=website",
    "inMenuSource": true
  },
  {
    "path": "/admin/website-media",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  },
  {
    "path": "/admin/wedding-traditions",
    "kind": "redirect",
    "redirectsTo": "/admin/ugat?tab=wedding-traditions",
    "inMenuSource": true
  },
  {
    "path": "/admin/wedding-types",
    "kind": "redirect",
    "redirectsTo": "/admin/taxonomy?view=vocab-faith",
    "inMenuSource": false
  },
  {
    "path": "/admin/work",
    "kind": "page",
    "redirectsTo": null,
    "inMenuSource": true
  }
];
