// AUTO-GENERATED by scripts/gen-admin-jobs.ts — do not hand-edit.
// Regenerate with: pnpm --filter @setnayan/web admin:jobs
//
// Every job the admin can perform and what it asks for, read out of the action
// that performs it. 283 jobs, 185 of them form-driven, as of d7000a62c.
// admin-jobs-are-generated.test.ts fails if this drifts from the code.

import type { AdminJob } from './scan-admin-jobs';

export const ADMIN_JOBS: readonly AdminJob[] = [
  {
    "name": "activateCustomPlan",
    "phrase": "activate custom plan",
    "ownerPath": "/admin/custom-plans",
    "resolvedPath": "/admin/custom-plans",
    "fields": [
      "vendor_profile_id",
      "custom_plan_id"
    ],
    "refusedWhenEmpty": [
      "vendor_profile_id"
    ],
    "destructive": false
  },
  {
    "name": "addAwardManually",
    "phrase": "add award manually",
    "ownerPath": "/admin/spotlight-awards",
    "resolvedPath": "/admin/spotlight-awards",
    "fields": [
      "vendor_profile_id",
      "award_type",
      "period_month"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addEligibleUser",
    "phrase": "add eligible user",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "discount_code_id",
      "email"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addExpense",
    "phrase": "add expense",
    "ownerPath": "/admin/app-performance",
    "resolvedPath": "/admin/app-performance",
    "fields": [
      "expensed_on",
      "vendor_name",
      "category",
      "amount_php",
      "note",
      "next_due_on",
      "recurs_monthly",
      "receipt"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addLeafAttributeFieldAction",
    "phrase": "add leaf attribute field",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "field_label",
      "field_type",
      "field_options"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addLeafAttributeOptionAction",
    "phrase": "add leaf attribute option",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "field_key",
      "option_label"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addRecommendation",
    "phrase": "add recommendation",
    "ownerPath": "/admin/vendor-recommendations",
    "resolvedPath": "/admin/vendor-recommendations",
    "fields": [
      "tile_id",
      "service_code",
      "is_opt_in",
      "priority",
      "rationale"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "addRefinementOption",
    "phrase": "add refinement option",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "label_en",
      "emoji",
      "photo_url"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminAcceptInquiry",
    "phrase": "admin accept inquiry",
    "ownerPath": "/admin/demo-vendors/inquiries",
    "resolvedPath": "/admin/demo-vendors/inquiries",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminClearConciergeFlag",
    "phrase": "admin clear concierge flag",
    "ownerPath": "/admin/concierge-abuse",
    "resolvedPath": "/admin/concierge-abuse",
    "fields": [
      "flag_id",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminConfirmConciergeAbuse",
    "phrase": "admin confirm concierge abuse",
    "ownerPath": "/admin/concierge-abuse",
    "resolvedPath": "/admin/concierge-abuse",
    "fields": [
      "flag_id",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminDeclineInquiry",
    "phrase": "admin decline inquiry",
    "ownerPath": "/admin/demo-vendors/inquiries",
    "resolvedPath": "/admin/demo-vendors/inquiries",
    "fields": [
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminLiftConciergeEnforcement",
    "phrase": "admin lift concierge enforcement",
    "ownerPath": "/admin/concierge-abuse",
    "resolvedPath": "/admin/concierge-abuse",
    "fields": [
      "user_id",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "adminReplyAsVendor",
    "phrase": "admin reply as vendor",
    "ownerPath": "/admin/demo-vendors/inquiries",
    "resolvedPath": "/admin/demo-vendors/inquiries",
    "fields": [
      "body"
    ],
    "refusedWhenEmpty": [
      "body"
    ],
    "destructive": false
  },
  {
    "name": "adminTakedownRecap",
    "phrase": "admin takedown recap",
    "ownerPath": "/admin/recaps",
    "resolvedPath": "/admin/recaps",
    "fields": [
      "event_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "agreeToRequestFromWorkList",
    "phrase": "agree to request from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "applyApplicationDecision",
    "phrase": "apply application decision",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "applyCorrectionRequest",
    "phrase": "apply correction request",
    "ownerPath": "/admin/corrections",
    "resolvedPath": "/admin/corrections",
    "fields": [
      "request_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveAndBlacklist",
    "phrase": "approve and blacklist",
    "ownerPath": "/admin/account-deletions",
    "resolvedPath": "/admin/account-deletions",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveAndDelete",
    "phrase": "approve and delete",
    "ownerPath": "/admin/account-deletions",
    "resolvedPath": "/admin/account-deletions",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveApplication",
    "phrase": "approve application",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveAsset",
    "phrase": "approve asset",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveFreeSpotlight",
    "phrase": "approve free spotlight",
    "ownerPath": "/admin/journal-spotlights",
    "resolvedPath": "/admin/journal-spotlights",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approvePayment",
    "phrase": "approve payment",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "payment_id",
      "admin_notes",
      "promote_order",
      "acknowledge_duplicate"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approvePaymentCore",
    "phrase": "approve payment core",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approvePaymentFromWorkList",
    "phrase": "approve payment from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "payment_id",
      "back"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approvePaymentMethod",
    "phrase": "approve payment method",
    "ownerPath": "/admin/payment-options",
    "resolvedPath": "/admin/payment-options",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveRequest",
    "phrase": "approve request",
    "ownerPath": "/admin/approvals",
    "resolvedPath": "/admin/approvals",
    "fields": [
      "approval_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveSubscription",
    "phrase": "approve subscription",
    "ownerPath": "/admin/subscriptions",
    "resolvedPath": "/admin/subscriptions",
    "fields": [
      "purchase_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveVendor",
    "phrase": "approve vendor",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "approveVerificationFromWorkList",
    "phrase": "approve verification from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "application_id",
      "back"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "archiveVendor",
    "phrase": "archive vendor",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "attachReceipt",
    "phrase": "attach receipt",
    "ownerPath": "/admin/app-performance",
    "resolvedPath": "/admin/app-performance",
    "fields": [
      "expense_id",
      "receipt"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "attachSpotlight",
    "phrase": "attach spotlight",
    "ownerPath": "/admin/journal-spotlights",
    "resolvedPath": "/admin/journal-spotlights",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "backfillTileDerivativesAction",
    "phrase": "backfill tile derivatives",
    "ownerPath": "/admin/papic-storage",
    "resolvedPath": "/admin/papic-storage",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "batchApprovePayments",
    "phrase": "batch approve payments",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "blacklistUser",
    "phrase": "blacklist user",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "clearDbSecret",
    "phrase": "clear db secret",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [
      "secret_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "clearIntegrationSecret",
    "phrase": "clear integration secret",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "integration_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "clearLastMinuteStart",
    "phrase": "clear last minute start",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "ref_key"
    ],
    "refusedWhenEmpty": [
      "ref_key"
    ],
    "destructive": true
  },
  {
    "name": "clearLeftoverMediaAction",
    "phrase": "clear leftover media",
    "ownerPath": "/admin/website-media",
    "resolvedPath": "/admin/website-media",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "clearMayaSecrets",
    "phrase": "clear maya secrets",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "clearOAuthSecret",
    "phrase": "clear o auth secret",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "oauth_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "clearResendKey",
    "phrase": "clear resend key",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "confirmOrderTotal",
    "phrase": "confirm order total",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "order_id",
      "confirmed_total_php",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "confirmSponsored",
    "phrase": "confirm sponsored",
    "ownerPath": "/admin/journal-spotlights",
    "resolvedPath": "/admin/journal-spotlights",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "confirmUserEmail",
    "phrase": "confirm user email",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "correctShopAddress",
    "phrase": "correct shop address",
    "ownerPath": "/admin/corrections",
    "resolvedPath": "/admin/corrections",
    "fields": [
      "current_slug",
      "new_slug",
      "reason"
    ],
    "refusedWhenEmpty": [
      "current_slug",
      "reason"
    ],
    "destructive": false
  },
  {
    "name": "createAdminVendorInvite",
    "phrase": "create admin vendor invite",
    "ownerPath": "/admin/vendors",
    "resolvedPath": "/admin/vendors",
    "fields": [
      "email",
      "business_name",
      "service_category"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createAnnouncement",
    "phrase": "create announcement",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createCanonicalLeaf",
    "phrase": "create canonical leaf",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "tile_id",
      "display_name_en",
      "is_rental",
      "is_ph",
      "faith",
      "refinement_label",
      "refinement_options"
    ],
    "refusedWhenEmpty": [
      "tile_id",
      "display_name_en"
    ],
    "destructive": false
  },
  {
    "name": "createDiscountCode",
    "phrase": "create discount code",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "code",
      "discount_type",
      "discount_pct",
      "cap_pesos",
      "expires_at",
      "effective_from",
      "max_uses"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createEventType",
    "phrase": "create event type",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "label_en",
      "emoji",
      "description",
      "sort_order"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createEventTypeRoster",
    "phrase": "create event type roster",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "label_en",
      "emoji",
      "description",
      "sort_order"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createEventTypeVocab",
    "phrase": "create event type vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "label_en"
    ],
    "refusedWhenEmpty": [
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "createFaithVocab",
    "phrase": "create faith vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "label_en"
    ],
    "refusedWhenEmpty": [
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "createFreeWindow",
    "phrase": "create free window",
    "ownerPath": "/admin/pricing",
    "resolvedPath": "/admin/pricing",
    "fields": [
      "audience_type",
      "title",
      "blurb",
      "starts_at",
      "ends_at",
      "promoted_vendor_tier",
      "show_banner"
    ],
    "refusedWhenEmpty": [
      "title"
    ],
    "destructive": false
  },
  {
    "name": "createPartnershipHq",
    "phrase": "create partnership hq",
    "ownerPath": "/admin/vendor-partnerships",
    "resolvedPath": "/admin/vendor-partnerships",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "createTaxonomyNode",
    "phrase": "create taxonomy node",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "parent_id",
      "label_en"
    ],
    "refusedWhenEmpty": [
      "parent_id",
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "createVenue",
    "phrase": "create venue",
    "ownerPath": "/admin/venues",
    "resolvedPath": "/admin/venues",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "declineCorrectionRequest",
    "phrase": "decline correction request",
    "ownerPath": "/admin/corrections",
    "resolvedPath": "/admin/corrections",
    "fields": [
      "request_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "deleteAsset",
    "phrase": "delete asset",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteEvent",
    "phrase": "delete event",
    "ownerPath": "/admin/events",
    "resolvedPath": "/admin/events",
    "fields": [
      "event_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteFreeWindow",
    "phrase": "delete free window",
    "ownerPath": "/admin/pricing",
    "resolvedPath": "/admin/pricing",
    "fields": [
      "promo_window_id"
    ],
    "refusedWhenEmpty": [
      "promo_window_id"
    ],
    "destructive": true
  },
  {
    "name": "deleteRecommendation",
    "phrase": "delete recommendation",
    "ownerPath": "/admin/vendor-recommendations",
    "resolvedPath": "/admin/vendor-recommendations",
    "fields": [
      "id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteSongAction",
    "phrase": "delete song",
    "ownerPath": "/admin/songs",
    "resolvedPath": "/admin/songs",
    "fields": [
      "song_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteTaxonomyNode",
    "phrase": "delete taxonomy node",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "id"
    ],
    "refusedWhenEmpty": [
      "id"
    ],
    "destructive": true
  },
  {
    "name": "deleteTileWithDestination",
    "phrase": "delete tile with destination",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteTraditionItem",
    "phrase": "delete tradition item",
    "ownerPath": "/admin/wedding-traditions",
    "resolvedPath": "/admin/wedding-traditions",
    "fields": [
      "item_id"
    ],
    "refusedWhenEmpty": [
      "item_id"
    ],
    "destructive": true
  },
  {
    "name": "deleteUser",
    "phrase": "delete user",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteVenue",
    "phrase": "delete venue",
    "ownerPath": "/admin/venues",
    "resolvedPath": "/admin/venues",
    "fields": [
      "venue_directory_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deleteVerificationDoc",
    "phrase": "delete verification doc",
    "ownerPath": "/admin/verification-docs",
    "resolvedPath": "/admin/verification-docs",
    "fields": [
      "key"
    ],
    "refusedWhenEmpty": [
      "key"
    ],
    "destructive": true
  },
  {
    "name": "deleteWebsiteMediaAction",
    "phrase": "delete website media",
    "ownerPath": "/admin/website-media",
    "resolvedPath": "/admin/website-media",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "deliverPakantaSong",
    "phrase": "deliver pakanta song",
    "ownerPath": "/admin/pakanta",
    "resolvedPath": "/admin/pakanta",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "demoteVendor",
    "phrase": "demote vendor",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "disableDiscountCode",
    "phrase": "disable discount code",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "discount_code_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "disconnectChannel",
    "phrase": "disconnect channel",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "dismissReviewFlag",
    "phrase": "dismiss review flag",
    "ownerPath": "/admin/reviews",
    "resolvedPath": "/admin/reviews",
    "fields": [
      "flag_id",
      "admin_note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "dismissVendorSignals",
    "phrase": "dismiss vendor signals",
    "ownerPath": "/admin/fraud",
    "resolvedPath": "/admin/fraud",
    "fields": [
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "enableDiscountCode",
    "phrase": "enable discount code",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "discount_code_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "escalateAppeal",
    "phrase": "escalate appeal",
    "ownerPath": "/admin/reviews",
    "resolvedPath": "/admin/reviews",
    "fields": [
      "appeal_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "executeFraudWipeBan",
    "phrase": "execute fraud wipe ban",
    "ownerPath": "/admin/fraud",
    "resolvedPath": "/admin/fraud",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "fetchUgatCounts",
    "phrase": "fetch ugat counts",
    "ownerPath": "/admin/ugat",
    "resolvedPath": "/admin/ugat",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "fetchUgatSavedSearch",
    "phrase": "fetch ugat saved search",
    "ownerPath": "/admin/ugat",
    "resolvedPath": "/admin/ugat",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "fetchUgatSearch",
    "phrase": "fetch ugat search",
    "ownerPath": "/admin/ugat",
    "resolvedPath": "/admin/ugat",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "fetchUgatTable",
    "phrase": "fetch ugat table",
    "ownerPath": "/admin/ugat",
    "resolvedPath": "/admin/ugat",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "forceCompleteVendor",
    "phrase": "force complete vendor",
    "ownerPath": "/admin/completions",
    "resolvedPath": "/admin/completions",
    "fields": [
      "event_id",
      "vendor_id",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "forceSignOutUser",
    "phrase": "force sign out user",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "getDeepSearchChatPromptAction",
    "phrase": "get deep search chat prompt",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "getDownloadUrlAction",
    "phrase": "get download url",
    "ownerPath": "/admin/website-media",
    "resolvedPath": "/admin/website-media",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "getRandomHiggsfieldPrompt",
    "phrase": "get random higgsfield prompt",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "getVendorStudyPromptAction",
    "phrase": "get vendor study prompt",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "grantFounderSeat",
    "phrase": "grant founder seat",
    "ownerPath": "/admin/founder-seats",
    "resolvedPath": "/admin/founder-seats",
    "fields": [
      "email",
      "label"
    ],
    "refusedWhenEmpty": [
      "email"
    ],
    "destructive": false
  },
  {
    "name": "holdPaymentMethod",
    "phrase": "hold payment method",
    "ownerPath": "/admin/payment-options",
    "resolvedPath": "/admin/payment-options",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "holdPayoutAction",
    "phrase": "hold payout",
    "ownerPath": "/admin/payouts",
    "resolvedPath": "/admin/payouts",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "initiateFraudWipeBan",
    "phrase": "initiate fraud wipe ban",
    "ownerPath": "/admin/fraud",
    "resolvedPath": "/admin/fraud",
    "fields": [
      "confirm_name",
      "rationale"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "initiateSponsored",
    "phrase": "initiate sponsored",
    "ownerPath": "/admin/journal-spotlights",
    "resolvedPath": "/admin/journal-spotlights",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "issueCompGrant",
    "phrase": "issue comp grant",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id",
      "scope",
      "expiry_at",
      "retail_value_php",
      "rationale"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "mapCategoryRequest",
    "phrase": "map category request",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "request_id",
      "mapped_to_canonical"
    ],
    "refusedWhenEmpty": [
      "request_id"
    ],
    "destructive": false
  },
  {
    "name": "markConsentPosted",
    "phrase": "mark consent posted",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "markConsentTakenDown",
    "phrase": "mark consent taken down",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "markPayoutPaidAction",
    "phrase": "mark payout paid",
    "ownerPath": "/admin/payouts",
    "resolvedPath": "/admin/payouts",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "markRotated",
    "phrase": "mark rotated",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [
      "secret_id",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "markVendorContactConfirmed",
    "phrase": "mark vendor contact confirmed",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "markVendorFeatured",
    "phrase": "mark vendor featured",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "mergeSongsAction",
    "phrase": "merge songs",
    "ownerPath": "/admin/songs",
    "resolvedPath": "/admin/songs",
    "fields": [
      "dup_id",
      "canonical_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "moveTaxonomyNode",
    "phrase": "move taxonomy node",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "id",
      "direction"
    ],
    "refusedWhenEmpty": [
      "id"
    ],
    "destructive": false
  },
  {
    "name": "moveTileToFolder",
    "phrase": "move tile to folder",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "overridePublishReview",
    "phrase": "override publish review",
    "ownerPath": "/admin/reviews",
    "resolvedPath": "/admin/reviews",
    "fields": [
      "appeal_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "postSocialPostNow",
    "phrase": "post social post now",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "promoteCategoryRequest",
    "phrase": "promote category request",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "request_id",
      "tile_id"
    ],
    "refusedWhenEmpty": [
      "request_id"
    ],
    "destructive": false
  },
  {
    "name": "publishReviewFromWorkList",
    "phrase": "publish review from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "back"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "pullSocialPost",
    "phrase": "pull social post",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "recomputePriceBands",
    "phrase": "recompute price bands",
    "ownerPath": "/admin/price-bands",
    "resolvedPath": "/admin/price-bands",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "recomputeSpotlightAwards",
    "phrase": "recompute spotlight awards",
    "ownerPath": "/admin/spotlight-awards",
    "resolvedPath": "/admin/spotlight-awards",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "recordPayoutFromWorkList",
    "phrase": "record payout from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "redeployProduction",
    "phrase": "redeploy production",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "refundOrder",
    "phrase": "refund order",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "order_id",
      "reason",
      "proof_url",
      "refund_amount_php"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rejectAppeal",
    "phrase": "reject appeal",
    "ownerPath": "/admin/reviews",
    "resolvedPath": "/admin/reviews",
    "fields": [
      "appeal_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectApplication",
    "phrase": "reject application",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectPartnership",
    "phrase": "reject partnership",
    "ownerPath": "/admin/vendor-partnerships",
    "resolvedPath": "/admin/vendor-partnerships",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectPayment",
    "phrase": "reject payment",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "payment_id",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectRequest",
    "phrase": "reject request",
    "ownerPath": "/admin/account-deletions",
    "resolvedPath": "/admin/account-deletions",
    "fields": [
      "request_id",
      "admin_note"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectRequest",
    "phrase": "reject request",
    "ownerPath": "/admin/approvals",
    "resolvedPath": "/admin/approvals",
    "fields": [
      "approval_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectSubscription",
    "phrase": "reject subscription",
    "ownerPath": "/admin/subscriptions",
    "resolvedPath": "/admin/subscriptions",
    "fields": [
      "purchase_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "rejectVendor",
    "phrase": "reject vendor",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "relabelEventTypeVocab",
    "phrase": "relabel event type vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "label_en"
    ],
    "refusedWhenEmpty": [
      "event_type",
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "relabelFaithVocab",
    "phrase": "relabel faith vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "faith_key",
      "label_en"
    ],
    "refusedWhenEmpty": [
      "faith_key",
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "relabelLeafAttributeFieldAction",
    "phrase": "relabel leaf attribute field",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "field_key",
      "field_label"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "releaseChannel",
    "phrase": "release channel",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "releasePayoutHoldAction",
    "phrase": "release payout hold",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "payout_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "remapCanonical",
    "phrase": "remap canonical",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "canonical_service",
      "tile_id",
      "_view"
    ],
    "refusedWhenEmpty": [
      "canonical_service"
    ],
    "destructive": false
  },
  {
    "name": "removeAward",
    "phrase": "remove award",
    "ownerPath": "/admin/spotlight-awards",
    "resolvedPath": "/admin/spotlight-awards",
    "fields": [
      "award_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removeBrandIcon",
    "phrase": "remove brand icon",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removeEligibleUser",
    "phrase": "remove eligible user",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "discount_code_id",
      "user_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removeMerchantQr",
    "phrase": "remove merchant qr",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "kind"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removePaymentMethod",
    "phrase": "remove payment method",
    "ownerPath": "/admin/payment-options",
    "resolvedPath": "/admin/payment-options",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removeRefinementOption",
    "phrase": "remove refinement option",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "removeSpotlight",
    "phrase": "remove spotlight",
    "ownerPath": "/admin/journal-spotlights",
    "resolvedPath": "/admin/journal-spotlights",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "renameTaxonomyNode",
    "phrase": "rename taxonomy node",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "id",
      "label_en"
    ],
    "refusedWhenEmpty": [
      "id",
      "label_en"
    ],
    "destructive": false
  },
  {
    "name": "reorderCategories",
    "phrase": "reorder categories",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "reorderEventTypeVocab",
    "phrase": "reorder event type vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "dir"
    ],
    "refusedWhenEmpty": [
      "event_type"
    ],
    "destructive": false
  },
  {
    "name": "reorderFaithVocab",
    "phrase": "reorder faith vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "faith_key",
      "dir"
    ],
    "refusedWhenEmpty": [
      "faith_key"
    ],
    "destructive": false
  },
  {
    "name": "reorderRefinementLeaves",
    "phrase": "reorder refinement leaves",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "reorderRefinementOptions",
    "phrase": "reorder refinement options",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "requestPaymentResubmit",
    "phrase": "request payment resubmit",
    "ownerPath": "/admin/payments",
    "resolvedPath": "/admin/payments",
    "fields": [
      "payment_id",
      "admin_resubmit_notice"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "requestPrivilegedGrant",
    "phrase": "request privileged grant",
    "ownerPath": "/admin/approvals",
    "resolvedPath": "/admin/approvals",
    "fields": [
      "action_type",
      "target_email",
      "rationale"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rerunSeoAudit",
    "phrase": "rerun seo audit",
    "ownerPath": "/admin/app-performance",
    "resolvedPath": "/admin/app-performance",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rescanAllRepostWatch",
    "phrase": "rescan all repost watch",
    "ownerPath": "/admin/repost-watch",
    "resolvedPath": "/admin/repost-watch",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rescanGhostListings",
    "phrase": "rescan ghost listings",
    "ownerPath": "/admin/integrity-watch",
    "resolvedPath": "/admin/integrity-watch",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rescanReviewsForFraud",
    "phrase": "rescan reviews for fraud",
    "ownerPath": "/admin/integrity-watch",
    "resolvedPath": "/admin/integrity-watch",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "rescanUnderDeclaredLocks",
    "phrase": "rescan under declared locks",
    "ownerPath": "/admin/integrity-watch",
    "resolvedPath": "/admin/integrity-watch",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resetOnboardingSpec",
    "phrase": "reset onboarding spec",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resetSlot",
    "phrase": "reset slot",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resetTraditionsToDefaults",
    "phrase": "reset traditions to defaults",
    "ownerPath": "/admin/wedding-traditions",
    "resolvedPath": "/admin/wedding-traditions",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resetUserPassword",
    "phrase": "reset user password",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveAllActive",
    "phrase": "resolve all active",
    "ownerPath": "/admin/connection-logs",
    "resolvedPath": "/admin/connection-logs",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveCategoryRequest",
    "phrase": "resolve category request",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "request_id",
      "outcome",
      "resolution_note"
    ],
    "refusedWhenEmpty": [
      "request_id"
    ],
    "destructive": false
  },
  {
    "name": "resolveChatFlag",
    "phrase": "resolve chat flag",
    "ownerPath": "/admin/chat-flags",
    "resolvedPath": "/admin/chat-flags",
    "fields": [
      "flag_id",
      "action"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveDispute",
    "phrase": "resolve dispute",
    "ownerPath": "/admin/disputes",
    "resolvedPath": "/admin/disputes",
    "fields": [
      "dispute_id",
      "resolution",
      "resolution_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveFeedback",
    "phrase": "resolve feedback",
    "ownerPath": "/admin/vendor-recommendations",
    "resolvedPath": "/admin/vendor-recommendations",
    "fields": [
      "id",
      "decision"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveFlag",
    "phrase": "resolve flag",
    "ownerPath": "/admin/editorial-review/[editorialId]",
    "resolvedPath": "/admin/editorial-review",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveFlag",
    "phrase": "resolve flag",
    "ownerPath": "/admin/force-majeure",
    "resolvedPath": "/admin/force-majeure",
    "fields": [
      "flag_id",
      "action",
      "resolution_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveIntegrityFlag",
    "phrase": "resolve integrity flag",
    "ownerPath": "/admin/integrity-watch",
    "resolvedPath": "/admin/integrity-watch",
    "fields": [
      "flag_id",
      "action",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveQrMediaFlag",
    "phrase": "resolve qr media flag",
    "ownerPath": "/admin/repost-watch",
    "resolvedPath": "/admin/repost-watch",
    "fields": [
      "flag_id",
      "action",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveReport",
    "phrase": "resolve report",
    "ownerPath": "/admin/user-reports",
    "resolvedPath": "/admin/user-reports",
    "fields": [
      "report_id",
      "action"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "resolveRepostFlag",
    "phrase": "resolve repost flag",
    "ownerPath": "/admin/repost-watch",
    "resolvedPath": "/admin/repost-watch",
    "fields": [
      "flag_id",
      "action",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "retireAsset",
    "phrase": "retire asset",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "retireEventType",
    "phrase": "retire event type",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "retireEventTypeVocab",
    "phrase": "retire event type vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "retireLeafAttributeFieldAction",
    "phrase": "retire leaf attribute field",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "field_key",
      "retired"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "retireLeafAttributeOptionAction",
    "phrase": "retire leaf attribute option",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "field_key",
      "option",
      "retired"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "retrySocialPost",
    "phrase": "retry social post",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "revokeAdminVendorInvite",
    "phrase": "revoke admin vendor invite",
    "ownerPath": "/admin/vendors",
    "resolvedPath": "/admin/vendors",
    "fields": [
      "invite_id"
    ],
    "refusedWhenEmpty": [
      "invite_id"
    ],
    "destructive": true
  },
  {
    "name": "revokeCompGrant",
    "phrase": "revoke comp grant",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "grant_id",
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "revokeFounderSeat",
    "phrase": "revoke founder seat",
    "ownerPath": "/admin/founder-seats",
    "resolvedPath": "/admin/founder-seats",
    "fields": [
      "seat_no"
    ],
    "refusedWhenEmpty": [],
    "destructive": true
  },
  {
    "name": "runDemandRadarRefresh",
    "phrase": "run demand radar refresh",
    "ownerPath": "/admin/demand",
    "resolvedPath": "/admin/demand",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "runReencryptSweep",
    "phrase": "run reencrypt sweep",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "runVendorDeepSearchAction",
    "phrase": "run vendor deep search",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveAdminDigest",
    "phrase": "save admin digest",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "admin_digest_enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveAllPricing",
    "phrase": "save all pricing",
    "ownerPath": "/admin/pricing",
    "resolvedPath": "/admin/pricing",
    "fields": [
      "setnayan_pay_fee_pct"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveBackgroundVideo",
    "phrase": "save background video",
    "ownerPath": "/admin/background-videos",
    "resolvedPath": "/admin/background-videos",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveBusinessIdentity",
    "phrase": "save business identity",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "default_vat_rate_pct",
      "repost_watch_hamming_threshold",
      "business_name",
      "business_tin",
      "business_address",
      "business_email",
      "vendor_validate_email",
      "vendor_validate_phone"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveColorRanges",
    "phrase": "save color ranges",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveComplianceFacts",
    "phrase": "save compliance facts",
    "ownerPath": "/admin/compliance",
    "resolvedPath": "/admin/compliance",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveEvergreenItem",
    "phrase": "save evergreen item",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [
      "is_active"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveIntegrationSecret",
    "phrase": "save integration secret",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "integration_id",
      "secret"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveLoaderAppearance",
    "phrase": "save loader appearance",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "loader_variant",
      "loader_veil_opacity",
      "loader_step_interval_ms",
      "loader_pop_enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveManualDossierAction",
    "phrase": "save manual dossier",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveMayaConfig",
    "phrase": "save maya config",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "maya_checkout_endpoint",
      "maya_public_api_key",
      "maya_secret_api_key"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveOAuthConfig",
    "phrase": "save o auth config",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "oauth_id",
      "client_secret"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "savePaymentInstruments",
    "phrase": "save payment instruments",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "bdo_account_name",
      "bdo_account_number",
      "gcash_account_name",
      "gcash_number",
      "gcash_enabled",
      "bdo_enabled",
      "gcash_monthly_cap_php",
      "bdo_monthly_cap_php"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveResendConfig",
    "phrase": "save resend config",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "resend_from_address",
      "resend_api_key"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveRevealStudio",
    "phrase": "save reveal studio",
    "ownerPath": "/admin/reveal-studio",
    "resolvedPath": "/admin/reveal-studio",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "saveUnclaimedVendorProfile",
    "phrase": "save unclaimed vendor profile",
    "ownerPath": "/admin/vendors",
    "resolvedPath": "/admin/vendors",
    "fields": [
      "vendor_profile_id",
      "business_name",
      "tagline",
      "location_city",
      "hq_address",
      "contact_email",
      "contact_phone",
      "services",
      "is_published"
    ],
    "refusedWhenEmpty": [
      "vendor_profile_id"
    ],
    "destructive": false
  },
  {
    "name": "scanQrMediaGuard",
    "phrase": "scan qr media guard",
    "ownerPath": "/admin/repost-watch",
    "resolvedPath": "/admin/repost-watch",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "sealStdVideoForReview",
    "phrase": "seal std video for review",
    "ownerPath": "/admin/reveal-studio",
    "resolvedPath": "/admin/reveal-studio",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "seedTraditionsFromDefaults",
    "phrase": "seed traditions from defaults",
    "ownerPath": "/admin/wedding-traditions",
    "resolvedPath": "/admin/wedding-traditions",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "sendCustomQuote",
    "phrase": "send custom quote",
    "ownerPath": "/admin/custom-plans",
    "resolvedPath": "/admin/custom-plans",
    "fields": [
      "vendor_profile_id",
      "channel"
    ],
    "refusedWhenEmpty": [
      "vendor_profile_id"
    ],
    "destructive": false
  },
  {
    "name": "setAiPaywall",
    "phrase": "set ai paywall",
    "ownerPath": "/admin/integrations",
    "resolvedPath": "/admin/integrations",
    "fields": [
      "mode"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setApplicationInReview",
    "phrase": "set application in review",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setCategoryEventTypes",
    "phrase": "set category event types",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "category_id"
    ],
    "refusedWhenEmpty": [
      "category_id"
    ],
    "destructive": false
  },
  {
    "name": "setCategoryHidden",
    "phrase": "set category hidden",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "category_id",
      "hidden"
    ],
    "refusedWhenEmpty": [
      "category_id"
    ],
    "destructive": false
  },
  {
    "name": "setCategoryIcon",
    "phrase": "set category icon",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "category_id",
      "icon_name"
    ],
    "refusedWhenEmpty": [
      "category_id"
    ],
    "destructive": false
  },
  {
    "name": "setCategoryPhoto",
    "phrase": "set category photo",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "category_id",
      "photo_ref"
    ],
    "refusedWhenEmpty": [
      "category_id"
    ],
    "destructive": false
  },
  {
    "name": "setChannelCap",
    "phrase": "set channel cap",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [
      "concurrent_cap"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setChannelLabel",
    "phrase": "set channel label",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [
      "label"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setChannelStatus",
    "phrase": "set channel status",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [
      "status"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setChannelVerified",
    "phrase": "set channel verified",
    "ownerPath": "/admin/live-studio-channels",
    "resolvedPath": "/admin/live-studio-channels",
    "fields": [
      "verified"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setChapterFeatured",
    "phrase": "set chapter featured",
    "ownerPath": "/admin/storytellers",
    "resolvedPath": "/admin/studio",
    "fields": [
      "public_id",
      "feature"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setChapterRank",
    "phrase": "set chapter rank",
    "ownerPath": "/admin/storytellers",
    "resolvedPath": "/admin/studio",
    "fields": [
      "public_id",
      "rank"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setDataPrivacyControl",
    "phrase": "set data privacy control",
    "ownerPath": "/admin/data-privacy",
    "resolvedPath": "/admin/data-privacy",
    "fields": [
      "control_key",
      "status",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setEventFaceMode",
    "phrase": "set event face mode",
    "ownerPath": "/admin/events",
    "resolvedPath": "/admin/events",
    "fields": [
      "event_id",
      "face_mode"
    ],
    "refusedWhenEmpty": [
      "event_id"
    ],
    "destructive": false
  },
  {
    "name": "setEventTypeEnabled",
    "phrase": "set event type enabled",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setEventTypeLaunch",
    "phrase": "set event type launch",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setEventTypeVocabStatus",
    "phrase": "set event type vocab status",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "active"
    ],
    "refusedWhenEmpty": [
      "event_type"
    ],
    "destructive": false
  },
  {
    "name": "setFaithLaunchStatus",
    "phrase": "set faith launch status",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "faith_key",
      "status"
    ],
    "refusedWhenEmpty": [
      "faith_key"
    ],
    "destructive": false
  },
  {
    "name": "setFaithLaunchThreshold",
    "phrase": "set faith launch threshold",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "faith_key",
      "threshold"
    ],
    "refusedWhenEmpty": [
      "faith_key"
    ],
    "destructive": false
  },
  {
    "name": "setFaithVocabStatus",
    "phrase": "set faith vocab status",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "faith_key",
      "active"
    ],
    "refusedWhenEmpty": [
      "faith_key"
    ],
    "destructive": false
  },
  {
    "name": "setFolderEventTypeOffered",
    "phrase": "set folder event type offered",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "folder_id",
      "offered"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setFolderEventTypes",
    "phrase": "set folder event types",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "parent_id",
      "confirm_overwrite",
      "scope_mode"
    ],
    "refusedWhenEmpty": [
      "parent_id"
    ],
    "destructive": false
  },
  {
    "name": "setFreeWindowActive",
    "phrase": "set free window active",
    "ownerPath": "/admin/pricing",
    "resolvedPath": "/admin/pricing",
    "fields": [
      "promo_window_id",
      "is_active"
    ],
    "refusedWhenEmpty": [
      "promo_window_id"
    ],
    "destructive": false
  },
  {
    "name": "setHelpMessageStatus",
    "phrase": "set help message status",
    "ownerPath": "/admin/help",
    "resolvedPath": "/admin/help",
    "fields": [
      "message_id",
      "status",
      "admin_notes"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setLastMinuteStart",
    "phrase": "set last minute start",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "ref_key",
      "label",
      "months"
    ],
    "refusedWhenEmpty": [
      "ref_key"
    ],
    "destructive": false
  },
  {
    "name": "setLogStatus",
    "phrase": "set log status",
    "ownerPath": "/admin/connection-logs",
    "resolvedPath": "/admin/connection-logs",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setNpcFilingTask",
    "phrase": "set npc filing task",
    "ownerPath": "/admin/npc-readiness",
    "resolvedPath": "/admin/npc-readiness",
    "fields": [
      "task_key",
      "status",
      "note",
      "evidence"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setReferralProgramEnabled",
    "phrase": "set referral program enabled",
    "ownerPath": "/admin/referrals",
    "resolvedPath": "/admin/referrals",
    "fields": [
      "referral_program_enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setServiceFaith",
    "phrase": "set service faith",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "canonical_service",
      "faith"
    ],
    "refusedWhenEmpty": [
      "canonical_service"
    ],
    "destructive": false
  },
  {
    "name": "setServiceFlag",
    "phrase": "set service flag",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "canonical_service",
      "flag",
      "value"
    ],
    "refusedWhenEmpty": [
      "canonical_service"
    ],
    "destructive": false
  },
  {
    "name": "setServiceSecondaryTiles",
    "phrase": "set service secondary tiles",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "canonical_service"
    ],
    "refusedWhenEmpty": [
      "canonical_service"
    ],
    "destructive": false
  },
  {
    "name": "setShowcaseFeatured",
    "phrase": "set showcase featured",
    "ownerPath": "/admin/real-stories",
    "resolvedPath": "/admin/real-stories",
    "fields": [
      "event_id",
      "feature"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setShowcaseRank",
    "phrase": "set showcase rank",
    "ownerPath": "/admin/real-stories",
    "resolvedPath": "/admin/real-stories",
    "fields": [
      "event_id",
      "rank"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setSlotHidden",
    "phrase": "set slot hidden",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setSlotLabel",
    "phrase": "set slot label",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setSlotLucideIcon",
    "phrase": "set slot lucide icon",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setSlotNoIcon",
    "phrase": "set slot no icon",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setSongCuratedAction",
    "phrase": "set song curated",
    "ownerPath": "/admin/songs",
    "resolvedPath": "/admin/songs",
    "fields": [
      "song_id",
      "curated"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setStdVideoModeration",
    "phrase": "set std video moderation",
    "ownerPath": "/admin/reveal-studio",
    "resolvedPath": "/admin/reveal-studio",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setTileEventTypeOffered",
    "phrase": "set tile event type offered",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "tile_id",
      "offered"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "settleChatFlagFromWorkList",
    "phrase": "settle chat flag from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "back"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "settleCorrectionFromWorkList",
    "phrase": "settle correction from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "decision"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "settleHelpFromWorkList",
    "phrase": "settle help from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "back"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "settlePaymentOptionFromWorkList",
    "phrase": "settle payment option from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "decision"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "settleSubscriptionFromWorkList",
    "phrase": "settle subscription from work list",
    "ownerPath": "/admin/work",
    "resolvedPath": "/admin/work",
    "fields": [
      "decision"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setVendorFoundingSupplier",
    "phrase": "set vendor founding supplier",
    "ownerPath": "/admin/vendors",
    "resolvedPath": "/admin/vendors",
    "fields": [
      "vendor_id",
      "is_founder"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "setVendorTier",
    "phrase": "set vendor tier",
    "ownerPath": "/admin/vendors",
    "resolvedPath": "/admin/vendors",
    "fields": [
      "vendor_id",
      "tier_state",
      "tier_expires_at"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "takeOwnership",
    "phrase": "take ownership",
    "ownerPath": "/admin/force-majeure",
    "resolvedPath": "/admin/force-majeure",
    "fields": [
      "flag_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "toggleBackgroundVideoPublish",
    "phrase": "toggle background video publish",
    "ownerPath": "/admin/background-videos",
    "resolvedPath": "/admin/background-videos",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "toggleHomepageFeatured",
    "phrase": "toggle homepage featured",
    "ownerPath": "/admin/spotlight-awards",
    "resolvedPath": "/admin/spotlight-awards",
    "fields": [
      "award_id",
      "next"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "toggleTeamMember",
    "phrase": "toggle team member",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "user_id",
      "desired"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "triggerRescan",
    "phrase": "trigger rescan",
    "ownerPath": "/admin/editorial-review/[editorialId]",
    "resolvedPath": "/admin/editorial-review",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "unblacklistEmail",
    "phrase": "unblacklist email",
    "ownerPath": "/admin/users",
    "resolvedPath": "/admin/users",
    "fields": [
      "blacklist_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "unlockForCouple",
    "phrase": "unlock for couple",
    "ownerPath": "/admin/editorial-review/[editorialId]",
    "resolvedPath": "/admin/editorial-review",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "unretireEventType",
    "phrase": "unretire event type",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "unretireEventTypeVocab",
    "phrase": "unretire event type vocab",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "unsuspendVendor",
    "phrase": "unsuspend vendor",
    "ownerPath": "/admin/fraud",
    "resolvedPath": "/admin/fraud",
    "fields": [
      "reason"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateAllocationConfig",
    "phrase": "update allocation config",
    "ownerPath": "/admin/budget-planner",
    "resolvedPath": "/admin/budget-planner",
    "fields": [
      "min_sample_n",
      "high_confidence_n",
      "med_confidence_n",
      "band_pct",
      "surplus_mode"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateBudgetBand",
    "phrase": "update budget band",
    "ownerPath": "/admin/budget-planner",
    "resolvedPath": "/admin/budget-planner",
    "fields": [
      "band_slug",
      "label",
      "tag",
      "per_head_median_pesos",
      "is_active"
    ],
    "refusedWhenEmpty": [
      "band_slug",
      "label"
    ],
    "destructive": false
  },
  {
    "name": "updateDbSecret",
    "phrase": "update db secret",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [
      "secret_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateDiscountCode",
    "phrase": "update discount code",
    "ownerPath": "/admin/discount-codes",
    "resolvedPath": "/admin/discount-codes",
    "fields": [
      "discount_code_id",
      "discount_type",
      "discount_pct",
      "cap_pesos",
      "expires_at",
      "effective_from",
      "max_uses"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateEventType",
    "phrase": "update event type",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "label_en",
      "emoji",
      "description",
      "onboarding_href",
      "hero_photo_url",
      "sort_order"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateEventTypePresentation",
    "phrase": "update event type presentation",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "event_type",
      "label_en",
      "emoji",
      "description",
      "onboarding_href",
      "hero_photo_url",
      "sort_order"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateLeafBenchmark",
    "phrase": "update leaf benchmark",
    "ownerPath": "/admin/budget-planner",
    "resolvedPath": "/admin/budget-planner",
    "fields": [
      "plan_group_id",
      "benchmark_php",
      "floor_php",
      "p25_php",
      "p75_php",
      "is_active"
    ],
    "refusedWhenEmpty": [
      "plan_group_id"
    ],
    "destructive": false
  },
  {
    "name": "updateOnboardingMusic",
    "phrase": "update onboarding music",
    "ownerPath": "/admin/onboarding",
    "resolvedPath": "/admin/onboarding",
    "fields": [
      "onboarding_bg_music_enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updatePlanningDeadline",
    "phrase": "update planning deadline",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "deadline_id",
      "offset_value",
      "offset_unit"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updatePublishSettings",
    "phrase": "update publish settings",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [
      "autopublish_enabled",
      "facebook_enabled",
      "instagram_enabled",
      "tiktok_enabled"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateRecommendation",
    "phrase": "update recommendation",
    "ownerPath": "/admin/vendor-recommendations",
    "resolvedPath": "/admin/vendor-recommendations",
    "fields": [
      "id",
      "is_opt_in",
      "is_active",
      "priority",
      "rationale"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateRefinementLeaf",
    "phrase": "update refinement leaf",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "label_en",
      "description_en",
      "main_photo_url",
      "main_photo_current",
      "status"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateRefinementOption",
    "phrase": "update refinement option",
    "ownerPath": "/admin/taxonomy",
    "resolvedPath": "/admin/taxonomy",
    "fields": [
      "emoji",
      "label_en",
      "photo_url",
      "photo_current",
      "status"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateSocialPostBody",
    "phrase": "update social post body",
    "ownerPath": "/admin/social-queue",
    "resolvedPath": "/admin/social-queue",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateVenue",
    "phrase": "update venue",
    "ownerPath": "/admin/venues",
    "resolvedPath": "/admin/venues",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "updateVercelSecret",
    "phrase": "update vercel secret",
    "ownerPath": "/admin/secrets",
    "resolvedPath": "/admin/secrets",
    "fields": [
      "secret_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "upholdNonDelivery",
    "phrase": "uphold non delivery",
    "ownerPath": "/admin/completions",
    "resolvedPath": "/admin/completions",
    "fields": [
      "event_id",
      "vendor_id",
      "note"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "uploadAsset",
    "phrase": "upload asset",
    "ownerPath": "/admin/moodboard-library",
    "resolvedPath": "/admin/moodboard-library",
    "fields": [
      "file",
      "label",
      "assetType",
      "assetSubtype",
      "source"
    ],
    "refusedWhenEmpty": [
      "label"
    ],
    "destructive": false
  },
  {
    "name": "uploadBrandIcon",
    "phrase": "upload brand icon",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "file"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "uploadMerchantQr",
    "phrase": "upload merchant qr",
    "ownerPath": "/admin/settings",
    "resolvedPath": "/admin/settings",
    "fields": [
      "kind",
      "file"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "uploadSlotIcon",
    "phrase": "upload slot icon",
    "ownerPath": "/admin/menus",
    "resolvedPath": "/admin/menus",
    "fields": [
      "slot_key",
      "file"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "upsertEventTypeProfile",
    "phrase": "upsert event type profile",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "organizer_noun",
      "person_a",
      "person_b",
      "seat_word",
      "event_word",
      "vip_tier_label",
      "onboarding_flow_key",
      "role_set_key"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "upsertOnboardingSpec",
    "phrase": "upsert onboarding spec",
    "ownerPath": "/admin/event-types",
    "resolvedPath": "/admin/event-types",
    "fields": [
      "event_type",
      "spec_json"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "upsertTraditionItem",
    "phrase": "upsert tradition item",
    "ownerPath": "/admin/wedding-traditions",
    "resolvedPath": "/admin/wedding-traditions",
    "fields": [
      "item_id",
      "ceremony_type",
      "dimension",
      "label",
      "note",
      "sort_order",
      "is_active"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "verifyVendorExperience",
    "phrase": "verify vendor experience",
    "ownerPath": "/admin/verify",
    "resolvedPath": "/admin/verify",
    "fields": [],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "viewReceipt",
    "phrase": "view receipt",
    "ownerPath": "/admin/app-performance",
    "resolvedPath": "/admin/app-performance",
    "fields": [
      "expense_id"
    ],
    "refusedWhenEmpty": [],
    "destructive": false
  },
  {
    "name": "viewVerificationDoc",
    "phrase": "view verification doc",
    "ownerPath": "/admin/verification-docs",
    "resolvedPath": "/admin/verification-docs",
    "fields": [
      "key"
    ],
    "refusedWhenEmpty": [
      "key"
    ],
    "destructive": false
  }
];
