// Ugat Studio surface — the SCREENS layer of the Ugat map (slice 1 · 2026-10-02).
//
// Owner, DECISION_LOG 2026-10-02 "ONE MAP OF THE APP": every page of the host,
// guest and supplier apps, the ways in to each one, and its Ugat node — viewable
// as a "Screens" layer in Admin › Set up. EXTENDS the map, never a fourth one:
// the nodes are the entity map's own UGAT_TYPES, and admin pages stay in the
// admin map (lib/admin-map/admin-routes.generated.ts).
//
// Server component reading the COMMITTED generated file — no database read, no
// client JS, no server action. The file is regenerated by
// `pnpm --filter @setnayan/web ugat:screens` and CI refuses it stale
// (scripts/check-ugat-screens.mjs), so what this page shows is the code as merged.
import { PageMasthead } from '@/app/_components/page-masthead';
import { UGAT_TYPE_BY_ID } from '@/lib/ugat/graph';
import {
  SCREEN_AREA_LABEL,
  connectingDoors,
  screensByArea,
  summarizeScreens,
  type UgatScreen,
  type UgatScreensMap,
} from '@/lib/ugat/screens';
import generated from '@/lib/ugat/screens.generated.json';

const MAP = generated as unknown as UgatScreensMap;

function Badge({ tone, children }: { tone: 'ok' | 'warn' | 'muted'; children: string }) {
  const cls =
    tone === 'ok'
      ? 'bg-[var(--sn-info-soft)] text-[color:var(--sn-info)]'
      : tone === 'warn'
        ? 'bg-warn-50 text-warn-900'
        : 'bg-ink/5 text-ink/55';
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.1em] ${cls}`}
    >
      {children}
    </span>
  );
}

function statusBadge(s: UgatScreen) {
  if (s.status === 'stub') return <Badge tone="muted">legacy stub</Badge>;
  if (s.status === 'no-door') return <Badge tone="warn">no door</Badge>;
  return <Badge tone="ok">connected</Badge>;
}

function ScreenRow({ s }: { s: UgatScreen }) {
  const doors = connectingDoors(s);
  const phone = doors.filter((d) => d.surface === 'phone').length;
  const desktop = doors.filter((d) => d.surface === 'desktop').length;
  return (
    <li className="flex flex-col gap-1 border-t border-ink/10 py-2.5 sm:flex-row sm:items-start sm:gap-4">
      <div className="min-w-0 flex-1">
        <p className="break-all font-mono text-[13px] text-ink">{s.route}</p>
        <p className="mt-0.5 text-xs text-ink/55">
          {s.status === 'stub'
            ? `forwards to ${s.redirectsTo ?? 'another page'}`
            : doors.length === 0
              ? s.doors.length
                ? `only reached from ${[...new Set(s.doors.map((d) => d.kind))].join(', ')}`
                : 'no way in found in the code'
              : `${doors.length} way${doors.length === 1 ? '' : 's'} in` +
                (phone || desktop ? ` · ${phone} phone menu · ${desktop} desktop menu` : '')}
        </p>
      </div>
      <div className="flex shrink-0 flex-wrap items-center gap-1.5">
        {statusBadge(s)}
        {s.status !== 'stub' && s.nodes.length === 0 ? <Badge tone="warn">unmapped</Badge> : null}
        {s.nodes.slice(0, 4).map((n) => (
          <Badge key={n} tone="muted">
            {UGAT_TYPE_BY_ID[n]?.name ?? n}
          </Badge>
        ))}
        {s.nodes.length > 4 ? <Badge tone="muted">{`+${s.nodes.length - 4}`}</Badge> : null}
      </div>
    </li>
  );
}

export function ScreensSurface() {
  const sum = summarizeScreens(MAP);
  const stats: Array<{ label: string; value: number; warn?: boolean }> = [
    { label: 'Screens', value: sum.screens },
    { label: 'Connected', value: sum.connected },
    { label: 'No door', value: sum.noDoor, warn: sum.noDoor > 0 },
    { label: 'Doors to nowhere', value: sum.brokenDoors, warn: sum.brokenDoors > 0 },
    { label: 'Unmapped', value: sum.unmapped },
    { label: 'Legacy stubs', value: sum.stubs },
  ];

  return (
    <div className="mx-auto w-full max-w-5xl">
      <PageMasthead title="Screens" />
      <p className="mb-6 mt-1 max-w-2xl text-sm text-ink/70">
        Every page of the host, guest and supplier apps, the ways in to each one, and the part of
        the entity map it belongs to — read from the code each time it changes. A page with no door
        can only be reached by typing its address.
      </p>

      <dl className="mb-8 grid grid-cols-2 gap-x-6 gap-y-3 sm:grid-cols-3 lg:grid-cols-6">
        {stats.map((x) => (
          <div key={x.label} className="border-t border-ink/10 pt-2">
            <dt className="font-mono text-[10px] uppercase tracking-[0.1em] text-ink/45">{x.label}</dt>
            <dd className={`text-2xl font-semibold tracking-tight ${x.warn ? 'text-warn-900' : 'text-ink'}`}>
              {x.value}
            </dd>
          </div>
        ))}
      </dl>

      {MAP.brokenDoors.length > 0 ? (
        <section className="mb-8">
          <h2 className="text-base font-semibold tracking-tight text-ink">Doors to nowhere</h2>
          <ul className="mt-2">
            {MAP.brokenDoors.map((b) => (
              <li key={`${b.from}${b.to}`} className="border-t border-ink/10 py-2 text-sm">
                <span className="break-all font-mono text-[13px] text-ink">{b.to}</span>
                <span className="text-ink/55"> — written in </span>
                <span className="break-all font-mono text-xs text-ink/70">{b.from}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {screensByArea(MAP).map((g) => {
        const noDoor = g.screens.filter((s) => s.status === 'no-door').length;
        return (
          <details key={g.area} className="mb-4 border-t border-ink/15 pt-3" open={noDoor > 0}>
            <summary className="flex cursor-pointer flex-wrap items-center gap-2 text-base font-semibold tracking-tight text-ink">
              {SCREEN_AREA_LABEL[g.area]}
              <span className="text-sm font-normal text-ink/55">
                {g.screens.length} screens{noDoor ? ` · ${noDoor} with no door` : ''}
              </span>
            </summary>
            <ul className="mt-2">
              {/* The unreachable ones first — they are the fix list. */}
              {[...g.screens]
                .sort((a, b) => Number(a.status !== 'no-door') - Number(b.status !== 'no-door'))
                .map((s) => (
                  <ScreenRow key={s.id} s={s} />
                ))}
            </ul>
          </details>
        );
      })}
    </div>
  );
}
