-- ============================================================================
-- 20260614000000_iteration_0010_attire_guide_recraft_seed.sql
--
-- Wedding Attire Guide · 50-figure Recraft V4.1 vector library seed
-- 5 styles × 10 roles = 50 figure_attire assets + 50 slot-1 color ranges
--
-- WHY (owner directive 2026-05-23 PM, 6-pass iteration on the bride
-- smoke test): seed populates the moodboard_library_assets table with
-- Recraft-generated faceless fashion-illustration Filipina/Filipino
-- wedding party figures, one per (style_theme, role_subtype) cell.
-- Owner approved the aesthetic on the "v3" smoke test (faceless head
-- with veil, fair-Filipina-skin, 2-tone attire, natural standing pose,
-- Etsy-fashion-plate style) and accepted all 50 in the 5×10 preview.
--
-- Pipeline:
--   - Recraft V4.1 vector API (model=recraftv4_1_vector, style=
--     vector_illustration) generated each SVG (~$0.08 per generation)
--   - Total generation cost: $4.00 of $40 pre-purchased API units
--   - Each SVG uploaded to R2 at moodboard-library/figure_attire/
--     {style_slug}/{role}.svg in the setnayan-media bucket
--   - URL pattern: ${R2_PUBLIC_URL}/{key} (r2.dev URLs are
--     bucket-specific, no bucket name in path)
--
-- WAG rendering: existing PhotoFigure component from PR #455 reads
-- moodboard_library_assets keyed by (asset_subtype, style_theme) per
-- the resolveAsset() 4-tier fallback chain. CSS mix-blend-multiply
-- overlay tints the figure with the host's per-role picked color.
-- V1.x adds per-region color picker (skin / hair / main attire /
-- accent / flowers / leaves) via inline-SVG + DOM fill swap.
--
-- Generated by: apps/web/scripts/generate-attire-guide-figures.ts
-- Generated at: 2026-05-23T11:39:18.857Z (PHT)
-- Idempotent: INSERTs gated on WHERE NOT EXISTS (asset_subtype, style_theme).
--
-- Cross-references:
--   * 02_Specifications/Wedding_Attire_Guide_AI_Generation.md
--   * CLAUDE.md 2026-05-23 "Wedding Attire Guide arc" PR lineage
--   * Migration 20260613000000 (style_theme column)
--   * Migration 20260612000000 (Pexels seed retirement)
-- ============================================================================

BEGIN;

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride', 'Bride · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/bride.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom', 'Groom · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/groom.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bridesmaids', 'Bridesmaid · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/bridesmaids.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bridesmaids' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bridesmaids'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groomsmen', 'Groomsman · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/groomsmen.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groomsmen' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groomsmen'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'female_ps', 'Female Principal Sponsor · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/female_ps.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'female_ps' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#D4B896', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'female_ps'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'male_ps', 'Male Principal Sponsor · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/male_ps.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'male_ps' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'male_ps'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'mothers', 'Mother of the Bride/Groom · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/mothers.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'mothers' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#C5C8CC', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'mothers'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'fathers', 'Father of the Bride/Groom · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/fathers.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'fathers' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'fathers'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests', 'Guest woman · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/guests.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'men_guests', 'Guest man · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/men_guests.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'men_guests' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#B8DCE8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'men_guests'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride', 'Bride · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/bride.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom', 'Groom · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/groom.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bridesmaids', 'Bridesmaid · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/bridesmaids.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bridesmaids' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bridesmaids'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groomsmen', 'Groomsman · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/groomsmen.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groomsmen' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groomsmen'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'female_ps', 'Female Principal Sponsor · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/female_ps.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'female_ps' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#D4B896', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'female_ps'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'male_ps', 'Male Principal Sponsor · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/male_ps.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'male_ps' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'male_ps'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'mothers', 'Mother of the Bride/Groom · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/mothers.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'mothers' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#C5C8CC', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'mothers'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'fathers', 'Father of the Bride/Groom · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/fathers.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'fathers' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'fathers'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests', 'Guest woman · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/guests.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'men_guests', 'Guest man · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/men_guests.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'men_guests' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#B8DCE8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'men_guests'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride', 'Bride · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/bride.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom', 'Groom · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/groom.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bridesmaids', 'Bridesmaid · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/bridesmaids.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bridesmaids' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bridesmaids'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groomsmen', 'Groomsman · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/groomsmen.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groomsmen' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groomsmen'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'female_ps', 'Female Principal Sponsor · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/female_ps.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'female_ps' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#D4B896', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'female_ps'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'male_ps', 'Male Principal Sponsor · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/male_ps.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'male_ps' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'male_ps'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'mothers', 'Mother of the Bride/Groom · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/mothers.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'mothers' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#C5C8CC', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'mothers'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'fathers', 'Father of the Bride/Groom · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/fathers.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'fathers' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'fathers'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests', 'Guest woman · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/guests.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'men_guests', 'Guest man · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/men_guests.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'men_guests' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#B8DCE8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'men_guests'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride', 'Bride · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/bride.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom', 'Groom · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/groom.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bridesmaids', 'Bridesmaid · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/bridesmaids.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bridesmaids' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bridesmaids'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groomsmen', 'Groomsman · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/groomsmen.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groomsmen' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groomsmen'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'female_ps', 'Female Principal Sponsor · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/female_ps.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'female_ps' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#D4B896', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'female_ps'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'male_ps', 'Male Principal Sponsor · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/male_ps.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'male_ps' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'male_ps'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'mothers', 'Mother of the Bride/Groom · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/mothers.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'mothers' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#C5C8CC', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'mothers'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'fathers', 'Father of the Bride/Groom · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/fathers.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'fathers' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'fathers'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests', 'Guest woman · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/guests.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'men_guests', 'Guest man · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/men_guests.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'men_guests' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#B8DCE8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'men_guests'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride', 'Bride · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/bride.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom', 'Groom · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/groom.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bridesmaids', 'Bridesmaid · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/bridesmaids.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bridesmaids' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bridesmaids'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groomsmen', 'Groomsman · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/groomsmen.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groomsmen' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groomsmen'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'female_ps', 'Female Principal Sponsor · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/female_ps.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'female_ps' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#D4B896', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'female_ps'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'male_ps', 'Male Principal Sponsor · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/male_ps.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'male_ps' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'male_ps'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'mothers', 'Mother of the Bride/Groom · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/mothers.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'mothers' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#C5C8CC', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'mothers'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'fathers', 'Father of the Bride/Groom · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/fathers.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'fathers' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#E8D9B8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'fathers'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests', 'Guest woman · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/guests.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'men_guests', 'Guest man · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/men_guests.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'men_guests' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#B8DCE8', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'men_guests'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

COMMIT;