-- ============================================================================
-- 20260615000000_iteration_0010_attire_guide_variants_seed.sql
--
-- Wedding Attire Guide · 25-figure variants library seed
-- 5 variants × 5 styles = 25 additional figure_attire assets + 25 color ranges
--
-- WHY (owner directive 2026-05-23 PM, immediately after accepting the
-- 50-figure base library): host needs additional outfit options per role
-- so they can pick non-default looks for their wedding. Variants are
-- additive — they live alongside the 10 default roles in the library,
-- accessed by new asset_subtype keys (groom_tux, groom_3piece, etc.).
--
-- The 5 variants:
--   groom_tux            · classic black-tie tuxedo (American)
--   groom_3piece         · 3-piece suit, vest visible (American)
--   bride_royal          · full royal ball gown, no waist cut, train, veil
--   guests_fashionista   · high-fashion editorial cocktail dress
--   guests_suittie       · women's pant suit + tie (formal register)
--
-- Pipeline (identical to base library):
--   - Recraft V4.1 vector API · ${ROLES=groom_tux,...,guests_suittie} env
--     filter scoped the script to just the 5 new variants × 5 styles
--   - 25/25 succeeded · total cost $2.00 of $40 pre-purchased API units
--   - Each SVG uploaded to R2 at moodboard-library/figure_attire/
--     {style_slug}/{variant_key}.svg in the setnayan-media bucket
--
-- WAG rendering (today): NOT rendered. The current WAG component only
-- knows the 10 default RoleKey union (bride, groom, bridesmaids, etc.)
-- and its assetsByRoleAndStyle resolver looks up by those keys. The new
-- variant assets sit in the library available to admin via /admin/
-- moodboard-library; V1.x variant-picker UI exposes them to hosts.
--
-- V1.x integration plan:
--   - WAG extends RoleConfig to accept a "variantKey" override per role
--   - Per-role variant picker (small chevron next to role label) lets
--     host pick "default" / "tux" / "3-piece" for groom; "default" /
--     "royal" for bride; "default" / "fashionista" / "suittie" for guests
--   - resolveAsset() chain extends to (role, style, variant) lookup
--
-- Generated by: apps/web/scripts/generate-attire-guide-figures.ts
-- Generated at: 2026-05-23T12:01:xx (PHT)
-- Idempotent: INSERTs gated on WHERE NOT EXISTS (asset_subtype, style_theme).
--
-- Cross-references:
--   * Migration 20260614000000 (default 50-figure library)
--   * 02_Specifications/Wedding_Attire_Guide_AI_Generation.md
--   * CLAUDE.md 2026-05-23 "Wedding Attire Guide arc" PR lineage
-- ============================================================================

BEGIN;

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_tux', 'Groom · Tuxedo · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/groom_tux.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_tux' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#1A1A1A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_tux'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_3piece', 'Groom · 3-Piece Suit (American) · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/groom_3piece.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_3piece' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#4A4A4A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_3piece'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride_royal', 'Bride · Royal full ball gown · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/bride_royal.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride_royal' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride_royal'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_fashionista', 'Guest woman · Fashionista · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/guests_fashionista.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_fashionista' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_fashionista'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_suittie', 'Guest · Suit and tie (formal) · Elegant · Simple · Classic (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/elegant-simple-classic/guests_suittie.svg', 'higgsfield_generated', 'elegant · simple · classic', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_suittie' AND style_theme = 'elegant · simple · classic'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_suittie'
  AND a.style_theme = 'elegant · simple · classic'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_tux', 'Groom · Tuxedo · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/groom_tux.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_tux' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#1A1A1A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_tux'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_3piece', 'Groom · 3-Piece Suit (American) · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/groom_3piece.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_3piece' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#4A4A4A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_3piece'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride_royal', 'Bride · Royal full ball gown · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/bride_royal.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride_royal' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride_royal'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_fashionista', 'Guest woman · Fashionista · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/guests_fashionista.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_fashionista' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_fashionista'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_suittie', 'Guest · Suit and tie (formal) · Bridgerton · Regal (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/bridgerton-regal/guests_suittie.svg', 'higgsfield_generated', 'bridgerton · regal', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_suittie' AND style_theme = 'bridgerton · regal'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_suittie'
  AND a.style_theme = 'bridgerton · regal'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_tux', 'Groom · Tuxedo · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/groom_tux.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_tux' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#1A1A1A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_tux'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_3piece', 'Groom · 3-Piece Suit (American) · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/groom_3piece.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_3piece' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#4A4A4A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_3piece'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride_royal', 'Bride · Royal full ball gown · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/bride_royal.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride_royal' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride_royal'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_fashionista', 'Guest woman · Fashionista · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/guests_fashionista.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_fashionista' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_fashionista'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_suittie', 'Guest · Suit and tie (formal) · Editorial Cream (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/editorial-cream/guests_suittie.svg', 'higgsfield_generated', 'editorial cream', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_suittie' AND style_theme = 'editorial cream'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_suittie'
  AND a.style_theme = 'editorial cream'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_tux', 'Groom · Tuxedo · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/groom_tux.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_tux' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#1A1A1A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_tux'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_3piece', 'Groom · 3-Piece Suit (American) · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/groom_3piece.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_3piece' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#4A4A4A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_3piece'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride_royal', 'Bride · Royal full ball gown · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/bride_royal.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride_royal' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride_royal'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_fashionista', 'Guest woman · Fashionista · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/guests_fashionista.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_fashionista' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_fashionista'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_suittie', 'Guest · Suit and tie (formal) · Tropical Heritage (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/tropical-heritage/guests_suittie.svg', 'higgsfield_generated', 'tropical heritage', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_suittie' AND style_theme = 'tropical heritage'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_suittie'
  AND a.style_theme = 'tropical heritage'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_tux', 'Groom · Tuxedo · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/groom_tux.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_tux' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#1A1A1A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_tux'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'groom_3piece', 'Groom · 3-Piece Suit (American) · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/groom_3piece.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'groom_3piece' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#4A4A4A', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'groom_3piece'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'bride_royal', 'Bride · Royal full ball gown · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/bride_royal.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'bride_royal' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#FAFAFA', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'bride_royal'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_fashionista', 'Guest woman · Fashionista · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/guests_fashionista.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_fashionista' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#7E1F32', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_fashionista'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

INSERT INTO public.moodboard_library_assets
  (asset_type, asset_subtype, label, storage_path, source, style_theme, approved_at)
SELECT 'figure_attire', 'guests_suittie', 'Guest · Suit and tie (formal) · Modern Minimalist (Recraft V3 vector)',
       'https://pub-37d64fe618584c2981a88610a55dd439.r2.dev/moodboard-library/figure_attire/modern-minimalist/guests_suittie.svg', 'higgsfield_generated', 'modern minimalist', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM public.moodboard_library_assets
  WHERE asset_subtype = 'guests_suittie' AND style_theme = 'modern minimalist'
);

INSERT INTO public.moodboard_asset_color_ranges
  (asset_id, slot_id, sampled_hex, tolerance_de, region_label)
SELECT a.asset_id, 1, '#2E3F5C', 15, 'attire'
FROM public.moodboard_library_assets a
WHERE a.asset_subtype = 'guests_suittie'
  AND a.style_theme = 'modern minimalist'
  AND NOT EXISTS (
    SELECT 1 FROM public.moodboard_asset_color_ranges rg
    WHERE rg.asset_id = a.asset_id AND rg.slot_id = 1
  );

COMMIT;