-- ============================================================================
-- 20261113000000_user_reports_ai_output.sql
-- Add 'ai_output' to the user_reports.target_type CHECK.
--
-- WHY THIS EXISTS
--   Google Play's AI-Generated Content policy requires apps with generative-AI
--   features to offer an in-app way to report / flag offensive AI output. The
--   live genAI surface is the Setnayan AI bespoke monogram studio
--   (/dashboard/[eventId]/monogram · bespoke_monogram_generations, migration
--   20261112000000). Reports ride the EXISTING user_reports queue (migration
--   20261108000000 · Apple 1.2 / Play UGC) — same reasons, same RLS (signed-in
--   reporter INSERTs as themselves; couple + admin read; admin resolves at
--   /admin/user-reports). The only schema change needed is widening the
--   target_type CHECK so a report can point at an AI generation:
--     target_type = 'ai_output' · target_id = bespoke_monogram_generations
--     .generation_id (TEXT-cast, same opaque-id convention as 'photo').
--
-- IDEMPOTENT: drops whatever CHECK currently constrains target_type (by
-- definition match, not just by the autogenerated name — robust to a renamed
-- or re-minted constraint) and re-adds the canonical named constraint.
-- Safe to (re-)apply.
-- ============================================================================

BEGIN;

-- Drop every CHECK on user_reports that mentions target_type. On a stock prod
-- this is exactly one: the inline CHECK from 20261108000000, autogenerated as
-- user_reports_target_type_check.
DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'user_reports'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%target_type%'
  LOOP
    EXECUTE format('ALTER TABLE public.user_reports DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE public.user_reports
  ADD CONSTRAINT user_reports_target_type_check
  CHECK (target_type IN ('photo', 'comment', 'user', 'ai_output'));

COMMENT ON TABLE public.user_reports IS
  'UGC + AI-output report queue (Apple 1.2 / Google Play UGC + Play GenAI '
  'policy). One row per report filed against Papic guest gallery content '
  '(photo/user) or a Setnayan AI generation (ai_output · target_id = '
  'bespoke_monogram_generations.generation_id). Routes to both the couple '
  '(event RLS) and Setnayan admins (is_admin). Guest-filed reports come '
  'through the SECURITY DEFINER report_guest_capture() fn.';

COMMIT;

-- Verification:
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--   WHERE conname = 'user_reports_target_type_check';
--   -- Expect: CHECK (target_type IN ('photo','comment','user','ai_output')).
