-- A REAL SCREEN, AND THE COUPLE MAY PICK ALL TWENTY.
--
-- Owner, 2026-08-21: *"the need to have a real screen to pick their challenges
-- up to 20 challenges."*
--
-- The board has always been twenty slots, but the COUPLE's lane was capped at
-- ten. A couple who chose twelve got ten; the other two sat with no board
-- position and nothing on any screen explained why. This lifts their ceiling to
-- the whole board.
--
-- ⚠ ONE THING IS NOT LIFTED, AND IT IS ABOUT SOMEBODY ELSE'S MONEY: a booth
-- mission a supplier PAID for keeps its slot. The couple's ceiling is
-- `20 - sold`, which is exactly 20 today (production holds zero sponsorships)
-- and degrades visibly rather than silently if one is ever bought.
--
-- Everything else in this function is reproduced from the version applied by
-- 20271154904649, unchanged. It is not re-typed from memory: this file was
-- generated by reading that migration's body and replacing the lane
-- arithmetic — the practice that stops a `CREATE OR REPLACE` quietly reverting
-- a fix nobody remembered was in there.

CREATE OR REPLACE FUNCTION public.ensure_papic_board(p_event_id uuid, p_pabati_active boolean DEFAULT false)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_couple_used INTEGER;
  v_vendor_used INTEGER;
  v_target      INTEGER;
  v_slotted     INTEGER;
  v_event_type  TEXT;
BEGIN
  -- Auth: the event's couple or coordinator, an admin, or service_role (server).
  -- NOT anon.
  --
  -- ⚠ The single-line form of this comment failed the secret scan. gitleaks'
  -- generic-api-key rule read the slash-joined role list as one high-entropy
  -- token and reported a leak at this line — in a COMMENT, with no credential
  -- anywhere near it. Split rather than suppressed: an inline `gitleaks:allow`
  -- would silence the rule here permanently, and a suppression marker on a line
  -- that never held a secret is a marker nobody can later evaluate.
  IF auth.uid() IS NOT NULL
     AND NOT public.is_admin()
     AND NOT EXISTS (
       SELECT 1 FROM public.event_members em
       WHERE em.event_id = p_event_id AND em.user_id = auth.uid()
         AND em.member_type IN ('couple','coordinator')
     ) THEN
    RAISE EXCEPTION 'not authorized to build the Papic board for event %', p_event_id;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('papic_board:' || p_event_id::text));

  -- ⬇ THE ONE-LINE FIX. Was ensure_papic_auto_missions(...), whose 2026-08-01
  -- NULL-session refusal aborted this whole function on the guest path — the
  -- only path that ever calls it — leaving every event with no board at all.
  -- We have authorized above; call the step, not the public door.
  PERFORM public.papic_generate_booth_missions_unchecked(p_event_id);

  -- What kind of celebration is this? Read once; both lanes use it.
  SELECT e.event_type INTO v_event_type
  FROM public.events e WHERE e.event_id = p_event_id;

  -- ── LANE SIZES — THE COUPLE'S CEILING IS NOW THE WHOLE BOARD ─────────────
  -- Owner, 2026-08-21: "the need to have a real screen to pick their challenges
  -- UP TO 20 CHALLENGES." The couple lane was capped at 10, so a couple who
  -- chose twenty got ten, silently, with the other ten queued behind a wall
  -- they were never shown.
  --
  -- ⚠ THE VENDOR LANE IS MEASURED FIRST, AND THAT IS DELIBERATE. A booth
  -- mission is something a supplier PAID for. If the couple's cap were a flat
  -- 20, the arithmetic would go NEGATIVE the moment one existed
  -- (20 - 20 - 5 = -5) and the slot allocator would try to place 25 rows in 20
  -- seats. Worse than the maths: a paid placement would vanish the moment the
  -- couple added a twentieth of their own, with nothing anywhere saying so.
  --
  -- So the couple's ceiling is "the whole board, minus whatever is already
  -- sold". Today that is exactly 20 — production holds ZERO booth
  -- sponsorships — and it degrades honestly rather than silently if one is ever
  -- bought. The screen shows the number, so the couple is never refused by a
  -- limit they cannot see.
  SELECT LEAST(COUNT(*), 5) INTO v_vendor_used
  FROM public.papic_missions m
  WHERE m.event_id = p_event_id AND m.source IN ('vendor','auto') AND m.is_active AND m.approved
    AND m.vendor_id IN (
      SELECT ev.vendor_id FROM public.event_vendors ev
      WHERE ev.event_id = p_event_id
        AND ev.status IN ('contracted','deposit_paid','delivered','complete')
    );

  SELECT LEAST(COUNT(*), 20 - v_vendor_used) INTO v_couple_used
  FROM public.papic_missions m
  WHERE m.event_id = p_event_id AND m.source = 'couple' AND m.is_active AND m.approved;

  -- >= 0 by construction now, never negative. It CAN be zero — a couple who
  -- picks all twenty gets a board of exactly their own choices, which is the
  -- point of the screen.
  v_target := 20 - v_couple_used - v_vendor_used;

  -- Materialize the Setnayan fills: top-ranked library items NOT taken by a couple pick, NOT vetoed
  -- (an inactive setnayan tombstone), Pabati only if the SKU is active, and only rows whose scope
  -- admits this event type. Idempotent via the partial unique. Existing active setnayan rows
  -- conflict -> DO NOTHING (kept, never re-created).
  IF v_target > 0 THEN
    INSERT INTO public.papic_missions
      (event_id, mission_type, source, prompt, library_id, capture_kind, approved, is_active)
    SELECT src.event_id, src.mission_type, 'setnayan', src.prompt, src.library_id, src.capture_kind, true, true
    FROM (
      SELECT p_event_id AS event_id, l.mission_type, l.prompt, l.library_id, l.capture_kind
      FROM public.papic_challenge_library l
      WHERE l.is_active
        AND l.mission_type <> 'face_verified'
        AND (l.capture_kind <> 'pabati' OR p_pabati_active)
        AND (l.event_types IS NULL OR v_event_type = ANY (l.event_types))
        AND NOT EXISTS (  -- taken by a couple pick
          SELECT 1 FROM public.papic_missions cm
          WHERE cm.event_id = p_event_id AND cm.source = 'couple'
            AND cm.is_active AND cm.approved AND cm.library_id = l.library_id)
        AND NOT EXISTS (  -- vetoed tombstone (couple hid this hero)
          SELECT 1 FROM public.papic_missions vm
          WHERE vm.event_id = p_event_id AND vm.source = 'setnayan'
            AND vm.library_id = l.library_id AND NOT vm.is_active)
      ORDER BY l.priority_rank NULLS LAST, l.library_id
      LIMIT v_target
    ) src
    ON CONFLICT (event_id, library_id) WHERE source = 'setnayan' DO NOTHING;
  END IF;

  -- Reset the board, then reassign board_slot deterministically across the three lanes.
  UPDATE public.papic_missions
    SET board_slot = NULL, updated_at = NOW()
  WHERE event_id = p_event_id AND board_slot IS NOT NULL;

  WITH cand AS (
    -- couple lane (slots first): active/approved couple rows by created_at, id.
    SELECT m.mission_id, 0 AS lane,
           row_number() OVER (ORDER BY m.created_at, m.id) AS lane_rank
    FROM public.papic_missions m
    WHERE m.event_id = p_event_id AND m.source = 'couple' AND m.is_active AND m.approved
    UNION ALL
    -- vendor lane: PAID (source='vendor', approved) before FREE booth (source='auto'); booked vendors only.
    SELECT m.mission_id, 1 AS lane,
           row_number() OVER (
             ORDER BY CASE WHEN m.source = 'vendor' THEN 0 ELSE 1 END, m.created_at, m.id
           ) AS lane_rank
    FROM public.papic_missions m
    WHERE m.event_id = p_event_id AND m.source IN ('vendor','auto') AND m.is_active AND m.approved
      AND m.vendor_id IN (
        SELECT ev.vendor_id FROM public.event_vendors ev
        WHERE ev.event_id = p_event_id
          AND ev.status IN ('contracted','deposit_paid','delivered','complete'))
    UNION ALL
    -- setnayan lane: by priority_rank then library order; exclude Pabati-if-inactive, couple-taken,
    -- and anything whose scope does not admit this event type.
    SELECT m.mission_id, 2 AS lane,
           row_number() OVER (ORDER BY l.priority_rank NULLS LAST, l.library_id) AS lane_rank
    FROM public.papic_missions m
    JOIN public.papic_challenge_library l ON l.library_id = m.library_id
    WHERE m.event_id = p_event_id AND m.source = 'setnayan' AND m.is_active AND m.approved
      AND l.is_active
      AND (l.capture_kind <> 'pabati' OR p_pabati_active)
      AND (l.event_types IS NULL OR v_event_type = ANY (l.event_types))
      AND NOT EXISTS (  -- dedup: a couple pick of the same library item wins the slot
        SELECT 1 FROM public.papic_missions cm
        WHERE cm.event_id = p_event_id AND cm.source = 'couple'
          AND cm.is_active AND cm.approved AND cm.library_id = m.library_id)
  ),
  capped AS (
    SELECT mission_id, lane, lane_rank FROM cand
    WHERE (lane = 0 AND lane_rank <= v_couple_used)
       OR (lane = 1 AND lane_rank <= v_vendor_used)
       OR (lane = 2 AND lane_rank <= v_target)
  ),
  slotted AS (
    SELECT mission_id, row_number() OVER (ORDER BY lane, lane_rank) AS slot
    FROM capped
  )
  UPDATE public.papic_missions m
    SET board_slot = s.slot, updated_at = NOW()
  FROM slotted s
  WHERE m.mission_id = s.mission_id;

  GET DIAGNOSTICS v_slotted = ROW_COUNT;
  RETURN v_slotted;
END;
$function$;
