-- ============================================================================
-- 20270817834616_chapter_report_target.sql
-- Widen the shared user_reports queue to cover ONE new PUBLIC-page target:
--   • 'chapter' — a creator "Adventure Chapter" page /u/[slug]/c/[public_id]
--                 (target_id = creator_chapters.public_id, S89C-…)
--
-- WHY THIS EXISTS
--   Storytellers × Editorial architecture council verdict (2026-07-16) —
--   Phase S0 "safety floor": chapter detail pages are ALREADY LIVE and public
--   (published chapter + public_profile_enabled owner), so an abuse-report path
--   is owed to them regardless of every later Storytellers phase. Same standing
--   solo-op red line as migration 20270812329751: no second moderation surface —
--   chapter reports ride the EXISTING user_reports queue and resolve at
--   /admin/user-reports (escalate/dismiss now; the "hide" lane arrives with
--   Phase S1's showcase_featured_at columns, when featuring exists to clear).
--
-- ONE schema change, minimal + idempotent, following the exact
-- drop-by-definition-then-readd pattern of 20270812329751 (which itself
-- followed 20261113000000):
--   1. target_type CHECK — add 'chapter' to the allowed set.
--   2. event_id guard CHECK — a chapter report is NOT event-scoped (the chapter
--      belongs to a creator profile; its optional event linkage is the
--      creator's private substrate, not the reporter's business), so 'chapter'
--      joins 'user_profile' in the may-omit-event_id set. Every other target
--      still REQUIRES an event_id. Existing rows are unaffected (the guard
--      only widens).
--
--   No RLS change. The existing policies still hold:
--     • couple read  — event_id IN current_event_ids(); a chapter report has
--       NULL event_id so it never matches a couple — admins only, exactly right.
--     • admin read/update — is_admin(), unchanged.
--   The report is filed server-side (service role) by the reusable
--   "Report this page" entry (lib/reports.ts), same as event/user_profile.
--
-- IDEMPOTENT. Safe to (re-)apply. Does NOT touch prod here.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Widen the target_type CHECK to include 'chapter'.
--    Drop every CHECK on user_reports that mentions target_type (by definition,
--    not just by the autogenerated name — robust to a renamed constraint), then
--    re-add the canonical named constraint with the full allowed set.
--    NOTE: the event_id guard from 20270812329751 also mentions target_type in
--    its definition, so this loop drops it too — intentional; step 2 re-adds it
--    widened. Both constraints stay canonical.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'user_reports'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%target_type%'
  LOOP
    EXECUTE format('ALTER TABLE public.user_reports DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE public.user_reports
  ADD CONSTRAINT user_reports_target_type_check
  CHECK (target_type IN ('photo', 'comment', 'user', 'ai_output', 'event', 'user_profile', 'chapter'));

-- ----------------------------------------------------------------------------
-- 2. (Re-)add the event_id guard with 'chapter' in the may-omit set. (event_id
--    was made nullable by 20270812329751; the loop above already dropped the
--    old guard because its definition mentions target_type.) Only
--    'user_profile' and 'chapter' may have a NULL event_id; every other target
--    must carry one.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'user_reports_event_id_required_check'
      AND conrelid = 'public.user_reports'::regclass
  ) THEN
    ALTER TABLE public.user_reports DROP CONSTRAINT user_reports_event_id_required_check;
  END IF;
END $$;

ALTER TABLE public.user_reports
  ADD CONSTRAINT user_reports_event_id_required_check
  CHECK (target_type IN ('user_profile', 'chapter') OR event_id IS NOT NULL);

COMMENT ON TABLE public.user_reports IS
  'UGC + AI-output + public-page report queue (Apple 1.2 / Google Play UGC + '
  'Play GenAI policy). One row per report: Papic guest gallery content '
  '(photo/user), a Setnayan AI generation (ai_output), a public invitation page '
  '(event · target_id = events.event_id), a public profile page '
  '(user_profile · target_id = users.user_id, event_id NULL), or a creator '
  'chapter page (chapter · target_id = creator_chapters.public_id, event_id '
  'NULL). Routes to the couple (event RLS, when event-scoped) and always to '
  'Setnayan admins (is_admin), resolved at /admin/user-reports.';

COMMIT;

-- Verification:
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--   WHERE conname = 'user_reports_target_type_check';
--   -- Expect: CHECK (target_type IN
--   --   ('photo','comment','user','ai_output','event','user_profile','chapter')).
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--   WHERE conname = 'user_reports_event_id_required_check';
--   -- Expect: CHECK (target_type IN ('user_profile','chapter')
--   --   OR event_id IS NOT NULL).
