-- ============================================================================
-- 20271004566590_vendor_team_role_secretary.sql
-- Vendor team roles — add SECRETARY to public.vendor_team_role, and the
-- vendor_assignment_received notification type.
--
-- Spec: ~/Documents/Claude/Projects/Setnayan/
--         Vendor_Monetization_Model_LOCKED_2026-07-25.md § 7 (Team seats + roles)
--
--   Owner/Admin — everything, incl. billing + settings           (exists)
--   Agent       — own clients + own calendar                     (exists)
--   Secretary   — scheduling + comms across the whole team        <- NEW
--
-- FINANCIAL IS DELIBERATELY NOT ADDED (descoped 2026-07-26, adversarial
-- review). Its defining promise — "billing/payments/reports but NEVER client
-- chat" — cannot be expressed by `public.current_vendor_ids(min_role)`, which
-- is a SINGLE SCALAR rank (owner 4 > admin 3 > agent 2 > viewer 1): vendor chat
-- is gated at rank >= 1 and billing at rank >= 3, so any rank that lets
-- Financial see billing necessarily clears chat. Adding the label would have
-- made an unenforceable boundary expressible in data, and
-- `ALTER TYPE ... ADD VALUE` cannot be undone. Re-introducing the role needs an
-- RLS split (e.g. `current_vendor_ids_billing`) plus a route guard — an open
-- owner decision, not a patch.
--
-- Secretary, by contrast, only needs a NEGATIVE boundary the existing ladder
-- CAN express (below admin => no billing, no store settings).
--
-- Roles + agent scheduling are a Pro+ capability. Assigning work to a team
-- member notifies them, which needs a notification_type the enum accepts —
-- hence the second ALTER TYPE here.
--
-- ADDITIVE ONLY. No existing row changes: every current membership stays
-- owner/admin/agent/viewer and every predicate over those four is unchanged.
-- The app side is flag-dark behind NEXT_PUBLIC_VENDOR_TEAM_ROLES_V2 (default
-- OFF), so nothing can WRITE the new value until the owner flips the flag —
-- this migration only makes the value expressible.
--
-- WHY A DEDICATED FILE (house pattern, see
-- 20270815640306_creator_notification_type_new_chapter_from_followed.sql):
-- Postgres forbids USING a newly-added enum value in the same transaction that
-- adds it. This file runs ONLY ALTER TYPE statements — no INSERT/UPDATE/CHECK
-- references either new label — so both values are committed before any later
-- migration or runtime code touches them.
--
-- Idempotent — ADD VALUE IF NOT EXISTS.
-- ============================================================================

-- Vendor team roles (public.vendor_team_role, created 20260514010000).
ALTER TYPE public.vendor_team_role ADD VALUE IF NOT EXISTS 'secretary';

-- Assignment notification (public.notification_type, created 20260513160000).
-- Emitted by lib/vendor-team-assignment-notify.ts when an admin assigns work to
-- a team member — flag-dark, never fired while the flag is OFF.
ALTER TYPE public.notification_type ADD VALUE IF NOT EXISTS 'vendor_assignment_received';
