-- MOOD BOARD THEME TEMPLATES — a curated gallery of starter "Overall Theme"
-- looks a couple can browse and apply, seeding their board instead of
-- starting from a blank palette + reception design (Mood Board redesign
-- follow-up, 2026-09-03).
--
-- Reuses the EXISTING moodboard_library_assets.style_theme taxonomy (5 style
-- families, added 20260613000000 for the now-deleted Wedding Attire Guide and
-- otherwise orphaned since that component's removal in 20271193010764) as one
-- axis: every template's style_family is one of the same 5 strings, so
-- applying a template can look up matching figure_attire assets by
-- style_theme for its inspiration-slot suggestions (see
-- applyMoodboardTemplate in dashboard/[eventId]/studio/mood-board/actions.ts).
--
-- A SECOND, INDEPENDENT axis — `mood_tag` — classifies each template's actual
-- character (whimsical vs. minimalist vs. dark-moody vs. bold-contrasting vs.
-- simple-understated vs. maximalist-complex) regardless of which style_family
-- it belongs to. The two axes are deliberately orthogonal: a 'bridgerton ·
-- regal' template can be either dark_moody or whimsical_storybook depending
-- on its actual palette, and the gallery UI filters on both independently.
--
-- This is CURATED ADMIN CONTENT (100 hand-authored rows — 20 per style
-- family), not a couple-owned row — same shape as moodboard_library_assets
-- and platform_retail_catalog_v2: RLS grants everyone SELECT (browsing a
-- template gallery needs no auth), and only admin/service-role can write.
-- role_palette / reception_design are jsonb matching the EXACT shapes
-- apps/web/lib/mood-board.ts's RolePalette and apps/web/lib/reception-scene.ts's
-- ReceptionDesign already expect — applying a template only ever writes valid
-- values into those existing shapes (RULE 0: no new schema for the couple's
-- own data, only a reference table of starter values). Every row was
-- validated against the real `sanitizeRolePalette` / `sanitizeReceptionDesign`
-- functions before this migration was written (no value here gets silently
-- dropped by either sanitizer).
--
-- Idempotent: CREATE TABLE IF NOT EXISTS, DROP/ADD CONSTRAINT IF EXISTS, seed
-- rows gated on "only insert if the table is empty" so a re-run never
-- duplicates content.

CREATE TABLE IF NOT EXISTS public.moodboard_theme_templates (
  template_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  style_family      TEXT NOT NULL,
  mood_tag          TEXT NOT NULL,
  name              TEXT NOT NULL,
  description       TEXT NOT NULL,
  role_palette      JSONB NOT NULL DEFAULT '{}'::jsonb,
  reception_design  JSONB NOT NULL DEFAULT '{}'::jsonb,
  sort_order        INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotent column add for a re-run against a table that was already
-- created by an earlier apply of this same migration (pre-scale-up, before
-- mood_tag existed) — ADD COLUMN IF NOT EXISTS is a no-op once it's there.
ALTER TABLE public.moodboard_theme_templates
  ADD COLUMN IF NOT EXISTS mood_tag TEXT NOT NULL DEFAULT 'simple_understated';
ALTER TABLE public.moodboard_theme_templates
  ALTER COLUMN mood_tag DROP DEFAULT;

-- Same 5 strings as moodboard_library_assets_style_theme_check
-- (20260613000000) — deliberately NOT a foreign key (that column is
-- nullable/mixed with venue_scene rows that carry no style at all), but the
-- CHECK keeps the vocab identical so a template's style_family always has a
-- matching figure_attire bucket to look up.
ALTER TABLE public.moodboard_theme_templates
  DROP CONSTRAINT IF EXISTS moodboard_theme_templates_style_family_check;
ALTER TABLE public.moodboard_theme_templates
  ADD CONSTRAINT moodboard_theme_templates_style_family_check
  CHECK (
    style_family IN (
      'elegant · simple · classic',
      'bridgerton · regal',
      'editorial cream',
      'tropical heritage',
      'modern minimalist'
    )
  );

-- The independent mood-character axis (owner directive, 2026-09-03) — a
-- second filter dimension in the gallery UI, orthogonal to style_family.
ALTER TABLE public.moodboard_theme_templates
  DROP CONSTRAINT IF EXISTS moodboard_theme_templates_mood_tag_check;
ALTER TABLE public.moodboard_theme_templates
  ADD CONSTRAINT moodboard_theme_templates_mood_tag_check
  CHECK (
    mood_tag IN (
      'whimsical_storybook',
      'minimalist',
      'dark_moody',
      'bold_contrasting',
      'simple_understated',
      'maximalist_complex'
    )
  );

CREATE INDEX IF NOT EXISTS idx_moodboard_theme_templates_family_sort
  ON public.moodboard_theme_templates(style_family, sort_order);
CREATE INDEX IF NOT EXISTS idx_moodboard_theme_templates_mood_tag
  ON public.moodboard_theme_templates(mood_tag);

ALTER TABLE public.moodboard_theme_templates ENABLE ROW LEVEL SECURITY;

-- Everyone can browse the gallery (no per-row ownership — this is reference
-- content, not a couple's data). Matches platform_retail_catalog_v2's
-- "price information is non-secret" public-read policy (20260628000000) —
-- same reasoning, same shape, no explicit GRANT needed (RLS is the real gate
-- and this repo's other public-read catalog tables don't grant explicitly
-- either).
DROP POLICY IF EXISTS moodboard_theme_templates_public_read ON public.moodboard_theme_templates;
CREATE POLICY moodboard_theme_templates_public_read
  ON public.moodboard_theme_templates FOR SELECT
  USING (TRUE);

-- Admin-only writes (same admin predicate as moodboard_library_assets_admin_all,
-- 20260525000000). No couple/vendor ever writes this table directly —
-- applyMoodboardTemplate only ever COPIES a template's values into the
-- couple's own events row, never writes here.
DROP POLICY IF EXISTS moodboard_theme_templates_admin_all ON public.moodboard_theme_templates;
CREATE POLICY moodboard_theme_templates_admin_all ON public.moodboard_theme_templates
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid()
        AND (u.is_internal = true OR u.is_team_member = true OR u.account_type = 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.user_id = auth.uid()
        AND (u.is_internal = true OR u.is_team_member = true OR u.account_type = 'admin')
    )
  );

-- ── SEED — 100 curated templates, 20 per style family ───────────────────────
-- Hand-authored content (not test fixtures). Deliberately leans on
-- Filipino-specific material/motif vocabulary (piña/jusi, capiz shell, banig
-- weave, bamboo/rattan, narra wood, sampaguita/ilang-ilang/waling-waling) —
-- spread across a meaningful share of ALL 5 families, not only 'tropical
-- heritage' — alongside the generic-elegant options reception-scene.ts
-- already had, using 5 small ADDITIVE Option entries added to RECEPTION_PARTS
-- in this same PR (backdrop.style 'capiz', ceiling.treatment 'banana_leaf',
-- tables.linen 'banig', tables.centerpiece 'sampaguita', tunnel.style
-- 'bamboo') — nothing renamed or removed, every couple gets more choice.
--
-- Gated on "only insert if the table is empty" for idempotent re-application;
-- `name` has no UNIQUE constraint (admin content, not a couple-safety
-- invariant) so this checks table emptiness rather than relying on
-- ON CONFLICT / per-row existence checks across 100 rows.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.moodboard_theme_templates LIMIT 1) THEN
    INSERT INTO public.moodboard_theme_templates
      (style_family, mood_tag, name, description, role_palette, reception_design, sort_order)
    VALUES
  ('elegant · simple · classic', 'simple_understated', 'Vintage Ilustrado Elegance', 'Spanish-colonial ilustrado elegance for a church-and-ancestral-house wedding — piña and jusi ivory, narra wood, antique gold, and a capiz-shell backdrop.', '{"ceremony":["#FAF7F2","#D4AF37"],"reception":["#FAF7F2","#C5A059","#824A2A"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#C5A059","#824A2A","#FAF7F2"],"guest":["#FAF7F2","#C5A059","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"cross_back","linen":"plain","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 0),
  ('elegant · simple · classic', 'whimsical_storybook', 'Romantic Garden Pastel', 'A soft pastel garden reception in blush and sage with sampaguita accents — romantic and light, suited to a garden or resort venue.', '{"ceremony":["#F4C2C2","#8A9A6B"],"reception":["#F4C2C2","#8A9A6B","#FAF7F2"],"bride":["#F4C2C2"],"groom":["#824A2A"],"wedding_party":["#F4C2C2","#8A9A6B","#FAF7F2"],"guest":["#FAF7F2","#F4C2C2","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"hanging_florals"},"backdrop":{"style":"floral_wall","florals":"none"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"chiavari","linen":"runner","centerpiece":"sampaguita","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"petals"},"people":{"who":"couple_party"}}'::jsonb, 1),
  ('elegant · simple · classic', 'maximalist_complex', 'Capiz & Ivory Classic', 'Ivory and gold, lit through iridescent capiz-shell panels — a classic, church-to-ballroom look with a distinctly Filipino backdrop.', '{"ceremony":["#FFFFF0","#D4AF37"],"reception":["#FAF7F2","#D4AF37","#C5A059"],"bride":["#FFFFF0"],"groom":["#1E2229"],"wedding_party":["#C5A059","#D4AF37","#FAF7F2"],"guest":["#FAF7F2","#C5A059","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 2),
  ('elegant · simple · classic', 'simple_understated', 'Narra & Ivory Church Classic', 'Warm narra-wood tones against ivory and soft gold — a grounded, timeless classic for a church wedding.', '{"ceremony":["#FAF7F2","#824A2A"],"reception":["#FAF7F2","#824A2A","#D4AF37"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#824A2A","#D4AF37","#FAF7F2"],"guest":["#FAF7F2","#824A2A","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"cross_back","linen":"plain","centerpiece":"tall","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 3),
  ('elegant · simple · classic', 'simple_understated', 'Pearl & Silver Ballroom Classic', 'Cool pearl white and silver for a formal hotel-ballroom classic — a jewel-box reception with clean, quiet luxury.', '{"ceremony":["#FFFFFF","#CFD3D6"],"reception":["#FFFFFF","#CFD3D6","#1E2540"],"bride":["#FFFFFF"],"groom":["#1E2540"],"wedding_party":["#CFD3D6","#FFFFFF","#1E2540"],"guest":["#FFFFFF","#CFD3D6","#1E2540"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"none"},"tables":{"shape":"round","chairs":"ghost","linen":"sequin","centerpiece":"candelabra","place":"silver"},"tunnel":{"style":"crystal"},"entrance":{"runner":"mirror"},"people":{"who":"couple_party"}}'::jsonb, 4),
  ('elegant · simple · classic', 'simple_understated', 'Champagne & Blush Simplicity', 'Champagne gold and the softest blush — a quiet, unfussy classic for a couple who wants elegant without a single loud color.', '{"ceremony":["#FAF7F2","#C5A059"],"reception":["#C5A059","#F4C2C2","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#C5A059","#F4C2C2","#FAF7F2"],"guest":["#FAF7F2","#C5A059","#F4C2C2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"runner","centerpiece":"tall","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 5),
  ('elegant · simple · classic', 'simple_understated', 'Dove Grey & Gold Classic', 'Dove grey softened with gold — a cool-toned classic that photographs beautifully under any lighting.', '{"ceremony":["#CFD3D6","#D4AF37"],"reception":["#CFD3D6","#D4AF37","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#D4AF37","#FAF7F2"],"guest":["#CFD3D6","#D4AF37","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"tall","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 6),
  ('elegant · simple · classic', 'maximalist_complex', 'Golden Hour Chandelier Classic', 'Warm gold under chandelier light — an amber-hued classic built for a reception that peaks at golden hour.', '{"ceremony":["#FAF7F2","#D4AF37"],"reception":["#D4AF37","#C97B4B","#824A2A"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#D4AF37","#C97B4B","#824A2A"],"guest":["#FAF7F2","#D4AF37","#C97B4B"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candles","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 7),
  ('elegant · simple · classic', 'simple_understated', 'Ecru & Copper Classic', 'Ecru linen and warm copper accents — an understated classic that leans slightly rustic without losing formality.', '{"ceremony":["#FAF7F2","#C97B4B"],"reception":["#C97B4B","#824A2A","#FAF7F2"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#C97B4B","#824A2A","#FAF7F2"],"guest":["#FAF7F2","#C97B4B","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"cross_back","linen":"plain","centerpiece":"low","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 8),
  ('elegant · simple · classic', 'simple_understated', 'Ivory & Eucalyptus Classic', 'Ivory with soft eucalyptus green — a classic reception that stays cool and calm rather than warm and golden.', '{"ceremony":["#FAF7F2","#8A9A6B"],"reception":["#FAF7F2","#8A9A6B","#824A2A"],"bride":["#FFFFF0"],"groom":["#3A5746"],"wedding_party":["#8A9A6B","#824A2A","#FAF7F2"],"guest":["#FAF7F2","#8A9A6B","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"hanging_greenery"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"greenery_runner","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 9),
  ('elegant · simple · classic', 'maximalist_complex', 'Antique Rose Chandelier Classic', 'Antique rose and warm gold under crystal chandeliers — a softly feminine classic ballroom look.', '{"ceremony":["#C9A0A0","#D4AF37"],"reception":["#C9A0A0","#D4AF37","#7A1F2B"],"bride":["#FAF7F2"],"groom":["#5C2542"],"wedding_party":["#C9A0A0","#D4AF37","#7A1F2B"],"guest":["#FAF7F2","#C9A0A0","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"cascading"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 10),
  ('elegant · simple · classic', 'simple_understated', 'Soft Grey & Rose Classic', 'Soft grey paired with dusty rose — a restrained, quiet-luxury classic for a couple who wants elegant, not loud.', '{"ceremony":["#CFD3D6","#C9A0A0"],"reception":["#CFD3D6","#C9A0A0","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#C9A0A0","#FAF7F2"],"guest":["#CFD3D6","#C9A0A0","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"runner","centerpiece":"tall","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 11),
  ('elegant · simple · classic', 'simple_understated', 'Cream & Silver Orchid Classic', 'Cream and brushed silver with a single white orchid accent — a spare, elegant classic.', '{"ceremony":["#FAF7F2","#CFD3D6"],"reception":["#FAF7F2","#CFD3D6","#D4AF37"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#FAF7F2","#D4AF37"],"guest":["#FAF7F2","#CFD3D6","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"ghost","linen":"plain","centerpiece":"tall","place":"silver"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 12),
  ('elegant · simple · classic', 'simple_understated', 'Warm Ivory Candlelight Classic', 'Warm ivory lit almost entirely by candlelight — a soft-focus classic with minimal color beyond gold and flame.', '{"ceremony":["#FFFFF0","#D4AF37"],"reception":["#FFFFF0","#D4AF37","#824A2A"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#D4AF37","#824A2A","#FFFFF0"],"guest":["#FFFFF0","#D4AF37","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candles","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"candle"},"people":{"who":"couple_party"}}'::jsonb, 13),
  ('elegant · simple · classic', 'minimalist', 'Frosted Silver Winter Classic', 'Frosted silver and icy white for a cool-toned classic, suited to an air-conditioned ballroom or a December date.', '{"ceremony":["#FFFFFF","#CFD3D6"],"reception":["#FFFFFF","#CFD3D6","#3A5766"],"bride":["#FFFFFF"],"groom":["#1E2540"],"wedding_party":["#CFD3D6","#FFFFFF","#3A5766"],"guest":["#FFFFFF","#CFD3D6","#3A5766"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"ghost","linen":"sequin","centerpiece":"tall","place":"silver"},"tunnel":{"style":"crystal"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 14),
  ('elegant · simple · classic', 'whimsical_storybook', 'Peach & Gold Garden Classic', 'Soft peach and gold for a classic garden-adjacent reception — warm, romantic, and easy to photograph.', '{"ceremony":["#F0B27A","#D4AF37"],"reception":["#F0B27A","#D4AF37","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#F0B27A","#D4AF37","#FAF7F2"],"guest":["#FAF7F2","#F0B27A","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"hanging_florals"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"tall","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 15),
  ('elegant · simple · classic', 'minimalist', 'Classic White Orchid Ballroom', 'All-white with a single gold line — the most restrained possible reading of "classic," built around white orchids.', '{"ceremony":["#FFFFFF","#D4AF37"],"reception":["#FFFFFF","#D4AF37","#CFD3D6"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#FFFFFF","#D4AF37","#CFD3D6"],"guest":["#FFFFFF","#D4AF37","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"low","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 16),
  ('elegant · simple · classic', 'maximalist_complex', 'Bronze & Cream Classic', 'Bronze metallics against warm cream — a classic look with a slightly darker, richer metal than the usual gold.', '{"ceremony":["#FAF7F2","#824A2A"],"reception":["#824A2A","#C97B4B","#FAF7F2"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#824A2A","#C97B4B","#FAF7F2"],"guest":["#FAF7F2","#824A2A","#C97B4B"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 17),
  ('elegant · simple · classic', 'simple_understated', 'Mint & Champagne Classic', 'A cool mint paired with champagne gold — an unexpected but still-quiet classic combination.', '{"ceremony":["#FAF7F2","#8A9A6B"],"reception":["#8A9A6B","#C5A059","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#3A5746"],"wedding_party":["#8A9A6B","#C5A059","#FAF7F2"],"guest":["#FAF7F2","#8A9A6B","#C5A059"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"runner","centerpiece":"low","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 18),
  ('elegant · simple · classic', 'maximalist_complex', 'Amber Chandelier Grand Classic', 'Deep amber and gold under a full spread of crystal chandeliers — the most maximalist reading of "classic" in this family.', '{"ceremony":["#D4AF37","#824A2A"],"reception":["#D4AF37","#824A2A","#7A1F2B"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#D4AF37","#824A2A","#7A1F2B"],"guest":["#FAF7F2","#D4AF37","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"sweetheart","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"fabric"},"people":{"who":"couple_party"}}'::jsonb, 19),
  ('bridgerton · regal', 'maximalist_complex', 'Glam & Gold Opulence', 'Rose, burgundy, and gold under candlelight — a maximalist, red-carpet-glam hotel-ballroom reception.', '{"ceremony":["#BE185D","#D4AF37"],"reception":["#BE185D","#D4AF37","#7A1F2B"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#BE185D","#D4AF37","#7A1F2B"],"guest":["#BE185D","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 20),
  ('bridgerton · regal', 'dark_moody', 'Regal Ilustrado Ballroom', 'Spanish-colonial ilustrado regalia — deep burgundy and antique gold behind a capiz-shell backdrop, fit for an ancestral-house or hacienda reception.', '{"ceremony":["#7A1F2B","#D4AF37"],"reception":["#7A1F2B","#D4AF37","#824A2A"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#D4AF37","#824A2A"],"guest":["#7A1F2B","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"cross_back","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"floral"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 21),
  ('bridgerton · regal', 'dark_moody', 'Emerald Court Hacienda', 'Deep emerald and gold for a regal hacienda-garden reception, gilded rather than sparse.', '{"ceremony":["#059669","#D4AF37"],"reception":["#059669","#D4AF37","#3A5746"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#059669","#D4AF37","#3A5746"],"guest":["#059669","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"runner","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 22),
  ('bridgerton · regal', 'dark_moody', 'Burgundy & Bronze Regal', 'Rich burgundy and bronze for an autumnal, regal hotel-ballroom reception with candlelight warmth.', '{"ceremony":["#7A1F2B","#824A2A"],"reception":["#7A1F2B","#824A2A","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#824A2A","#D4AF37"],"guest":["#7A1F2B","#824A2A","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"cascading"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"velvet","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 23),
  ('bridgerton · regal', 'whimsical_storybook', 'Lavender Duchess Garden', 'Soft lavender and plum for a dreamy, feminine regal garden reception.', '{"ceremony":["#C9B8D9","#5C2542"],"reception":["#C9B8D9","#5C2542","#D4AF37"],"bride":["#FAF7F2"],"groom":["#5C2542"],"wedding_party":["#C9B8D9","#5C2542","#D4AF37"],"guest":["#C9B8D9","#5C2542","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"lounge","florals":"arch"},"tables":{"shape":"round","chairs":"velvet","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 24),
  ('bridgerton · regal', 'dark_moody', 'Navy & Gold Ballroom Regal', 'Navy blue and gold for a dramatic, formal ballroom affair with a full regal spread.', '{"ceremony":["#1E2540","#D4AF37"],"reception":["#1E2540","#D4AF37","#3A5766"],"bride":["#FAF7F2"],"groom":["#1E2540"],"wedding_party":["#1E2540","#D4AF37","#3A5766"],"guest":["#1E2540","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"sequin","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 25),
  ('bridgerton · regal', 'dark_moody', 'Sapphire & Silver Regal', 'Deep sapphire blue and brushed silver — a cool, dramatic regal palette instead of the usual gold.', '{"ceremony":["#1E2540","#CFD3D6"],"reception":["#1E2540","#CFD3D6","#3A5766"],"bride":["#FFFFFF"],"groom":["#1E2540"],"wedding_party":["#1E2540","#CFD3D6","#3A5766"],"guest":["#1E2540","#CFD3D6","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"ghost","linen":"sequin","centerpiece":"candelabra","place":"silver"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 26),
  ('bridgerton · regal', 'maximalist_complex', 'Wine & Rose Gold Regal', 'Deep wine red softened with rose gold — an opulent, romantic regal palette for a candlelit ballroom.', '{"ceremony":["#7A1F2B","#BE185D"],"reception":["#7A1F2B","#BE185D","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#BE185D","#D4AF37"],"guest":["#7A1F2B","#BE185D","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 27),
  ('bridgerton · regal', 'bold_contrasting', 'Peacock & Gold Regal', 'Peacock teal and gold — a bold, jewel-toned regal statement for a couple who wants drama and color both.', '{"ceremony":["#0284C7","#D4AF37"],"reception":["#0284C7","#D4AF37","#3A5766"],"bride":["#FAF7F2"],"groom":["#1E2540"],"wedding_party":["#0284C7","#D4AF37","#3A5766"],"guest":["#0284C7","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 28),
  ('bridgerton · regal', 'dark_moody', 'Plum & Antique Gold Regal', 'Plum and antique gold for a moody, romantic regal look with less red than a classic burgundy palette.', '{"ceremony":["#5C2542","#C5A059"],"reception":["#5C2542","#C5A059","#824A2A"],"bride":["#FAF7F2"],"groom":["#5C2542"],"wedding_party":["#5C2542","#C5A059","#824A2A"],"guest":["#5C2542","#C5A059","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"lounge","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 29),
  ('bridgerton · regal', 'maximalist_complex', 'Ivory & Gold Cathedral Regal', 'Ivory and gold scaled up for a cathedral-sized regal reception — the most restrained palette in the family, but the fullest room.', '{"ceremony":["#FAF7F2","#D4AF37"],"reception":["#FAF7F2","#D4AF37","#C5A059"],"bride":["#FFFFF0"],"groom":["#1E2229"],"wedding_party":["#D4AF37","#C5A059","#FAF7F2"],"guest":["#FAF7F2","#D4AF37","#C5A059"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 30),
  ('bridgerton · regal', 'bold_contrasting', 'Ruby Court Ballroom', 'Ruby red and gold for a vivid, high-drama court-ballroom look — the boldest red in the family.', '{"ceremony":["#BE185D","#D4AF37"],"reception":["#BE185D","#7A1F2B","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#BE185D","#7A1F2B","#D4AF37"],"guest":["#BE185D","#7A1F2B","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 31),
  ('bridgerton · regal', 'dark_moody', 'Midnight Garden Regal', 'Midnight navy against deep greenery and gold — a regal reception staged like a moonlit garden ball.', '{"ceremony":["#1E2540","#3A5746"],"reception":["#1E2540","#3A5746","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2540"],"wedding_party":["#1E2540","#3A5746","#D4AF37"],"guest":["#1E2540","#3A5746","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"greenery","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"greenery"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 32),
  ('bridgerton · regal', 'whimsical_storybook', 'Blush Regency Ballroom', 'Blush pink and gold for the softest, most Bridgerton-pastel reading of a regal ballroom.', '{"ceremony":["#F4C2C2","#D4AF37"],"reception":["#F4C2C2","#D4AF37","#BE185D"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#F4C2C2","#D4AF37","#BE185D"],"guest":["#F4C2C2","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 33),
  ('bridgerton · regal', 'maximalist_complex', 'Amethyst & Gold Regal', 'Amethyst purple and gold — a rich jewel-tone regal palette between lavender softness and plum drama.', '{"ceremony":["#5C2542","#D4AF37"],"reception":["#5C2542","#C9B8D9","#D4AF37"],"bride":["#FAF7F2"],"groom":["#5C2542"],"wedding_party":["#5C2542","#C9B8D9","#D4AF37"],"guest":["#5C2542","#C9B8D9","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 34),
  ('bridgerton · regal', 'maximalist_complex', 'Champagne Court Regal', 'Champagne gold on champagne gold, layered — a monochrome-metallic take on regal opulence.', '{"ceremony":["#C5A059","#D4AF37"],"reception":["#C5A059","#D4AF37","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#C5A059","#D4AF37","#FAF7F2"],"guest":["#C5A059","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"sequin","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 35),
  ('bridgerton · regal', 'dark_moody', 'Forest & Gold Regal Hacienda', 'Forest green and antique gold for a regal reception set among real trees — an ancestral-house garden at dusk.', '{"ceremony":["#3A5746","#D4AF37"],"reception":["#3A5746","#D4AF37","#824A2A"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#3A5746","#D4AF37","#824A2A"],"guest":["#3A5746","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"greenery","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"cross_back","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"greenery"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 36),
  ('bridgerton · regal', 'bold_contrasting', 'Crimson & Ivory Regal', 'Crimson against ivory for a high-contrast, dramatic regal reception — the boldest pairing in the family.', '{"ceremony":["#7A1F2B","#FAF7F2"],"reception":["#7A1F2B","#FAF7F2","#D4AF37"],"bride":["#FFFFF0"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#FAF7F2","#D4AF37"],"guest":["#7A1F2B","#FAF7F2","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 37),
  ('bridgerton · regal', 'maximalist_complex', 'Bronze Rose Regal', 'Bronze and dusty rose for a warmer, softer regal look than the family’s usual gold-and-jewel-tone pairings.', '{"ceremony":["#824A2A","#C9A0A0"],"reception":["#824A2A","#C9A0A0","#D4AF37"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#824A2A","#C9A0A0","#D4AF37"],"guest":["#824A2A","#C9A0A0","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"cascading"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"draped"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 38),
  ('bridgerton · regal', 'dark_moody', 'Obsidian & Gold Regal', 'Near-black paired with gold — the darkest, most dramatic regal palette in the family, for a couple unafraid of drama.', '{"ceremony":["#1E2229","#D4AF37"],"reception":["#1E2229","#D4AF37","#7A1F2B"],"bride":["#FAF7F2"],"groom":["#000000"],"wedding_party":["#1E2229","#D4AF37","#7A1F2B"],"guest":["#1E2229","#D4AF37","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"chandeliers"},"backdrop":{"style":"draped","florals":"full"},"stage":{"setup":"king_queen","florals":"arch"},"tables":{"shape":"round","chairs":"chiavari","linen":"full_drape","centerpiece":"candelabra","place":"gold"},"tunnel":{"style":"crystal"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 39),
  ('editorial cream', 'minimalist', 'Industrial Loft Chic', 'Concrete grey and charcoal against warm cream — a stripped-back, industrial-loft reception for a couple who wants exposed brick over ballrooms.', '{"ceremony":["#CFD3D6","#1E2229"],"reception":["#CFD3D6","#1E2229","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#1E2229","#FAF7F2"],"guest":["#CFD3D6","#1E2229","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"ghost","linen":"plain","centerpiece":"low","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 40),
  ('editorial cream', 'simple_understated', 'Terracotta Sunlit Editorial', 'Warm terracotta and rust for a sun-drenched, editorial garden-resort reception.', '{"ceremony":["#C97B4B","#824A2A"],"reception":["#C97B4B","#824A2A","#D08654"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#C97B4B","#824A2A","#D08654"],"guest":["#FAF7F2","#C97B4B","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"table_runner"},"tables":{"shape":"long","chairs":"bentwood","linen":"runner","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"floral_lined"},"people":{"who":"couple"}}'::jsonb, 41),
  ('editorial cream', 'simple_understated', 'Warm Neutral Editorial', 'Warm beige, sand, and walnut tones — an editorial reception that leans into natural materials over ornament.', '{"ceremony":["#FAF7F2","#824A2A"],"reception":["#F0B27A","#824A2A","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#F0B27A","#824A2A","#FAF7F2"],"guest":["#FAF7F2","#F0B27A","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"cross_back","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 42),
  ('editorial cream', 'minimalist', 'Camel & Ivory Studio', 'Camel and ivory with a single black accent — a controlled, studio-quality editorial palette.', '{"ceremony":["#FFFFF0","#824A2A"],"reception":["#FFFFF0","#824A2A","#1E2229"],"bride":["#FFFFF0"],"groom":["#1E2229"],"wedding_party":["#824A2A","#FFFFF0","#1E2229"],"guest":["#FFFFF0","#824A2A","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"bentwood","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 43),
  ('editorial cream', 'minimalist', 'Piña Ivory Editorial', 'Piña and jusi ivory tones kept spare and editorial — a barong-inspired neutral palette for a minimalist couple who still wants a Filipino texture story.', '{"ceremony":["#FAF7F2","#3A5766"],"reception":["#FFFFF0","#3A5766","#FAF7F2"],"bride":["#FFFFF0"],"groom":["#FFFFF0"],"wedding_party":["#FFFFF0","#3A5766","#FAF7F2"],"guest":["#FAF7F2","#FFFFF0","#3A5766"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"low","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 44),
  ('editorial cream', 'minimalist', 'Soft Stone Editorial', 'Muted stone grey and cream for a calm, architectural editorial reception.', '{"ceremony":["#FAF7F2","#3A5766"],"reception":["#CFD3D6","#3A5766","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#3A5766"],"wedding_party":["#CFD3D6","#3A5766","#FAF7F2"],"guest":["#FAF7F2","#CFD3D6","#3A5766"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"low","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 45),
  ('editorial cream', 'simple_understated', 'Sandstone & Sage Editorial', 'Sandstone beige with a quiet sage accent — an earthy, calm editorial palette for a daytime reception.', '{"ceremony":["#F0B27A","#8A9A6B"],"reception":["#F0B27A","#8A9A6B","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#F0B27A","#8A9A6B","#FAF7F2"],"guest":["#FAF7F2","#F0B27A","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"plain","centerpiece":"greenery_runner","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 46),
  ('editorial cream', 'minimalist', 'Charcoal & Cream Studio Editorial', 'Charcoal and cream in equal measure — an editorial two-tone palette with nothing else competing for attention.', '{"ceremony":["#FAF7F2","#1E2229"],"reception":["#1E2229","#FAF7F2","#CFD3D6"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#1E2229","#FAF7F2","#CFD3D6"],"guest":["#1E2229","#FAF7F2","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 47),
  ('editorial cream', 'bold_contrasting', 'Rust & Bone Editorial', 'Rust orange against bone white — a warm-cool contrast editorial palette with real punch, kept in a spare layout.', '{"ceremony":["#824A2A","#FAF7F2"],"reception":["#824A2A","#FAF7F2","#C97B4B"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#824A2A","#FAF7F2","#C97B4B"],"guest":["#824A2A","#FAF7F2","#C97B4B"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"runner","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 48),
  ('editorial cream', 'simple_understated', 'Olive & Ecru Editorial', 'Olive green and ecru — an unusual, quietly modern editorial pairing for a couple who wants natural over floral.', '{"ceremony":["#8A9A6B","#FAF7F2"],"reception":["#8A9A6B","#FAF7F2","#3A5746"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#8A9A6B","#FAF7F2","#3A5746"],"guest":["#8A9A6B","#FAF7F2","#3A5746"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"cross_back","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 49),
  ('editorial cream', 'minimalist', 'Barong Ivory & Slate Editorial', 'Piña-white barong tones against cool slate — a Filipino-material editorial palette with a modern, restrained finish.', '{"ceremony":["#FFFFF0","#3A5766"],"reception":["#FFFFF0","#3A5766","#CFD3D6"],"bride":["#FFFFF0"],"groom":["#FFFFF0"],"wedding_party":["#3A5766","#FFFFF0","#CFD3D6"],"guest":["#FFFFF0","#3A5766","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 50),
  ('editorial cream', 'simple_understated', 'Amber Studio Editorial', 'Amber and walnut brown for a warm, cinematic editorial look shot best in late-afternoon light.', '{"ceremony":["#D97706","#824A2A"],"reception":["#D97706","#824A2A","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#D97706","#824A2A","#FAF7F2"],"guest":["#FAF7F2","#D97706","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 51),
  ('editorial cream', 'minimalist', 'Dove Grey Studio Minimal', 'Dove grey on dove grey — a near-monochrome editorial palette, the most minimal in the family.', '{"ceremony":["#CFD3D6","#FAF7F2"],"reception":["#CFD3D6","#FAF7F2","#3A5766"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#FAF7F2","#3A5766"],"guest":["#CFD3D6","#FAF7F2","#3A5766"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 52),
  ('editorial cream', 'bold_contrasting', 'Terracotta & Charcoal Editorial', 'Terracotta orange against deep charcoal — a bolder editorial pairing that still reads controlled, not busy.', '{"ceremony":["#C97B4B","#1E2229"],"reception":["#C97B4B","#1E2229","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#C97B4B","#1E2229","#FAF7F2"],"guest":["#C97B4B","#1E2229","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"runner","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 53),
  ('editorial cream', 'simple_understated', 'Wheat & Ivory Editorial', 'Sun-bleached wheat tones against ivory — a soft, quiet editorial palette that reads like a Tuscan-meets-Batangas field.', '{"ceremony":["#FAF7F2","#F0B27A"],"reception":["#F0B27A","#FAF7F2","#824A2A"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#F0B27A","#FAF7F2","#824A2A"],"guest":["#FAF7F2","#F0B27A","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 54),
  ('editorial cream', 'dark_moody', 'Onyx & Champagne Editorial', 'Onyx black with a champagne-gold whisper — a refined, moody editorial look for an evening reception.', '{"ceremony":["#1E2229","#C5A059"],"reception":["#1E2229","#C5A059","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#1E2229","#C5A059","#FAF7F2"],"guest":["#1E2229","#C5A059","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 55),
  ('editorial cream', 'simple_understated', 'Blush Studio Editorial', 'Blush pink against warm cream — the softest, most romantic reading of "editorial" in this family.', '{"ceremony":["#F4C2C2","#FAF7F2"],"reception":["#F4C2C2","#FAF7F2","#824A2A"],"bride":["#F4C2C2"],"groom":["#824A2A"],"wedding_party":["#F4C2C2","#FAF7F2","#824A2A"],"guest":["#FAF7F2","#F4C2C2","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 56),
  ('editorial cream', 'simple_understated', 'Espresso & Cream Editorial', 'Deep espresso brown against warm cream — a grounded, coffee-toned editorial palette.', '{"ceremony":["#824A2A","#FAF7F2"],"reception":["#824A2A","#FAF7F2","#1E2229"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#824A2A","#FAF7F2","#1E2229"],"guest":["#824A2A","#FAF7F2","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"cross_back","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 57),
  ('editorial cream', 'minimalist', 'Sage & Stone Minimal Editorial', 'Sage green and cool stone grey — a nature-adjacent minimal editorial palette with no warmth at all.', '{"ceremony":["#8A9A6B","#CFD3D6"],"reception":["#8A9A6B","#CFD3D6","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#3A5746"],"wedding_party":["#8A9A6B","#CFD3D6","#FAF7F2"],"guest":["#8A9A6B","#CFD3D6","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 58),
  ('editorial cream', 'maximalist_complex', 'Golden Wheat Loft Editorial', 'Golden wheat tones inside an industrial-loft shell — pairing this family’s two signature moods, warm color and raw architecture.', '{"ceremony":["#D4AF37","#824A2A"],"reception":["#D4AF37","#824A2A","#1E2229"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#D4AF37","#824A2A","#1E2229"],"guest":["#D4AF37","#824A2A","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 59),
  ('tropical heritage', 'maximalist_complex', 'Rustic Filipiniana Heritage', 'Banig weave, narra wood, and capiz shell under a banana-leaf canopy — a proudly Filipiniana reception for an ancestral house or garden.', '{"ceremony":["#E8735A","#824A2A"],"reception":["#E8735A","#D4AF37","#059669"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#E8735A","#D4AF37","#059669"],"guest":["#FAF7F2","#E8735A","#059669"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 60),
  ('tropical heritage', 'whimsical_storybook', 'Tropical Garden Waling-Waling', 'Waling-waling orchids and banana-leaf greenery for a lush tropical-garden reception by the coast or in a resort garden.', '{"ceremony":["#3A5746","#F4C2C2"],"reception":["#3A5746","#8A9A6B","#F4C2C2"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#3A5746","#8A9A6B","#F4C2C2"],"guest":["#FAF7F2","#3A5746","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"long","chairs":"cross_back","linen":"runner","centerpiece":"tall","place":"none"},"tunnel":{"style":"greenery"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 61),
  ('tropical heritage', 'simple_understated', 'Boho Beach Piña & Rattan', 'Piña-fabric neutrals, bamboo and rattan structures, and a barefoot-beach feel — relaxed boho for a shoreline reception.', '{"ceremony":["#FAF7F2","#7DB8D9"],"reception":["#F0B27A","#7DB8D9","#FAF7F2"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#F0B27A","#7DB8D9","#FAF7F2"],"guest":["#FAF7F2","#F0B27A","#7DB8D9"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"round","chairs":"bentwood","linen":"banig","centerpiece":"low","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"none"},"people":{"who":"everyone"}}'::jsonb, 62),
  ('tropical heritage', 'maximalist_complex', 'Piña & Capiz Ilustrado Heritage', 'Piña ivory, capiz shell, and antique gold — an heirloom-inspired heritage look for an ancestral-house wedding.', '{"ceremony":["#FAF7F2","#D97706"],"reception":["#FFFFF0","#D97706","#D4AF37"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#D97706","#D4AF37","#FAF7F2"],"guest":["#FAF7F2","#D97706","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"lanterns"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"lanterns","place":"gold"},"tunnel":{"style":"lantern"},"entrance":{"runner":"petals"},"people":{"who":"everyone"}}'::jsonb, 63),
  ('tropical heritage', 'maximalist_complex', 'Sampaguita & Gold Heritage', 'Sampaguita garlands and heritage gold against banana-leaf greenery — fragrant, festive, and unmistakably Filipino, for a church or garden wedding.', '{"ceremony":["#D97706","#059669"],"reception":["#FAF7F2","#D97706","#059669"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#D97706","#059669","#FAF7F2"],"guest":["#FAF7F2","#D97706","#059669"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"bentwood","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 64),
  ('tropical heritage', 'simple_understated', 'Ilang-Ilang Ivory Heritage', 'Ilang-ilang cream and soft gold — a fragrant, understated heritage palette centered on one of the Philippines’ most beloved wedding blooms.', '{"ceremony":["#FAF7F2","#D4AF37"],"reception":["#FAF7F2","#D4AF37","#8A9A6B"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#D4AF37","#8A9A6B","#FAF7F2"],"guest":["#FAF7F2","#D4AF37","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"draped","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"chiavari","linen":"plain","centerpiece":"sampaguita","place":"gold"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 65),
  ('tropical heritage', 'simple_understated', 'Banig & Bamboo Garden Heritage', 'Woven banig and bamboo structure throughout, unpainted and natural — a heritage look that celebrates craft materials over color.', '{"ceremony":["#824A2A","#8A9A6B"],"reception":["#824A2A","#8A9A6B","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#824A2A","#8A9A6B","#FAF7F2"],"guest":["#FAF7F2","#824A2A","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"none"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"greenery_runner","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 66),
  ('tropical heritage', 'simple_understated', 'Coconut Grove Heritage', 'Deep coconut-grove greens and sun-bleached wood for a heritage reception staged by the coast.', '{"ceremony":["#3A5746","#FAF7F2"],"reception":["#3A5746","#8A9A6B","#D4AF37"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#3A5746","#8A9A6B","#D4AF37"],"guest":["#FAF7F2","#3A5746","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"corner"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"long","chairs":"cross_back","linen":"plain","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"none"},"people":{"who":"everyone"}}'::jsonb, 67),
  ('tropical heritage', 'bold_contrasting', 'Mango & Malachite Heritage', 'Sunny mango yellow against deep malachite green — a bold tropical-heritage statement.', '{"ceremony":["#D97706","#059669"],"reception":["#D97706","#059669","#3A5746"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#D97706","#059669","#3A5746"],"guest":["#FAF7F2","#D97706","#059669"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"runner","centerpiece":"tall","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 68),
  ('tropical heritage', 'bold_contrasting', 'Coral Reef Fiesta Heritage', 'Coral, sky blue, and white for a bright, festive island-wedding energy.', '{"ceremony":["#FAF7F2","#7DB8D9"],"reception":["#E8735A","#7DB8D9","#FAF7F2"],"bride":["#FAF7F2"],"groom":["#1E2540"],"wedding_party":["#E8735A","#7DB8D9","#FAF7F2"],"guest":["#FAF7F2","#E8735A","#7DB8D9"]}'::jsonb, '{"ceiling":{"treatment":"fairy_lights"},"backdrop":{"style":"balloon","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"round","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"balloon"},"entrance":{"runner":"none"},"people":{"who":"everyone"}}'::jsonb, 69),
  ('tropical heritage', 'bold_contrasting', 'Barrio Fiesta Heritage', 'Bright red, yellow, and green — a barrio-fiesta color story, festive and unapologetically loud, for a heritage-forward reception.', '{"ceremony":["#7A1F2B","#D97706"],"reception":["#7A1F2B","#D97706","#059669"],"bride":["#FAF7F2"],"groom":["#7A1F2B"],"wedding_party":["#7A1F2B","#D97706","#059669"],"guest":["#FAF7F2","#7A1F2B","#D97706"]}'::jsonb, '{"ceiling":{"treatment":"lanterns"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"lanterns","place":"none"},"tunnel":{"style":"lantern"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 70),
  ('tropical heritage', 'whimsical_storybook', 'Kalachuchi Sunset Heritage', 'Kalachuchi (frangipani) pink and gold against a sunset-orange sky — a warm, floral-forward heritage palette.', '{"ceremony":["#F4C2C2","#D97706"],"reception":["#F4C2C2","#D97706","#D4AF37"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#F4C2C2","#D97706","#D4AF37"],"guest":["#FAF7F2","#F4C2C2","#D97706"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 71),
  ('tropical heritage', 'simple_understated', 'Bahay Kubo Heritage', 'Nipa-and-bamboo neutral tones, entirely unpainted — the most rustic, materials-only reading of "heritage" in this family.', '{"ceremony":["#824A2A","#FAF7F2"],"reception":["#824A2A","#FAF7F2","#8A9A6B"],"bride":["#FFFFF0"],"groom":["#824A2A"],"wedding_party":["#824A2A","#FAF7F2","#8A9A6B"],"guest":["#FAF7F2","#824A2A","#8A9A6B"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"greenery_runner","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"none"},"people":{"who":"everyone"}}'::jsonb, 72),
  ('tropical heritage', 'maximalist_complex', 'Golden Palm Heritage', 'Golden hour tones filtered through palm shade — warm amber, deep green, and capiz shimmer for a late-afternoon garden reception.', '{"ceremony":["#D4AF37","#3A5746"],"reception":["#D4AF37","#3A5746","#824A2A"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#D4AF37","#3A5746","#824A2A"],"guest":["#FAF7F2","#D4AF37","#3A5746"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 73),
  ('tropical heritage', 'minimalist', 'Ivory Piña Beach Heritage', 'All-ivory piña fabric against a bright beach backdrop — the most restrained possible heritage palette.', '{"ceremony":["#FFFFF0","#7DB8D9"],"reception":["#FFFFF0","#7DB8D9","#FAF7F2"],"bride":["#FFFFF0"],"groom":["#FFFFF0"],"wedding_party":["#7DB8D9","#FFFFF0","#FAF7F2"],"guest":["#FFFFF0","#7DB8D9","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"round","chairs":"bentwood","linen":"plain","centerpiece":"low","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"everyone"}}'::jsonb, 74),
  ('tropical heritage', 'maximalist_complex', 'Anahaw & Amber Heritage', 'Anahaw-leaf green and amber gold — a heritage palette named for the Philippines’ national leaf, used throughout the canopy and runners.', '{"ceremony":["#3A5746","#D4AF37"],"reception":["#3A5746","#D4AF37","#059669"],"bride":["#FAF7F2"],"groom":["#3A5746"],"wedding_party":["#3A5746","#D4AF37","#059669"],"guest":["#FAF7F2","#3A5746","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 75),
  ('tropical heritage', 'bold_contrasting', 'Jeepney Fiesta Heritage', 'Chrome silver, red, and gold — a jeepney-inspired maximalist fiesta palette, loud and proudly Filipino.', '{"ceremony":["#7A1F2B","#CFD3D6"],"reception":["#7A1F2B","#CFD3D6","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#CFD3D6","#D4AF37"],"guest":["#FAF7F2","#7A1F2B","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"lanterns"},"backdrop":{"style":"capiz","florals":"corner"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"lanterns","place":"silver"},"tunnel":{"style":"lantern"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 76),
  ('tropical heritage', 'dark_moody', 'Moonlit Mangrove Heritage', 'Deep mangrove green under moonlight, with capiz catching what light there is — a moody, nighttime heritage reception.', '{"ceremony":["#3A5746","#1E2229"],"reception":["#3A5746","#1E2229","#D4AF37"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#3A5746","#1E2229","#D4AF37"],"guest":["#3A5746","#1E2229","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"none"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"candles","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"candle"},"people":{"who":"everyone"}}'::jsonb, 77),
  ('tropical heritage', 'bold_contrasting', 'Tropical Sunset Boho Heritage', 'Sunset coral, gold, and deep teal for a boho-tropical reception that leans warm and saturated rather than pastel.', '{"ceremony":["#E8735A","#D4AF37"],"reception":["#E8735A","#D4AF37","#0284C7"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#E8735A","#D4AF37","#0284C7"],"guest":["#FAF7F2","#E8735A","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"greenery","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"sampaguita","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 78),
  ('tropical heritage', 'maximalist_complex', 'Waling-Waling Regal Heritage', 'The Philippines’ queen of orchids in deep purple and gold — a heritage palette dressed up for a formal ancestral-house evening.', '{"ceremony":["#5C2542","#D4AF37"],"reception":["#5C2542","#D4AF37","#3A5746"],"bride":["#FAF7F2"],"groom":["#5C2542"],"wedding_party":["#5C2542","#D4AF37","#3A5746"],"guest":["#FAF7F2","#5C2542","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"banana_leaf"},"backdrop":{"style":"capiz","florals":"full"},"stage":{"setup":"sweetheart","florals":"pedestals"},"tables":{"shape":"round","chairs":"cross_back","linen":"banig","centerpiece":"candelabra","place":"none"},"tunnel":{"style":"bamboo"},"entrance":{"runner":"floral_lined"},"people":{"who":"everyone"}}'::jsonb, 79),
  ('modern minimalist', 'minimalist', 'Modern Minimalist Ballroom', 'Charcoal, bone, and brushed silver with no ornament — a confident, geometric hotel-ballroom reception.', '{"ceremony":["#1E2229","#CFD3D6"],"reception":["#1E2229","#CFD3D6","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#1E2229","#CFD3D6","#FAF7F2"],"guest":["#1E2229","#CFD3D6","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 80),
  ('modern minimalist', 'bold_contrasting', 'Monochrome Editorial Modern', 'Black, white, and one shot of red — a graphic, monochrome-plus-one modern palette for a design-forward couple.', '{"ceremony":["#000000","#FFFFFF"],"reception":["#000000","#FFFFFF","#BE185D"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#000000","#FFFFFF","#BE185D"],"guest":["#000000","#FFFFFF","#BE185D"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"sequin","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 81),
  ('modern minimalist', 'minimalist', 'Slate & Silver Modern', 'Slate blue and brushed silver for a cool, contemporary modern-minimalist ballroom look.', '{"ceremony":["#3A5766","#CFD3D6"],"reception":["#3A5766","#CFD3D6","#1E2540"],"bride":["#FFFFFF"],"groom":["#1E2540"],"wedding_party":["#3A5766","#CFD3D6","#1E2540"],"guest":["#3A5766","#CFD3D6","#FFFFFF"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 82),
  ('modern minimalist', 'bold_contrasting', 'Black & White Geometric', 'A sharp black-and-white palette with geometric ceiling installations and a mirrored aisle for a design-forward couple.', '{"ceremony":["#FFFFFF","#000000"],"reception":["#FFFFFF","#000000","#CFD3D6"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#FFFFFF","#000000","#CFD3D6"],"guest":["#FFFFFF","#000000","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"sweetheart","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"mirror"},"people":{"who":"couple"}}'::jsonb, 83),
  ('modern minimalist', 'minimalist', 'Concrete & Sage Modern', 'Concrete grey warmed with sage green — a modern-minimalist palette that still feels organic, for a loft or garden-adjacent venue.', '{"ceremony":["#CFD3D6","#8A9A6B"],"reception":["#CFD3D6","#8A9A6B","#1E2229"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#8A9A6B","#1E2229"],"guest":["#CFD3D6","#8A9A6B","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"greenery","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"bentwood","linen":"plain","centerpiece":"greenery_runner","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 84),
  ('modern minimalist', 'dark_moody', 'Ink & Bone Modern', 'Deep ink black against pale bone — a stark two-tone modern palette, the darkest in the family.', '{"ceremony":["#000000","#FAF7F2"],"reception":["#000000","#FAF7F2","#1E2229"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#000000","#FAF7F2","#1E2229"],"guest":["#000000","#FAF7F2","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 85),
  ('modern minimalist', 'bold_contrasting', 'Cobalt & White Modern', 'Bold cobalt blue against crisp white — a saturated, high-contrast modern palette.', '{"ceremony":["#0284C7","#FFFFFF"],"reception":["#0284C7","#FFFFFF","#1E2540"],"bride":["#FFFFFF"],"groom":["#1E2540"],"wedding_party":["#0284C7","#FFFFFF","#1E2540"],"guest":["#0284C7","#FFFFFF","#1E2540"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 86),
  ('modern minimalist', 'simple_understated', 'Warm Grey Studio Modern', 'Warm greige instead of stark charcoal — a softer, gentler take on the modern-minimalist family.', '{"ceremony":["#CFD3D6","#FAF7F2"],"reception":["#CFD3D6","#FAF7F2","#824A2A"],"bride":["#FAF7F2"],"groom":["#824A2A"],"wedding_party":["#CFD3D6","#FAF7F2","#824A2A"],"guest":["#CFD3D6","#FAF7F2","#824A2A"]}'::jsonb, '{"ceiling":{"treatment":"bare"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 87),
  ('modern minimalist', 'bold_contrasting', 'Emerald Glass Modern', 'Emerald green through glass and steel — a modern jewel-tone palette kept spare and architectural.', '{"ceremony":["#059669","#FFFFFF"],"reception":["#059669","#FFFFFF","#1E2229"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#059669","#FFFFFF","#1E2229"],"guest":["#059669","#FFFFFF","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 88),
  ('modern minimalist', 'simple_understated', 'Taupe & Steel Modern', 'Taupe and cool steel grey — a quiet, corporate-adjacent modern palette for a design-minded couple who wants zero drama.', '{"ceremony":["#CFD3D6","#824A2A"],"reception":["#CFD3D6","#824A2A","#1E2229"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#CFD3D6","#824A2A","#1E2229"],"guest":["#CFD3D6","#824A2A","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 89),
  ('modern minimalist', 'dark_moody', 'Merlot & Concrete Modern', 'Deep merlot red against raw concrete — a moody, architectural modern palette.', '{"ceremony":["#7A1F2B","#CFD3D6"],"reception":["#7A1F2B","#CFD3D6","#1E2229"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#7A1F2B","#CFD3D6","#1E2229"],"guest":["#7A1F2B","#CFD3D6","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 90),
  ('modern minimalist', 'minimalist', 'Pure White Minimal Modern', 'All white, no accent color at all — the most minimal palette in the entire gallery.', '{"ceremony":["#FFFFFF","#FFFFFF"],"reception":["#FFFFFF","#CFD3D6","#FAF7F2"],"bride":["#FFFFFF"],"groom":["#FFFFFF"],"wedding_party":["#FFFFFF","#CFD3D6","#FAF7F2"],"guest":["#FFFFFF","#CFD3D6","#FAF7F2"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"draped","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 91),
  ('modern minimalist', 'maximalist_complex', 'Amber Glass Modern', 'Warm amber glass against charcoal steel — a modern palette with one warm accent breaking the cool base.', '{"ceremony":["#D97706","#1E2229"],"reception":["#D97706","#1E2229","#CFD3D6"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#D97706","#1E2229","#CFD3D6"],"guest":["#D97706","#1E2229","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"glass"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 92),
  ('modern minimalist', 'simple_understated', 'Ash Rose Modern', 'Ash rose (a dusty, greyed pink) against charcoal — a modern palette with a single soft accent.', '{"ceremony":["#C9A0A0","#1E2229"],"reception":["#C9A0A0","#1E2229","#CFD3D6"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#C9A0A0","#1E2229","#CFD3D6"],"guest":["#C9A0A0","#1E2229","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 93),
  ('modern minimalist', 'minimalist', 'Graphite & Gold Line Modern', 'Graphite grey with a single thin gold line — the family’s only metallic accent, used sparingly.', '{"ceremony":["#1E2229","#D4AF37"],"reception":["#1E2229","#D4AF37","#CFD3D6"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#1E2229","#D4AF37","#CFD3D6"],"guest":["#1E2229","#D4AF37","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"gold"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 94),
  ('modern minimalist', 'bold_contrasting', 'Deep Teal Modern', 'Deep teal against white — a cool, saturated modern palette between calm and bold.', '{"ceremony":["#3A5766","#FFFFFF"],"reception":["#3A5766","#FFFFFF","#1E2229"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#3A5766","#FFFFFF","#1E2229"],"guest":["#3A5766","#FFFFFF","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 95),
  ('modern minimalist', 'dark_moody', 'Storm Grey Modern', 'Storm grey with near-black accents — a brooding, low-key modern palette without any warm tone at all.', '{"ceremony":["#3A5766","#1E2229"],"reception":["#3A5766","#1E2229","#CFD3D6"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#3A5766","#1E2229","#CFD3D6"],"guest":["#3A5766","#1E2229","#CFD3D6"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 96),
  ('modern minimalist', 'minimalist', 'Blush Line Modern', 'White and charcoal with a thin blush line — nearly monochrome, one soft color kept to a minimum.', '{"ceremony":["#FFFFFF","#F4C2C2"],"reception":["#FFFFFF","#F4C2C2","#1E2229"],"bride":["#FFFFFF"],"groom":["#1E2229"],"wedding_party":["#FFFFFF","#F4C2C2","#1E2229"],"guest":["#FFFFFF","#F4C2C2","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"none"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 97),
  ('modern minimalist', 'maximalist_complex', 'Copper Wire Modern', 'Copper metal accents against cool grey — an industrial-adjacent modern palette with warmth from metal, not color.', '{"ceremony":["#C97B4B","#CFD3D6"],"reception":["#C97B4B","#CFD3D6","#1E2229"],"bride":["#FAF7F2"],"groom":["#1E2229"],"wedding_party":["#C97B4B","#CFD3D6","#1E2229"],"guest":["#C97B4B","#CFD3D6","#1E2229"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"plain","centerpiece":"candles","place":"gold"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 98),
  ('modern minimalist', 'dark_moody', 'Full Black Modern Statement', 'All black — walls, linens, chairs — for the boldest, most maximal-through-restriction reading of "modern" in this family.', '{"ceremony":["#000000","#1E2229"],"reception":["#000000","#1E2229","#D4AF37"],"bride":["#FFFFFF"],"groom":["#000000"],"wedding_party":["#000000","#1E2229","#D4AF37"],"guest":["#000000","#1E2229","#D4AF37"]}'::jsonb, '{"ceiling":{"treatment":"geometric"},"backdrop":{"style":"led","florals":"none"},"stage":{"setup":"lounge","florals":"none"},"tables":{"shape":"square","chairs":"ghost","linen":"sequin","centerpiece":"candles","place":"gold"},"tunnel":{"style":"none"},"entrance":{"runner":"none"},"people":{"who":"couple"}}'::jsonb, 99);

  END IF;
END $$;

COMMENT ON TABLE public.moodboard_theme_templates IS
  'Curated starter "Overall Theme" gallery for the Mood Board (2026-09-03), 100 rows across 5 style_family values x a mix of 6 mood_tag values. Applying a template (applyMoodboardTemplate) fills only EMPTY palette roles / reception zones / inspiration slots / theme name+description on the couple''s own event — never overwrites anything already set. style_family reuses moodboard_library_assets.style_theme''s 5-value vocabulary so template application can look up matching figure_attire assets for inspiration-slot suggestions; mood_tag is an independent second filter axis for the gallery UI.';
