-- ============================================================================
-- 20270812329751_user_reports_event_and_profile_targets.sql
-- Widen the shared user_reports queue to cover two new PUBLIC-page targets:
--   • 'event'         — the public invitation page /[slug] (social-share item #8)
--   • 'user_profile'  — the public profile page /u/[slug] (profile item #7c)
--
-- WHY THIS EXISTS
--   The Social-Sharing follow-through (2026-07-16, owner-approved) adds a
--   one-tap public share button to the invitation page. The council gated that
--   on an abuse-report path existing FIRST. Rather than stand up a second
--   moderation surface (solo-op red line), reports of a public event page — and,
--   forward-compat, a public profile page — ride the EXISTING user_reports
--   queue (migration 20261108000000 · Apple 1.2 / Google Play UGC) and resolve
--   at /admin/user-reports (hide/block/escalate/dismiss). Both new target types
--   land NOW so item #7c needs no second migration.
--
-- TWO schema changes, both minimal + idempotent:
--   1. target_type CHECK — add 'event' and 'user_profile' to the allowed set.
--      Follows the same drop-by-definition-then-readd pattern as the 'ai_output'
--      widening (20261113000000) so it's robust to a renamed/re-minted CHECK.
--   2. event_id NULLABILITY — a 'user_profile' report is not tied to any event,
--      so event_id must be nullable. The column was NOT NULL (every prior target
--      is event-scoped). Drop NOT NULL, and add a guarding CHECK so the
--      event-scoped targets still REQUIRE an event_id (only 'user_profile' may
--      omit it). Existing rows all carry an event_id, so the guard is satisfied.
--
--   No RLS change. The existing policies still hold:
--     • couple read  — event_id IN current_event_ids(); a NULL event_id (a
--       profile report) simply never matches a couple, so only admins see it —
--       which is exactly right (a profile report is not any couple's business).
--     • admin read/update — is_admin(), unchanged.
--   The public-page report is filed server-side (service role) by the reusable
--   "Report this page" entry (lib/reports.ts), mirroring how the guest-camera
--   report path already writes this table.
--
-- IDEMPOTENT. Safe to (re-)apply. Does NOT touch prod here.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Widen the target_type CHECK to include 'event' + 'user_profile'.
--    Drop every CHECK on user_reports that mentions target_type (by definition,
--    not just by the autogenerated name — robust to a renamed constraint), then
--    re-add the canonical named constraint with the full allowed set.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
  c RECORD;
BEGIN
  FOR c IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'user_reports'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%target_type%'
  LOOP
    EXECUTE format('ALTER TABLE public.user_reports DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE public.user_reports
  ADD CONSTRAINT user_reports_target_type_check
  CHECK (target_type IN ('photo', 'comment', 'user', 'ai_output', 'event', 'user_profile'));

-- ----------------------------------------------------------------------------
-- 2. event_id becomes nullable (a 'user_profile' report is not event-scoped),
--    guarded so every event-scoped target still REQUIRES an event_id.
-- ----------------------------------------------------------------------------
ALTER TABLE public.user_reports
  ALTER COLUMN event_id DROP NOT NULL;

-- Drop any prior copy of the guard, then (re-)add it. Only 'user_profile' may
-- have a NULL event_id; every other target must carry one.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'user_reports_event_id_required_check'
      AND conrelid = 'public.user_reports'::regclass
  ) THEN
    ALTER TABLE public.user_reports DROP CONSTRAINT user_reports_event_id_required_check;
  END IF;
END $$;

ALTER TABLE public.user_reports
  ADD CONSTRAINT user_reports_event_id_required_check
  CHECK (target_type = 'user_profile' OR event_id IS NOT NULL);

COMMENT ON TABLE public.user_reports IS
  'UGC + AI-output + public-page report queue (Apple 1.2 / Google Play UGC + '
  'Play GenAI policy). One row per report: Papic guest gallery content '
  '(photo/user), a Setnayan AI generation (ai_output), a public invitation page '
  '(event · target_id = events.event_id), or a public profile page '
  '(user_profile · target_id = users.user_id, event_id NULL). Routes to the '
  'couple (event RLS, when event-scoped) and always to Setnayan admins '
  '(is_admin), resolved at /admin/user-reports.';

COMMIT;

-- Verification:
--   SELECT pg_get_constraintdef(oid) FROM pg_constraint
--   WHERE conname = 'user_reports_target_type_check';
--   -- Expect: CHECK (target_type IN
--   --   ('photo','comment','user','ai_output','event','user_profile')).
--   SELECT is_nullable FROM information_schema.columns
--   WHERE table_name = 'user_reports' AND column_name = 'event_id';  -- YES
